### ISSUE TITLE
Technical review Tracking and tracing audiovisual reuse: Introducing the Video Reuse Detector

### ISSUE THREAD

**Issue by eliselavy** [C2DH/jdh-notebook#103]
Question about the use of Ffmpeg

https://github.com/jdh-observer/BuWvtJFxh3wy

**Comment by eliselavy** [comment]
Problem in preview: https://journalofdigitalhistory.org/en/notebook-viewer/JTJGcHJveHktZ2l0aHVidXNlcmNvbnRlbnQlMkZUb21hc1Nrb3RhcmUlMkZ0ZXN0X3ZyZF9yZXBvJTJGbWFpbiUyRlRyYWNraW5nJTI1MjAtJTI1MjBNYXJpYSUyNTIwZWRpdGlvbiUyNTIwdy4lMjUyMFRvbWFzJTI1MjBGaXhlcy1WMTAuaXB5bmI=

**Comment by eliselavy** [comment]
About the images, time to implement the gallery tag  https://github.com/C2DH/journal-of-digital-history/issues/98
<img width="1105" alt="Screenshot 2023-04-04 at 12 14 13" src="https://user-images.githubusercontent.com/35602279/229761207-bd23658c-9f60-4e76-ac84-6def65cdf02c.png">
Need to speak with @danieleguido at the JDH's meeting

**Comment by mariacheriksson** [comment]
Hi Elisabeth! A gallery function seems like a nice idea for the journal but unfortunately, I think it won't help us in our article. What we are asking for is really a feature for making the outputs in a code cell scrollable (so you don't see all outputs at once and can navigate up and down). If you open our notebook in a regular Jupyter notebook browser (i.e. not through the journal's article preview) you will see that this feature is used in every code cell in our hermeneutics layer. Would something like this be possible?

**Comment by mariacheriksson** [comment]
> Question about the use of Ffmpeg
> 
> https://github.com/jdh-observer/BuWvtJFxh3wy

Hi Elisabeth! This link seems to be broken - maybe try adding it again?

**Comment by mariacheriksson** [comment]
> 

Hi Elisabeth! A gallery function seems like a nice idea for the journal but unfortunately, I think it won't help us in our article. What we are asking for is really a feature for making the outputs in a code cell scrollable (so you don't see all outputs at once and can navigate up and down). If you open our notebook in a regular Jupyter notebook browser (i.e. not through the journal's article preview) you will see that this feature is used in every code cell in our hermeneutics layer. Would something like this be possible?

**Comment by mariacheriksson** [comment]
Another question that we have concerns adding videos to the notebook. We'd like to add two clips to the notebook and these files are stored in the folder media/demo in our github repo. We tried using the code that can be found in the journal's author guidelines, but can't seem to get it to work. Any ideas why (see copy of code below). Also, the captions/metadata is rendered twice when we use the code below. Possible bug?


from IPython.display import Video, display

metadata={
    "jdh": {
        "module": "object",
        "object": {
            "type":"image",
            "source": [
                "The Eagle Has Landed: The Flight of Apollo 11 (1969)"
            ]
        }
    }
}


display(Video("media/demo/The Eagle Has Landed x265.mp4"), metadata=metadata)

**Comment by mariacheriksson** [comment]
Note that the metadata/captions are also rendered twice when we display ordinary photographies, using this code:

# question to person doing technical check: 
# the metadata/captions to images are rendered twice
# when looking at the notebook in "preview notebook"
# possible bug?

from IPython.display import Image, display

metadata={
    "jdh": {
        "module": "object",
        "object": {
            "type":"image",
            "source": ["Suggestion of where to set the threshold in the \
analysis of a distance metric histogram."
            ]
        }
    }
}

display(Image("./media/demo/distance_illustration.jpg"), metadata=metadata)

**Comment by mariacheriksson** [comment]
We also wanted to ask if the journal has a Pandas style, so that we can make our tables and data output look a bit nicer. If not, we think it might help if we could get access to the color code for the journal's hermeneutics layer.

**Comment by mariacheriksson** [comment]
> About the images, time to implement the gallery tag [C2DH/journal-of-digital-history#98](https://github.com/C2DH/journal-of-digital-history/issues/98) <img alt="Screenshot 2023-04-04 at 12 14 13" width="1105" src="https://user-images.githubusercontent.com/35602279/229761207-bd23658c-9f60-4e76-ac84-6def65cdf02c.png"> Need to speak with @danieleguido at the JDH's meeting

Hi Elisabeth. Adding a gallery feature sounds like a nice idea, but I'm afraid it probably won't help us in our article. What we are asking for is really a feature for making cell outputs scrollable (up and down). If you open our notebook in a regular browser (without looking at it through the journal's preview system) you will see that this is used in every code cell in our hermeneutics layer. Would something like this be possible?

**Comment by mariacheriksson** [comment]
One final question: we've followed the author guidelines but can't get the "narrative-step" and "hermeneutics-step" functions to work (nothing seems to happen when we tag the cells according to the quotations above). Is this function supposed to work, and if so do you have any idea what we are doing wrong?


<br class="Apple-interchange-newline">

**Comment by TomasSkotare** [comment]
> 



> Problem in preview: https://journalofdigitalhistory.org/en/notebook-viewer/JTJGcHJveHktZ2l0aHVidXNlcmNvbnRlbnQlMkZUb21hc1Nrb3RhcmUlMkZ0ZXN0X3ZyZF9yZXBvJTJGbWFpbiUyRlRyYWNraW5nJTI1MjAtJTI1MjBNYXJpYSUyNTIwZWRpdGlvbiUyNTIwdy4lMjUyMFRvbWFzJTI1MjBGaXhlcy1WMTAuaXB5bmI=
> 
> Raw url not available with Git LFS. To have the raw url:
> 
> `https://raw.githubusercontent.com/<username>/<repository>/<branch>/<path>/<filename>?token=<LFS_token> `
> 
> To get your Git LFS token, go to the "Settings" tab of your GitHub repository, and click on "Secrets" in the left sidebar. Then, create a new secret with the name "GIT_LFS_TOKEN" and set its value to your Git LFS token. After you have modified the URL with your Git LFS token, you should be able to access the raw file through Git LFS. @mariacheriksson is it work? Wait for author feedback, I will look at also to :https://github.com/git-lfs/git-lfs/blob/main/docs/api/batch.md

Hello!

I tried to get this to work but I couldn't pass the token step, as I was unsure where there secret should be saved, as well as the value of the secret. Is it the token to the repo? Because it's public, so that shouldn't strictly be necessary - but perhaps I misunderstand!

Regardless, my best effort to find a direct download link resulted in:
[https://media.githubusercontent.com/media/TomasSkotare/test_vrd_repo/main/Tracking%20-%20Maria%20edition%20w.%20Tomas%20Fixes-V10.ipynb](https://media.githubusercontent.com/media/TomasSkotare/test_vrd_repo/main/Tracking%20-%20Maria%20edition%20w.%20Tomas%20Fixes-V10.ipynb)

Which will result in a download, even using tools e.g. wget.

However, it doesn't work in your viewer, so I'm sure I'm missing something!

If you have any extra information I would be very thankful!

**Comment by mariacheriksson** [comment]
Hey @eliselavy! Aside from the unanswered questions above, I noticed that the following prompt doesn't work to make links open in a new window: [link](URL){:target="_blank"}. Any idea how this can be fixed?

**Comment by eliselavy** [comment]
@mariacheriksson 
My bad Maria, I looked at it a bit quickly. I thought you also used via the metadata to insert labels. See screenshot below 
<img width="965" alt="Screenshot 2023-04-11 at 13 02 54" src="https://user-images.githubusercontent.com/35602279/231142297-c4946c2a-0490-4215-9605-770404703a14.png">


but in fact it's a bad effect of the fact that the figures have not been tagged as a figure, if you add a tag to specify that it's a figure (for example below: figure-layer-*), the label is not duplicated.
<img width="1098" alt="Screenshot 2023-04-11 at 13 02 37" src="https://user-images.githubusercontent.com/35602279/231142356-78ea7eb8-d6a5-467f-90fc-82c86c9d4244.png">
<img width="991" alt="Screenshot 2023-04-11 at 13 02 30" src="https://user-images.githubusercontent.com/35602279/231142515-1da93257-d96d-4862-bb2e-f9b2ed763f76.png">


Thank you for your understanding.

**Comment by mariacheriksson** [comment]
> @mariacheriksson My bad Maria, I looked at it a bit quickly. I thought you also used via the metadata to insert labels. See screenshot below <img alt="Screenshot 2023-04-11 at 13 02 54" width="965" src="https://user-images.githubusercontent.com/35602279/231142297-c4946c2a-0490-4215-9605-770404703a14.png">
> 
> but in fact it's a bad effect of the fact that the figures have not been tagged as a figure, if you add a tag to specify that it's a figure (for example below: figure-layer-*), the label is not duplicated. <img alt="Screenshot 2023-04-11 at 13 02 37" width="1098" src="https://user-images.githubusercontent.com/35602279/231142356-78ea7eb8-d6a5-467f-90fc-82c86c9d4244.png"> <img alt="Screenshot 2023-04-11 at 13 02 30" width="991" src="https://user-images.githubusercontent.com/35602279/231142515-1da93257-d96d-4862-bb2e-f9b2ed763f76.png">
> 
> Thank you for your understanding.

Ah - fabulous! Thank you  @eliselavy. I had forgotten to add the proper tags :) now it works!

**Comment by mariacheriksson** [comment]
@eliselavy @TomasSkotare

So, just to recap, here are our remaining questions:

1. We are not sure if there's a better way of installing ffmpg than our current solution in the notebook. The link you added above (https://github.com/jdh-observer/BuWvtJFxh3wy) is unfortunately broken. Did you find another solution? Maybe try adding it again?

2. Does the journal have a Pandas style? We are asking to see if there's a way make our tables and data output look a bit nicer. If not, would it be possible to get the color code for the journal's hermeneutics layer?

3. As a solution to the poor way in which our data is shown in the hermeneutics layer, you suggested adding a gallery feature. This sounds like a nice idea, but I'm afraid it won't help us in our article. What we are asking for is really a feature for collapsing/shrinking cell outputs and making them scrollable (up and down). If you open our notebook in a regular browser (without looking at it through the journal's preview system) you will see that this is used in every code cell in our hermeneutics layer. Would something like this be possible?

4. Tomas had some questions regarding Git LFS, but you already announced you will get back to him regarding this!

5. Finally, I'm trying to get the feature for making links open in an external window work, but I'm not succeeding. For instance, I'm following the author guidelines and adding the following in a markdown cell: 

[RosaMannen](https://www.youtube.com/user/RosaMannen){:target="_blank"}

But when this is rendered in the journal's preview tool, a new tab/window does not open when I click on the link. Any idea what I'm doing wrong?

Thank you so much for your help!

**Comment by eliselavy** [comment]
Email made to the authors:
- problem of the number of images
![Screenshot 2023-04-13 at 15 37 33](https://user-images.githubusercontent.com/35602279/232450936-16127486-2647-41a4-bea9-22dbec5716ed.png)
You have 11 cells with show_limit=200.
Each of the cells mentioned above displays 200 pictures along with 200 tables. So for 11 cells, you will show 2200 images beside 2200 tables which is a large number for a notebook.
Also, there are eight other cells with show_limit=100 or 10 or 50.

**Comment by mariacheriksson** [comment]
Hi @eliselavy, (@TomasSkotare for info),

Regarding your comments above: that is right, sometimes we output 200 images, sometimss 100, sometimes 50 and it is absolutely correct that this adds up to a lot of pictures. We are working with audiovisual content as source materials and by nature, this involves dealing with lots of images/frames. This is also the reason why it would be fantastic if we could **collapse** the cell outputs into a scrollable cell (so that readers wouldn't have to scroll down excessive amounts of images when reading the hermeneutical layer of our article). Again, this feature is normally built into Jupyter notebooks, but it disappears in the journal's rendering of the text.

I'm afraid tagging the cell outputs as a figure won't help, since readers will still be forced to scroll through the same amount of information (+ it makes it very difficult to grasp which metadata belongs to which image sequence). You also mentioned using the toggle feature to partially hide the cell outputs, but we are unsure how this feature can be implemented and transported in the journal's rendering of the article. Perhaps you could clarify? I'm also not sure I understand how you mean that dividing the notebook into two or three could help in this case, but maybe you could explain a bit more? 

As you suggest, we could limit the number of images but this would greatly reduce and limit our possibilities to showcase our methods (which is a key feature of the special issue on Digital tools that the article would be part of). It would also involve rewriting a very substantial part of the article, and this is why we really want to double-check if it wouldn't be possible to add a feature for collapsing cell outputs. Once more, what we are asking for is exactly the same feature that is automatically shown when you look at our article in a Jupyter Notebook browser window (as opposed to the journal's article preview).

**Comment by mariacheriksson** [comment]
Hello again @eliselavy,

You wrote the following before: "about the size of the image don't worry now about it, we have a GitHub action we retag all the pictures by adding tag of width/height in order to avoid this blank marge ( i can share it with you for test) and this should be documented to the guidelines"

Would it be possible to have a look at the test? we are fixing up the final things with our pictures and it would be great to double-check how things will look in the final article!

Best,
Maria

**Comment by mariacheriksson** [comment]
Hi @eliselavy,

One final question: we are doing a final proof-reading of the references and can't get the zotero plugin to work as we would like to. For instance, references that have been deleted from the main text remain in the bibliography at the end of the article.  When references are updated in the linked zotero-account (for instance, adding a missing publication date) this is also not imported to the article. Furthermore, we were wondering how to add page numbers for citations in the correct way. Thanks for your help!

**Comment by eliselavy** [comment]
> Hi @eliselavy,
> 
> One final question: we are doing a final proof-reading of the references and can't get the zotero plugin to work as we would like to. For instance, references that have been deleted from the main text remain in the bibliography at the end of the article. When references are updated in the linked zotero-account (for instance, adding a missing publication date) this is also not imported to the article. Furthermore, we were wondering how to add page numbers for citations in the correct way. Thanks for your help!

Hi @mariacheriksson 

- For inserting page numbers for citations, here is the way:
Insert after the cite tag, insert pp. PAGE_NUMBER
<img width="879" alt="Screenshot 2023-04-27 at 15 46 29" src="https://user-images.githubusercontent.com/35602279/234882901-e97eddc0-3617-495f-a239-0e19c345f79c.png">
` of the definition of crowds in ancient societies: see some brief assessments in (<cite data-cite=\"2272257/C6JA85NG\"></cite> pp. 7-16, <cite data-cite=\"2272257/R4D2I72H\"></cite> pp. 17-18, or more recently <cite data-cite=\"2272257/JHK45JAI\"></cite>, and on the side of literary studies, the panoramas of <cite data-cite=\"2272257/83M575BB\"></cite> or <cite data-cite=\"2272257/9HJ9HQUA\"></cite>`

-  The cite2c plugin is not synchronised with zotero, it means in case of an update of the reference, you need to remove the reference from the metadata and reinsert it in order to have the new elements taken into account. Same things to do for deleted references in the text and still present to the bibliography.
The cite2c metadatas are at the level of the notebook, it means: 
<img width="250" alt="Screenshot 2023-04-27 at 15 55 22" src="https://user-images.githubusercontent.com/35602279/234884321-22e5e0ac-3938-43d5-9be3-041e44380638.png">
Delete the key you want to remove:
<img width="608" alt="Screenshot 2023-04-27 at 16 00 07" src="https://user-images.githubusercontent.com/35602279/234885494-53aaf530-156c-4e06-9c9f-6bc81fb60102.png">

**Comment by eliselavy** [comment]
> Hi @eliselavy, (@TomasSkotare for info),
> 
> Regarding your comments above: that is right, sometimes we output 200 images, sometimss 100, sometimes 50 and it is absolutely correct that this adds up to a lot of pictures. We are working with audiovisual content as source materials and by nature, this involves dealing with lots of images/frames. This is also the reason why it would be fantastic if we could **collapse** the cell outputs into a scrollable cell (so that readers wouldn't have to scroll down excessive amounts of images when reading the hermeneutical layer of our article). Again, this feature is normally built into Jupyter notebooks, but it disappears in the journal's rendering of the text.
> 
> I'm afraid tagging the cell outputs as a figure won't help, since readers will still be forced to scroll through the same amount of information (+ it makes it very difficult to grasp which metadata belongs to which image sequence). You also mentioned using the toggle feature to partially hide the cell outputs, but we are unsure how this feature can be implemented and transported in the journal's rendering of the article. Perhaps you could clarify? I'm also not sure I understand how you mean that dividing the notebook into two or three could help in this case, but maybe you could explain a bit more?
> 
> As you suggest, we could limit the number of images but this would greatly reduce and limit our possibilities to showcase our methods (which is a key feature of the special issue on Digital tools that the article would be part of). It would also involve rewriting a very substantial part of the article, and this is why we really want to double-check if it wouldn't be possible to add a feature for collapsing cell outputs. Once more, what we are asking for is exactly the same feature that is automatically shown when you look at our article in a Jupyter Notebook browser window (as opposed to the journal's article preview).

@mariacheriksson we go to have a meeting next week about this.

**Comment by mariacheriksson** [comment]
Fabulous! Thank you so much for your help @eliselavy!

**Comment by eliselavy** [comment]
> Hello again @eliselavy,
> 
> You wrote the following before: "about the size of the image don't worry now about it, we have a GitHub action we retag all the pictures by adding tag of width/height in order to avoid this blank marge ( i can share it with you for test) and this should be documented to the guidelines"
> 
> Would it be possible to have a look at the test? we are fixing up the final things with our pictures and it would be great to double-check how things will look in the final article!
> 
> Best, Maria

I add the GitHub action in the JDH template repository https://github.com/C2DH/template_repo_JDH/blob/main/.github/workflows/github-actions-publishing.yml, you can copy the code of github-actions-publishing.yml
And add this action to your repository:
<img width="984" alt="Screenshot 2023-04-27 at 16 09 05" src="https://user-images.githubusercontent.com/35602279/234888232-f106016e-b61f-4753-a488-2b7b031a2c7f.png">
You need to put the name of your notebook in parameter **notebook** in the file github-actions-publishing.yml
```
with:
          notebook: 'article.ipynb'
          output_notebook: 'skim-article.ipynb'
```
After that commit the file, and run the workflow:
<img width="383" alt="Screenshot 2023-04-27 at 16 16 02" src="https://user-images.githubusercontent.com/35602279/234890111-3c8ce282-b496-48fe-a44c-cae6c0908675.png">
A new file will be produced: skim-article.ipynb where all the figures will be tagged with the width and the height

**Comment by eliselavy** [comment]
Save output in the GitHub repository to give further access
"Give a taste of DH articles"

**Comment by eliselavy** [comment]
Still waiting for the installation of the package: `pip install video-reuse-detector`

```
iler.py", line 120, in _compile
      raise CompileError(msg)
  distutils.errors.CompileError: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  ERROR: Failed building wheel for grpcio
  Running setup.py clean for grpcio
Failed to build grpcio
Installing collected packages: keract, Wand, faiss-cpu, flatbuffers, cachetools, pyasn1, pyasn1-modules, rsa, google-auth, protobuf, grpcio, oauthlib, requests-oauthlib, google-auth-oauthlib, tensorboard-plugin-wit, absl-py, tensorboard-data-server, importlib-metadata, markdown, tensorboard, termcolor, keras-preprocessing, gast, libclang, tensorflow-estimator, opt-einsum, google-pasta, tensorflow-io-gcs-filesystem, astunparse, keras, tensorflow, tenacity, plotly, ffmpeg-python, video-reuse-detector
  Attempting uninstall: protobuf
    Found existing installation: protobuf 4.25.2
    Uninstalling protobuf-4.25.2:
      Successfully uninstalled protobuf-4.25.2
    Running setup.py install for grpcio ... |
```

**Comment by eliselavy** [comment]
Ok can install the package video-reuse-detector with `Python 3.7.10`

```
ffmpeg version 6.0 Copyright (c) 2000-2023 the FFmpeg developers
built with Apple clang version 14.0.0 (clang-1400.0.29.202)
```

Nbconvert:

```
~/.pyenv/versions/anaconda3-2020.02/lib/python3.7/site-packages/vrd/frame_extractor.py in _extract_png_from_video(self, video_path, frame_directory)
    180                 .run(capture_stdout=True, capture_stderr=True)
    181             )
--> 182         except ffmpeg.Error as error:
    183             # TODO: Use logger instead? Throw exception?
    184             print("stdout:", error.stdout.decode("utf8"))

AttributeError: module 'ffmpeg' has no attribute 'Error'
AttributeError: module 'ffmpeg' has no attribute 'Error'
```

**Comment by TomasSkotare** [comment]
@eliselavy That seems to be the case, which is interesting. I will supply this early version of the file, which should work; it simply deletes one sequence in each file, as a demonstration. 

This file should be placed in the root directory, the same as the `README.md` file is located in.

[demo_unwanted_frames.xlsx](https://github.com/C2DH/jdh-notebook/files/14458324/demo_unwanted_frames.xlsx)

**Comment by eliselavy** [comment]
Sent to peer-review
