### ISSUE TITLE
Integrate copy-editing Fifty Years of Technocracy. International Migration Management as an Evolving Discourse Coalition + Design review

### ISSUE THREAD

**Issue by jdh-observer** [C2DH/jdh-notebook#104]
https://github.com/jdh-observer/jdh002-VeaK58WBs82C

Integration copy editing + design review + produce social media cover
[50yearsofTechnocracy-AOD review v1.docx](https://github.com/C2DH/jdh-notebook/files/10896338/50yearsofTechnocracy-AOD.review.v1.docx)

**Comment by eliselavy** [comment]
Md file has been generated https://github.com/jdh-observer/jdh002-VeaK58WBs82C/blob/main/article-notebook.md , can be the moment to evaluate the solution https://github.com/C2DH/journal-of-digital-history-backend/issues/175

**Comment by biumiamy** [comment]
It works well, but I think for Andy it will be too difficult..
https://github.com/jdh-observer/jdh002-VeaK58WBs82C/pull/2

**Comment by biumiamy** [comment]
It seems like the author forgot to finish the sentence here:

![2023-03-07 16_16_49-Journal of Digital History](https://user-images.githubusercontent.com/47319502/223465399-7c88de7d-670b-4739-86b7-5f48426f5c44.png)

**Comment by biumiamy** [comment]
@inactinique how should we proceed with that question?

**Comment by eliselavy** [comment]
@biumiamy merge branch made / in order to consolidate the md file and ipynb the notebook need to be relaunch in the Jupyter server- DONE /  desanonymisation done

@inactinique copyright need to be requested

**Comment by eliselavy** [comment]
@inactinique @biumiamy 
Integration of the authors remarks
- license integrated in notebook CC-BY / original agreement saved in atlas
- remove incomplete sentence
- regenerate citation
- update institution to respect alphabetical order
- re-check execution in mybinder

TO BE PUBLISH:
@biumiamy 
- social media cover 
- check in the different browser if ok for all figures (horizontal scrollbar displayed for figure 8-9...) and javascript enabled figure-2

**Comment by biumiamy** [comment]
There's a dot at the end of the title. Do we want that?

![2023-03-09 14_12_00-Journal of Digital History](https://user-images.githubusercontent.com/47319502/224033541-616cfc4d-eaed-4885-bdfc-5088d3ddfb18.png)

**Comment by biumiamy** [comment]
I deleted the dot and added the social media cover. Now testing the figures in various browsers

**Comment by biumiamy** [comment]
I can only test Firefox and Chrome. Safari is not developed for Windows anymore I just learned xD

**Comment by biumiamy** [comment]
Well yes. As Elisabeth already said, they have scrollbars in Chrome and Firefox. But otherwise there's no issue. 

So, Design Review done.

**Comment by inactinique** [comment]
Scrollbars in safari too.
If design review is done, then let's publish, so that I can send the authors the URL for a last review and we'll communicate next week.
