### ISSUE TITLE
Technical review A Digital Toolbox for Studying the LGBTQ World, 1965-1990

### ISSUE THREAD

**Issue by eliselavy** [C2DH/jdh-notebook#105]
Technical review A Digital Toolbox for Studying the LGBTQ World, 1965-1990
https://github.com/jdh-observer/X3MGSKqAycaT

see email for question

**Comment by eliselavy** [comment]
Adaptation needs to be made on the frontend
https://github.com/C2DH/journal-of-digital-history/issues/533

**Comment by eliselavy** [comment]
- Anonymisation
- Need to tag the figure / table
- Add title in the metadata , look at here in the guidelines how to do it:
https://journalofdigitalhistory.org/en/guidelines?idx=251&layer=narrative&lh=1182&pidx=251&pl=narrative&y=551
At the level of the cell, 
![Screenshot 2023-03-22 at 15 51 03](https://user-images.githubusercontent.com/35602279/226943060-cd61ac72-4ff9-48c1-93b4-189f732a7204.png)
- The Output needs to be generated and saved
- Leaflet required version under R version 4.1.2
I install the 4.2.3pkg
In the R console

```
install.packages('IRkernel')  # Don’t forget step 2/3!
IRkernel::installspec()
```
If you use Docker and for mybinder **FROM rocker/binder:4.2.0** needs to be use
- all packages used  need to be listed in install.R and not requirements.txt (this is for Python user)
- for leaflet map to display it in the notebook:
![Screenshot 2023-03-22 at 15 55 16](https://user-images.githubusercontent.com/35602279/226944518-e5fb4642-380c-4d96-bd5e-81b13ab7e621.png)
Adaptation on your side in order to support it: see issue https://github.com/C2DH/journal-of-digital-history/issues/533

**Comment by regan008** [comment]
Hi @eliselavy! When you say "=> you can resynchronise from here: https://github.com/jdh-observer/X3MGSKqAycaT/blob/main/article.ipynb" do you mean I need to bring my version of the notebook up to date with the version linked here? I'm a bit unclear on what exactly I need to do.

I'm also a bit unclear on what you mean by "If you use Docker and for mybinder FROM rocker/binder:4.2.0 needs to be use" -- I do have docker installed. Where would I find rocker/binder:4.2.0 and how would I install that? I may be misunderstanding the direction here.

**Comment by eliselavy** [comment]
> Hi @eliselavy! When you say "=> you can resynchronise from here: https://github.com/jdh-observer/X3MGSKqAycaT/blob/main/article.ipynb" do you mean I need to bring my version of the notebook up to date with the version linked here? I'm a bit unclear on what exactly I need to do.
> 
> I'm also a bit unclear on what you mean by "If you use Docker and for mybinder FROM rocker/binder:4.2.0 needs to be use" -- I do have docker installed. Where would I find rocker/binder:4.2.0 and how would I install that? I may be misunderstanding the direction here.

In fact only tag for figures have been added and the output genererated, you can add the tag by yourself with the name you want as it specified in the documentation.

For mybinder i will do the technical check if you want - i see you specify a version to use for R that is not compatible with the leaflet library

**Comment by eliselavy** [comment]
> And for the leaflet map - I can't seem to get the map to display like you have it above. I've installed those R packages you mention but the code in the screenshot doesn't work for me. I get no output when I run that cell. Is the adaption that needs to happen on my end or yours? I'm a bit unsure about next steps here.

@regan008 
Our frontend (it means the JDH interface) needs to be adapted as i wrote you but at least the map needs to be generated in your notebook.
The map is not generated in your notebook, isn'it? Do you have an error? Check the version you use by executing the following code in a cell code: `R.version` and share it

**Comment by regan008** [comment]
@eliselavy Yeah for whatever reason, I'm having trouble getting that map to show up in my notebook. Most of the time I just get nothing in return. I'm running R version 4.0.4 (2021-02-15) in the docker setup recommended by the journal. Any ideas?

**Comment by eliselavy** [comment]
@regan008 
>You should at least have an error message: 

**If the package is not installed:**
```
Error in library(leaflet): there is no package called ‘leaflet’
Traceback:
1. library(leaflet)
```

**Check where the package is installed:**
`system.file(package='leaflet')`

You mentioned version R version 4.0.4 (2021-02-15) in the docker setup but the version in the file is 4.2.0, see documentation here: https://github.com/C2DH/journal-of-digital-history-jupyter-stack#for-rs-user
Maybe we can a quick talk via webex ?, please contact me by email, free tomorrow except 2pm-3pm Luxembourg time
