### ISSUE TITLE
Technical review Mapping radio: Variations on segmentation and analysis of Swedish broadcasting data

### ISSUE THREAD

**Issue by jdh-observer** [C2DH/jdh-notebook#107]
https://github.com/jdh-observer/6EWgjJtoiW6R

**Comment by jdh-observer** [comment]
- OMP: Info #270: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
- update requirements.txt
- update github url given in parameter plot_waveform_and_play_audio

**Comment by eliselavy** [comment]
- wrong tag used for figure
- unused tag needs to be removed
- email send to the author

**Comment by eliselavy** [comment]
Not cell centric - one plot per cell
```
pca_result, audio_file_info, subfolder_names = plot_from_csv(csv_file_url, title='PCA', selected_subfolders=selected_subfolders)
print_intra_cluster_distances(pca_result, audio_file_info, subfolder_names, 'PCA')

```
```
pca_result, audio_file_info, subfolder_names = plot_from_csv(csv_file_url, title='PCA', selected_subfolders=selected_subfolders)
umap_result, audio_file_info, subfolder_names = plot_from_csv_umap(csv_file_url, title='UMAP', selected_subfolders=selected_subfolders)

```

Extra tagging made

**Comment by eliselavy** [comment]
MyBinder: check ok 
https://hub.gke2.mybinder.org/user/jdh-observer-6ewgjjtoiw6r-85w0y7cd/notebooks/article.ipynb

**Comment by eliselavy** [comment]
@inactinique can be send to the review:
- https://journalofdigitalhistory.org/en/notebook-viewer/JTJGcHJveHktZ2l0aHVidXNlcmNvbnRlbnQlMkZqZGgtb2JzZXJ2ZXIlMkY2RVdnakp0b2lXNlIlMkZtYWluJTJGc2tpbS1hcnRpY2xlLmlweW5i?idx=49
- https://mybinder.org/v2/gh/jdh-observer/6EWgjJtoiW6R/main?filepath=article.ipynb
