### ISSUE TITLE
Technical review The Text Analysis Prototype for Galileo's Library and Letters Online: GaLiLeO

### ISSUE THREAD

**Issue by eliselavy** [C2DH/jdh-notebook#108]
Repository: https://github.com/jdh-observer/FYjDViXVXggz

**Comment by eliselavy** [comment]
Check html retrieve this: 
```
<br>_Galileo’s Correspondence_
- Hannah Marcus and Paula Findlen: metadata and tagging schema of letters
- Data curators: Hannah Marcus, Daniele Macuglia, Rachel Midura, Mackenzie Cooley, Paolo Savoia, Demetrius Loufas, Brian Brege, Padraic Rohan, Chris Bacich, Julia Roever, Charlotte Thun-Hohenstein
- Undergraduate assistants: Kyle Lee-Crossett, Max Morales
- Morgan MacLeod: Python tools for tag analysis

<br> _Galileo’s Library_
- Crystal Hall: GaLiLeO infrastructure & tool development, corpus integration, library and correspondence document gathering, text cleaning, analysis, documentation, coordination with Harvard IT support for the workshop in September 2018.
- Aaron Gilbreath, Academic Tecnology & Consulting, Bowdoin College: experimental shiny app design for visualizing descriptions of the corpus (no longer supported)
- Additional transcribers and text cleaners: Gabriella Papper ’18, Dean Zucconi ’19, Ingrid Horton (MAI Services)

<br> _Workshop Support_
- William Barthelemy, Academic Technology, Harvard University Institutional Technology
found in the cell: <div class="cite2c-biblio"></div>
```

problem to run the preflight action : https://github.com/jdh-observer/FYjDViXVXggz/actions/runs/6262624601/workflow

**Comment by biumiamy** [comment]
Just saw this when I did a table check of all notebooks (if the formatting is still correct after Daniele created the dialog CSS adaption)
- the <chr> at the top - what is the meaning?

![Image](https://github.com/C2DH/jdh-notebook/assets/47319502/4e51a83a-cef4-48a8-84eb-a69d48259fb9)

**Comment by eliselavy** [comment]
By running nbconvert - error:
https://app.reviewnb.com/jdh-observer/FYjDViXVXggz/pull/2/

<img width="1381" alt="Screenshot 2023-10-19 at 16 50 27" src="https://github.com/C2DH/jdh-notebook/assets/35602279/7a9e9159-340e-44c1-931a-a6b6f1eb6695">

<img width="1404" alt="Screenshot 2023-10-19 at 16 50 41" src="https://github.com/C2DH/jdh-notebook/assets/35602279/f41fa2d0-4fbc-41d6-9271-24afcca2a6de">

**Comment by eliselavy** [comment]
```
Error in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : polygon edge not found
Traceback:


plot without title
```

**Comment by eliselavy** [comment]
Debug in R - same problem
Control of the list: 
```
> length(type_attributes)
[1] 75798
```

Control of type_attributes[["ochiale"]]

**Comment by eliselavy** [comment]
By using this code no more error:
```
type_plot <- ggplot(df, aes(x = Year, fill = factor(GG))) +
  geom_bar(stat = "count") +
  labs(title = "Chronological Use of your_word", x = "Year", y = "Count") +
  xlab("Year") +  # Corrected line to set the x-axis title
  scale_fill_discrete(name = "Author", breaks = c("GG", "NotGG"), labels = c("Galileo", "Other Authors"))

```

to set the x-axis use this:
xlab("Year") 
in order to use:
theme(axis.title.x=element_text("Year"))

but not same plot
![Screenshot 2023-10-24 at 15 14 16](https://github.com/C2DH/jdh-notebook/assets/35602279/883c0e62-f2cc-494d-acc1-209d9a50fb70)

**Comment by eliselavy** [comment]
About myBinder ok loaded ROM rocker/binder:4
![Screenshot 2023-10-24 at 15 00 41](https://github.com/C2DH/jdh-notebook/assets/35602279/edd87f17-d68f-42f5-bdfc-d6dd2e37cb3a)

**Comment by eliselavy** [comment]
Check mybinder - loaded correctly image FROM rocker/binder:4
![Screenshot 2023-10-24 at 16 25 20](https://github.com/C2DH/jdh-notebook/assets/35602279/98e89065-2ffc-48fb-83cb-899bb3b2b113)
![Screenshot 2023-10-24 at 16 25 20](https://github.com/C2DH/jdh-notebook/assets/35602279/5d0f8167-d1a5-44e3-a869-e46708698bb2)

**Comment by eliselavy** [comment]
Sent to peer-review
