### ISSUE TITLE
Remerge last revision for A Digital Toolbox for Studying the LGBTQ World, 1965-1990

### ISSUE THREAD

**Issue by eliselavy** [C2DH/jdh-notebook#109]
https://github.com/jdh-observer/X3MGSKqAycaT

**Comment by eliselavy** [comment]
- CHECK RESSOURCES

 file demo_files/rstudio_leaflet-1.3.1/rstudio_leaflet.css is not called
 file demo_files/rstudio_leaflet-1.3.1/images/1px.png is not called
 file demo_files/leaflet-binding-2.1.2/leaflet.js is not called
 file demo_files/htmlwidgets-1.6.2/htmlwidgets.js is not called
 file demo_files/leafletfix-1.0.0/leafletfix.css is not called
 file demo_files/jquery-1.12.4/jquery.min.js is not called
 file demo_files/proj4-2.6.2/proj4.min.js is not called
 file demo_files/Proj4Leaflet-1.0.1/proj4leaflet.js is not called
 file demo_files/leaflet-1.3.1/leaflet.js is not called
 file demo_files/leaflet-1.3.1/leaflet.css is not called
 file demo_files/leaflet-1.3.1/images/layers.png is not called
 file demo_files/leaflet-1.3.1/images/marker-icon.png is not called
 file demo_files/leaflet-1.3.1/images/marker-icon-2x.png is not called
 file demo_files/leaflet-1.3.1/images/marker-shadow.png is not called
 file demo_files/leaflet-1.3.1/images/layers-2x.png is not called
 file media/typicallisting.png is not called
 file media/placeholder.png is not called

- Not anonymised
- Reference to the GitHub repository of the author

**Comment by eliselavy** [comment]
Problem dataframe empty
see: https://app.reviewnb.com/jdh-observer/X3MGSKqAycaT/pull/1/
<img width="1350" alt="Screenshot 2023-04-07 at 18 09 39" src="https://user-images.githubusercontent.com/35602279/230641268-343c7f07-3769-4c61-8087-c578badfc60c.png">

**Comment by regan008** [comment]
@eliselavy Ah, there was an issue with the RDS dataset. I've fixed it and pushed the revisions. Now the code should run as expected.

**Comment by regan008** [comment]
@eliselavy I think I fixed the data frame and pushed a revised version. Can you take another look?
