### ISSUE TITLE
Technical review Building an AI Research Assistant: Large Language Models as A Versatile Tool for Digital Historians

### ISSUE THREAD

**Issue by eliselavy** [C2DH/jdh-notebook#110]
Repo to create with pid JZx9gw7iwGxb. (here https://github.com/jdh-observer/JZx9gw7iwGxb)
Wait for last version

**Comment by Dr-Hutchinson** [comment]
Final version submitted for technical review.

**Comment by eliselavy** [comment]
- regenerate the requirements.txt file to list only the packages usefull
- update path to include media or script folder
- retag image + include label in metadata for image Accuracy of the GPT Series on A.P. History Questions in the MMLU Benchmarks
- Notebook needs to be trusted in order to display output 
- keep the output of the author as without OPEN_AI_API_KEY can not reproduce the analysis: article.ipynb
- generate output article-executed.ipynb following problem:
```
ModuleNotFoundError: No module named 'langchain.chat_models'
langchain==0.0.178
```
and 
`NameError: name 'SystemMessagePromptTemplate' is not defined`

- remove files not mentionned in the notebook
```
CHECK RESSOURCES
 file script/benchmarks_tests_euro.py is not called
 file script/more_index_summarized.csv is not called
 file script/benchmarks_tests_us.py is not called
 file script/benchmarks_tests_world.py is not called
 file script/high_school_us_history_test.csv is not called
 file script/high_school_european_history_test.csv is not called
 file script/high_school_world_history_test.csv is not called
 file media/more_history_of_richard_iii.pdf is not called
 file media/ocr_die_lotse-6-30-1945_1.pdf is not called
 file media/GPT-3 Dialogue with Martin Luther.txt.txt is not called
```

**Comment by eliselavy** [comment]
- correct one undefined reference
- add label to figure 2 / figure 3 / figure 5 correctly

**Comment by eliselavy** [comment]
Contact the author for a temporary API key - otherwise buy one

**Comment by eliselavy** [comment]
![Screenshot 2023-06-08 at 17 01 24](https://github.com/C2DH/jdh-notebook/assets/35602279/00aefb8b-d714-4a68-b1b1-66135e0bd574)

**Comment by eliselavy** [comment]
ModuleNotFoundError: No module named 'langchain.chat_models'

**Comment by Dr-Hutchinson** [comment]
There seems to be a version error causing this. For cell 24 change get rid of the install for 'openai[embeddings':

# Below are the modules and libraries needed for running the case studies below.
# Requires Python version 3.8

!pip install pandas
!pip install Pillow 
!pip install openai[embeddings] # eliminate this install
!pip install langchain
!pip install matplotlib seaborn

After that I was able to run the code without errors. 

Additionally, I can send a temporary API key if needed for accessing GPT-4.

**Comment by eliselavy** [comment]
@Dr-Hutchinson fixed problem langchain by using  specific version as initially provide in the requirements.txt
Add only necessary package see here https://github.com/jdh-observer/JZx9gw7iwGxb/blob/gpt-35-turbo/requirements.txt
Preference by running the install requirements.txt to be able to use **nbconvert** otherwise required a restart of the kernel

I run the analysis with gpt-3.5-turbo.
One error dataframe contains only one element:  
`Exception: ValueError: 1 is not in range`

![Screenshot 2023-06-14 at 10 59 05](https://github.com/C2DH/jdh-notebook/assets/35602279/1eb3b638-cd9c-42f3-91b5-74f9a31399ba)
Linked to the gpt-3.5-turbo model? Still in waiting list for gpt-4
Maybe you can provide me your key ? (email: elisabeth.guerard@uni.lu)

**Comment by eliselavy** [comment]
From here: 
https://blog.finxter.com/game-changing-updates-from-openai-a-new-era-in-function-calling/?tl_inbound=1&tl_target_all=1&tl_form_type=1&tl_period_type=3
<img width="802" alt="Screenshot 2023-06-15 at 09 06 15" src="https://github.com/C2DH/jdh-notebook/assets/35602279/e43a5db7-d2dc-40ba-afd5-86fd5a8eb118">

**Comment by eliselavy** [comment]
Output will be saved.

**Comment by eliselavy** [comment]
Generation with appropriate key: ok
Notebook needs to be trusted after running nbconvert to display correctly : <IPython.core.display.Markdown object>
Nbdiff between author execution (article) - nbconvert (article_executed) saved: diff_article_article_executed.html

**Comment by eliselavy** [comment]
sent to review @inactinique
