### ISSUE TITLE
Merge last revision on Contextualizing and unlocking political web defacements for research

### ISSUE THREAD

**Issue by eliselavy** [C2DH/jdh-notebook#111]
https://github.com/jdh-observer/hXsgcT9BZ5jP

**Comment by eliselavy** [comment]
@mkrzmr you mentionned following file: media/flowchart.drawio.png
<img width="764" alt="Screenshot 2023-04-12 at 18 20 20" src="https://user-images.githubusercontent.com/35602279/231520229-f18c89c2-52ff-4364-a53b-eb4a8aeb4879.png">


 but the ressource is missing can you upload it in our github repo?

**Comment by eliselavy** [comment]
Problem in myBinder limit memory
<img width="1397" alt="Screenshot 2023-04-12 at 18 50 31" src="https://user-images.githubusercontent.com/35602279/231
![Screenshot 2023-04-13 at 10 45 48](https://user-images.githubusercontent.com/35602279/231705642-13ed41a1-d18b-4587-a626-7e4288253ff4.png)
705438-cb13c351-1017-47c5-b781-311c0ea6cace.png">

**Comment by eliselavy** [comment]
No hermeneutics paragraph defined:
<img width="421" alt="Screenshot 2023-04-12 at 18 23 33" src="https://user-images.githubusercontent.com/35602279/231706762-8ae3a3df-0cd9-4bc1-9c9d-7442baf22598.png">

**Comment by eliselavy** [comment]
@mkrzmr see commit above- file has been renamed to flowchart.png, IPython display doesn't' like name title with .

**Comment by eliselavy** [comment]
https://journalofdigitalhistory.org/en/notebook-viewer/JTJGcHJveHktZ2l0aHVidXNlcmNvbnRlbnQlMkZqZGgtb2JzZXJ2ZXIlMkZoWHNnY1Q5Qlo1alAlMkZtYWluJTJGc2tpbS1hcnRpY2xlLmlweW5i

**Comment by eliselavy** [comment]
- Limit of 2GB ram mybinder
- Hermeneutics paragraph missing

**Comment by mkrzmr** [comment]
> No hermeneutics paragraph defined: <img alt="Screenshot 2023-04-12 at 18 23 33" width="421" src="https://user-images.githubusercontent.com/35602279/231706762-8ae3a3df-0cd9-4bc1-9c9d-7442baf22598.png"> @mkrzmr it will be good to add title for your hermeutics paragraph in order to be visible on the table of contents

I'm not sure I understand - can you show me an example?
