### ISSUE TITLE
 Dialects of Discord. Changing vocabularies in the Dutch Cruise Missile discussion

### ISSUE THREAD

**Issue by eliselavy** [C2DH/jdh-notebook#113]
Take the branch : edited
Look at reference / citation not rendered

GitHub repository: https://github.com/jdh-observer/jdh001-9HcfToh7EYm8
Preview: https://journalofdigitalhistory.org/en/notebook-viewer/JTJGcHJveHktZ2l0aHVidXNlcmNvbnRlbnQlMkZqZGgtb2JzZXJ2ZXIlMkZqZGgwMDEtOUhjZlRvaDdFWW04JTJGbWFpbiUyRnNraW0tYXJ0aWNsZS5pcHluYg==
Article: https://github.com/jdh-observer/jdh001-9HcfToh7EYm8/blob/main/skim-article.ipynb

**Comment by eliselavy** [comment]
@inactinique licence saved in atlas directory - don't know if article required copy-editing
@biumiamy please integrate social media in the repository https://github.com/jdh-observer/jdh001-9HcfToh7EYm8
design review to do
GitHub repository: https://github.com/jdh-observer/jdh001-9HcfToh7EYm8
Preview: https://journalofdigitalhistory.org/en/notebook-viewer/JTJGcHJveHktZ2l0aHVidXNlcmNvbnRlbnQlMkZqZGgtb2JzZXJ2ZXIlMkZqZGgwMDEtOUhjZlRvaDdFWW04JTJGbWFpbiUyRnNraW0tYXJ0aWNsZS5pcHluYg==
Article: https://github.com/jdh-observer/jdh001-9HcfToh7EYm8/blob/main/skim-article.ipynb
If change needs to be done in the notebook: https://github.com/jdh-observer/jdh001-9HcfToh7EYm8/blob/main/1_load_train_7075.ipynb and action needs to be re-run
https://github.com/jdh-observer/jdh001-9HcfToh7EYm8/actions/workflows/github-actions-publishing.yml

Take care to not alter metadata kernel spec - to submit to review to me if needed

![Screenshot 2023-05-17 at 12 56 51](https://github.com/C2DH/jdh-notebook/assets/35602279/78541470-9b44-4a7b-921e-feca969a8030)

**Comment by biumiamy** [comment]
social media cover integrated

**Comment by eliselavy** [comment]
Provide printed version to Andy in order to perform the copy-editing.
Student Céline will integrate the changes in Md and push it on Github

**Comment by eliselavy** [comment]
[article.pdf](https://github.com/C2DH/jdh-notebook/files/11725398/article.pdf)
will be sent to Andy

**Comment by eliselavy** [comment]
[Dialectics of Discord - article -AOD review v1.docx.zip](https://github.com/C2DH/jdh-notebook/files/11746623/Dialectics.of.Discord.-.article.-AOD.review.v1.docx.zip)
Comment of Andy need to be integrated in the markdown file here: https://github.com/jdh-observer/jdh001-9HcfToh7EYm8/blob/main/1_load_train_7075.md

**Comment by eliselavy** [comment]
@inactinique @biumiamy takes charge on it. Review design - publication scheduled before the board meeting 29/06

**Comment by biumiamy** [comment]
Is there a way to extend the size of the popover? It's strange having to scroll when it's so little text anyway

![2023-06-21 11_02_57-Journal of Digital History](https://github.com/C2DH/jdh-notebook/assets/47319502/dd505b03-5436-4368-b7fb-7e75716c102e)

**Comment by biumiamy** [comment]
@danieleguido 
The button to switch to the H-layer looks good when it's a few lines of text, but not when it's just one line

![2023-06-21 11_04_47-Journal of Digital History](https://github.com/C2DH/jdh-notebook/assets/47319502/d3494e1d-8458-4799-a306-56684771bd9f)

**Comment by inactinique** [comment]
> Is there a way to extend the size of the popover? It's strange having to scroll when it's so little text anyway
> 
> ![2023-06-21 11_02_57-Journal of Digital History](https://user-images.githubusercontent.com/47319502/247495748-dd505b03-5436-4368-b7fb-7e75716c102e.png)

And it should be jdh002 not jdh 003.

**Comment by eliselavy** [comment]
@inactinique jdh003 is in development as i created an Issue "Varia review" but in production would be jdh002
About the citation strange i don't have it, any idea @danieleguido 
![Screenshot 2023-06-22 at 09 47 47](https://github.com/C2DH/jdh-notebook/assets/35602279/33879622-1178-4c42-b104-bc168939de04)

**Comment by inactinique** [comment]
> @inactinique jdh003 is in development as i created an Issue "Varia review" but in production would be jdh002 About the citation strange i don't have it, any idea @danieleguido ![Screenshot 2023-06-22 at 09 47 47](https://user-images.githubusercontent.com/35602279/247861591-33879622-1178-4c42-b104-bc168939de04.png)

Thanks, I thought it was something like that. On my computer: the citation appears with no scrollbar with firefox, chrome and safari (macos)

**Comment by eliselavy** [comment]
- Fade out is made with a paragraph not a single line


- For the button with one line editorial problem for @danieleguido - please open a dedicated issue for this design issue if action is requested @biumiamy 
<img width="884" alt="Screenshot 2023-06-26 at 16 29 54" src="https://github.com/C2DH/jdh-notebook/assets/35602279/6c601873-cca9-468a-b6d5-6f6e930f8bcf">

**Comment by danieleguido** [comment]
ah ok, thanks for the explanation. Do we also need to fix the "Cite as" component?

**Comment by eliselavy** [comment]
Fixed 
<img width="952" alt="Screenshot 2023-06-26 at 18 09 50" src="https://github.com/C2DH/jdh-notebook/assets/35602279/3b9c26c3-1401-4f33-857d-7753dfbc7b5c">


Plot needs to be regenerated:
<img width="1088" alt="Screenshot 2023-06-26 at 18 10 29" src="https://github.com/C2DH/jdh-notebook/assets/35602279/db3f5bde-273f-4599-b3b5-07b1c34e93da">

**Comment by eliselavy** [comment]
In production https://journalofdigitalhistory.org/en/article/9HcfToh7EYm8

**Comment by biumiamy** [comment]
not yet published on DeGruyter
