### ISSUE TITLE
Support plotly - alternative google spreadsheet -technical review 

### ISSUE THREAD

**Issue by jdh-observer** [C2DH/jdh-notebook#114]
Figure-3, figure-4, and figure-5 are the plotly graphs that are not printing out. I have uploaded the resources as .csv files in the "script" folder. Unfortunately, I am not sure what the issue is exactly. If the problem is with my usage of plotly, should I consider using another library such as Matplotlib? Alternatively, if you could provide a brief explanation on how I can resolve this issue, I would greatly appreciate it.
Regarding the Google Spreadsheets, one of the documents is the "corpus" which is a large document. That's why I only included the first few lines and added the link to the full document in the caption. I attempted to download the Google Spreadsheet document as an .excel file, but adding it to GitHub proved to be challenging due to its size. Do you have any suggestions on how I can resolve this?

Repo is here: 
https://github.com/jdh-observer/aADj3Ljjqti2

**Comment by eliselavy** [comment]
Dear all,

 

Well, I uploaded the corpus under the name “Full Corpus.xlsx”. However, it doesn’t show the data on github when I click on it. It gives me the error “(Sorry about that, but we can’t show files that are this big right now.)” However, when I click on Raw Data, it downloads the excel file. This might be a possible way out, right?

 

About the files, I checked them again, some numbers were wrong in the csv file. Now they are all uploaded under “script”.

Figure 1 is in github under the name “Figure 2.csv”
Figure 3 is under the name “Figure 3.csv”
Figure 4 is under the name “Figure 4.csv”
Figure 5 is under the name “Figure 5.csv”

**Comment by eliselavy** [comment]
Problem plotly: https://github.com/C2DH/journal-of-digital-history/issues/541

**Comment by eliselavy** [comment]
![Screenshot 2023-05-26 at 12 41 37](https://github.com/C2DH/jdh-notebook/assets/35602279/136eef46-9347-401e-8539-5c972fda7b79)

**Comment by eliselavy** [comment]
![Screenshot 2023-05-26 at 13 59 09](https://github.com/C2DH/jdh-notebook/assets/35602279/9d7d65d0-03ef-40cf-9d0a-0ddfbcae2e3e)

**Comment by eliselavy** [comment]
Send to peer review
