### ISSUE TITLE
Not good link for the fingerprint video in the guidelines

### ISSUE THREAD

**Issue by eliselavy** [C2DH/jdh-notebook#120]
- In the general guidelines: https://journalofdigitalhistory.org/en/guidelines#figure-fingerprint-explanation-*
=>. figure-92
- In the the styling and tagging: http://10.240.4.179/en/guidelines/AuthorGuideline-styling#figure-fingerprint-explanation-*
<img width="965" alt="Screenshot 2023-06-30 at 10 07 20" src="https://github.com/C2DH/jdh-notebook/assets/35602279/fd917d03-9cd9-4d80-b365-4c2b51073adf">
=> figure-16

**Comment by biumiamy** [comment]
updated as soon as new guideline will be pushed
