### ISSUE TITLE
update guideline

### ISSUE THREAD

**Issue by biumiamy** [C2DH/jdh-notebook#121]
- many issues in terms of content mismatch
- check again all previous issues
- linked to this issue: https://github.com/C2DH/jdh-notebook/issues/120
- https://github.com/C2DH/jdh-notebook/issues/87

**Comment by biumiamy** [comment]
don't have steps anymore (and totally wrong figure captions)

![Image](https://github.com/C2DH/jdh-notebook/assets/47319502/9cf39c50-c273-4d1b-9ef1-4789791d1f03)


![Image](https://github.com/C2DH/jdh-notebook/assets/47319502/13dc9d63-2a0b-43a8-96ab-cbce4624c3d2)

**Comment by biumiamy** [comment]
think about moving some parts of the guideline to the H-layer?

**Comment by biumiamy** [comment]
For the [script result](https://github.com/C2DH/journal-of-digital-history-ipynb-preflight-action/blob/master/report.md), added a first demo gif to the guideline.

Need to add: how author can implement into their repo

See guides:
https://docs.github.com/en/github-ae@latest/actions/using-workflows/creating-starter-workflows-for-your-organization
https://docs.github.com/en/actions/quickstart

**Comment by biumiamy** [comment]
two ways to add the script:
1. use the [JDH template ](https://github.com/C2DH/template_repo_JDH/tree/main)that has the action already integrated
2. create a new action in an already existing repository (copy paste the content of the yml-file)

**Comment by biumiamy** [comment]
add to the guideline: dont use the button "Use this template" (=it will fork the template), but use "create a new repository"


![Image](https://github.com/C2DH/jdh-notebook/assets/47319502/6b59bb75-9324-4186-bcf9-d7523249e828)

**Comment by biumiamy** [comment]
add section about recognize missing tags

**Comment by danieleguido** [comment]
As the guideline becomes part of the next release, I suggest just to add a couple of paragraphs to the `introduction` notebook: 


We present a comprehensive overview of the submission workflow to guide authors seamlessly through the publication process:

1.  Setup the environment: Begin by installing Docker to establish a conducive writing environment. Check either the MacOS installation (add link) or the Window (add link)
2. Repository and Template: Create a Github repository and leverage the JDH template notebook as your foundation. Seamlessly integrate the citation plugin in Jupyter to ensure proper referencing, follow the Styling guideline (add link)

3.    Follow the Writing and Design Guidelines: Adhere to our structured guidelines encompassing writing principles and design aesthetics. These directives guarantee clarity and coherence while presenting your research.

4.    Ensuring Reproducibility: detail your methodology, code, and data sources. This pivotal step reinforces the credibility of your findings.

    Thorough Reviews: Your article will undergo a rigorous evaluation process, encompassing technical, peer and finally design reviews. These stages refine the content, enhance its technical robustness, and polish its visual presentation.

    Publication: Upon successful review completion, your article is poised for publication. Our meticulous process ensures that your valuable contribution seamlessly integrates into the journal's repository of knowledge.

**Comment by eliselavy** [comment]
@biumiamy need to deploy due to https://github.com/C2DH/journal-of-digital-history/issues/564#issuecomment-1689694734

**Comment by biumiamy** [comment]
[update](https://github.com/C2DH/jdh-notebook/commit/f2945b9c991123e1a0bb80dc3870e5859229e68d):
- added preflight section (but with hide-tag for the moment)
- updated the introduction text from [here](https://github.com/C2DH/jdh-notebook/issues/121#issuecomment-1689627164)
- uploaded updated submission workflow figure

**Comment by biumiamy** [comment]
new problem:
- docker interface was changed
- need to update figures
