### ISSUE TITLE
double figure captions on Guideline introduction page

### ISSUE THREAD

**Issue by biumiamy** [C2DH/jdh-notebook#123]
There's double caption bug

![Image](https://user-images.githubusercontent.com/47319502/253007097-d97c5e2a-b5c0-45c8-abdd-3692d991a8fa.png)

**Comment by biumiamy** [comment]
@danieleguido it's still there an now on production

**Comment by eliselavy** [comment]
fixed in [v4.2.](https://github.com/C2DH/journal-of-digital-history/releases/tag/v4.2.2)
