### ISSUE TITLE
Technical review Unlinked: Conflict Resolution and Structural Balance in the Early Modern Republic of Letters

### ISSUE THREAD

**Issue by eliselavy** [C2DH/jdh-notebook#130]
nKMX2DnFTBvx

https://github.com/jdh-observer/nKMX2DnFTBvx

Article sent for review 15 september

**Comment by inactinique** [comment]
Je prends le relais

**Comment by inactinique** [comment]
Added: GitHub Actions Ipynb for preflight that did not exist in this repo.

**Comment by inactinique** [comment]
launch of mybinder failed:

> Warning in install.packages("ggplot2", "tidyverse", "dplyr", "igraph", "threejs",  :
>   'lib = "tidyverse"' is not writable
> Error in install.packages("ggplot2", "tidyverse", "dplyr", "igraph", "threejs",  : 
>   unable to install packages
> Execution halted

**Comment by inactinique** [comment]
@eliselavy cannot do the reproducible code part for now.

**Comment by eliselavy** [comment]
@inactinique ok go to look at but wonder if :
install.packages function in R accepts only one package name at a time
it means https://github.com/jdh-observer/nKMX2DnFTBvx/blob/main/install.R not valid
(On package per line) https://github.com/jdh-observer/jdh001-9HcfToh7EYm8/blob/main/install.R

**Comment by inactinique** [comment]
@eliselavy yep, you're right. Modified it and mybinder is now working.

**Comment by eliselavy** [comment]
Here to look at https://observablehq.com/collection/@jacomyma/quest-for-connected-closeness

**Comment by jdh-observer** [comment]
from the author: 

R version 4.2.0 (2022-04-22)
nickname       Vigorous Calisthenics

**Comment by eliselavy** [comment]
Sent for review

**Comment by inactinique** [comment]
Article abandonned.
