### ISSUE TITLE
Technical review: Voyages in 3D: Creating a Multimodal Narrative of the Battle of Mount Street Bridge

### ISSUE THREAD

**Issue by jdh-observer** [C2DH/jdh-notebook#131]
@eliselavy

**Comment by eliselavy** [comment]
@inactinique no abstract submitted

**Comment by jdh-observer** [comment]
> @inactinique no abstract submitted

Yep, it is. Title: Voyages in 3D: Creating a Multimodal Narrative of the Battle of Mount Street Bridge

**Comment by jdh-observer** [comment]
https://github.com/jdh-observer/52s3BFHa5Miy

**Comment by eliselavy** [comment]
Sent to review

- cover image to request
- copyright
