### ISSUE TITLE
Technical review: 'The Secret History of the Mongols: A Digital History Approach'

### ISSUE THREAD

**Issue by inactinique** [C2DH/jdh-notebook#133]
'The Secret History of the Mongols: A Digital History Approach'.

https://github.com/jdh-observer/Gqh2Bf5W4TdK

**Comment by eliselavy** [comment]
@inactinique 
pid: Gqh2Bf5W4TdK
Email sent to author:
- anonymisation
- retag figure
- anonymisation

**Comment by eliselavy** [comment]
Anonymous version here: https://github.com/hBpzL3h8/The-Secret-History-of-the-Mongols.-A-Digital-History-Approach/blob/5abdb1f3c608c8f3e64f52f8b54b428c0e1b7e81/The%20Secret%20History%20of%20the%20Mongols.%20A%20Digital%20History%20Approach.ipynb

**Comment by inactinique** [comment]
Where are we on this article? @eliselavy ?

**Comment by eliselavy** [comment]
As mentionned in the issue : still open / still technical check 
The version corrected by the author has been resent the 22 November 2023
Need to create the GitHub repo / integrate material

**Comment by eliselavy** [comment]
Sent to peer- review
