### ISSUE TITLE
Technical review: Chinese Political and Cultural Elites: Twentieth Century Transformations

### ISSUE THREAD

**Issue by jdh-observer** [C2DH/jdh-notebook#135]
pid: JMU8e6tFQscz
https://github.com/jdh-observer/JMU8e6tFQscz

**Comment by jdh-observer** [comment]
@inactinique can find the GitHub repository 's url

**Comment by inactinique** [comment]
added to abstract on backend dev

**Comment by eliselavy** [comment]
Problem duplicate column can not use properly the tag data-table
![Screenshot 2023-12-19 at 17 17 16](https://github.com/C2DH/jdh-notebook/assets/35602279/c730bf3a-30f8-4007-8fb9-0832ce29df6e)
![Screenshot 2023-12-19 at 17 30 37](https://github.com/C2DH/jdh-notebook/assets/35602279/f8a5549d-b57c-4343-b7a3-243312a4bf99)

**Comment by eliselavy** [comment]
See here: http://10.240.4.179/en/notebook-viewer/JTJGcHJveHktZ2l0aHVidXNlcmNvbnRlbnQlMkZqZGgtb2JzZXJ2ZXIlMkZKTVU4ZTZ0RlFzY3olMkY1ZGY1MjkyOGE4ZjdhMDRmYTA0ZGY0OTk5YjM0Mjk5NTUyNDU2NzlkJTJGYW5vbnltX2NoaW5lc2Vfc3R1ZGVudHNfZXVyb3BlLmlweW5i?idx=63&layer=hermeneutics&lh=690&pidx=63&pl=narrative&y=85

**Comment by eliselavy** [comment]
Sent to review

**Comment by eliselavy** [comment]
```
By executing code: Error in file(con, "rb"): cannot open the connection
Traceback:

1. display_png(file = "./media/Fig.1.png")
2. display_img("image/png", TRUE, data, file, width, height)
3. display_raw(mime, binary, data, file, img_metadata(mime, width, 
 .     height))
4. prepare_content(isbinary, data, file)
5. read_all(file, isbinary)
6. read(size)
7. readBin(file, "raw", s)
8. file(con, "rb")
ERROR: Error in file(con, "rb"): cannot open the connection
```
