### ISSUE TITLE
Technical review after R1: Economic union in the debates on the creation of the euro: new evidence from the tapes of the Delors Committee meetings

### ISSUE THREAD

**Issue by inactinique** [C2DH/jdh-notebook#138]
pid: https://github.com/jdh-observer/4ZDXFXQwhoA8

(see author's email from 6.11.2023)

https://github.com/C2DH/jdh-notebook/issues/112

**Comment by eliselavy** [comment]
@inactinique revision merge - sent for peer-review again - pdf generated for copy-editing
https://app.reviewnb.com/jdh-observer/4ZDXFXQwhoA8/pull/1/

need to fix mybinder as now ressources is back- no more [MyBinder trouble: get a plain text "500 Internal Server Error"](https://github.com/C2DH/jdh-notebook/issues/117#top)
```
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python-dev-is-python3

E: Package 'python-dev' has no installation candidate
Removing intermediate container dfbef9c665cd
The command '/bin/sh -c mkdir -p /var/www     &
```

**Comment by eliselavy** [comment]
@inactinique review of the label of figure / table , bad effect of nbreview can not check metadata, after merge for R1, authors didn't resynchronize with jdh-observer.
Label restored now

Try to use the data-table-* tag, good use case with the 70 topics at the table-8 , see comment:
https://github.com/C2DH/journal-of-digital-history/issues/575#issuecomment-1888789384

**Comment by eliselavy** [comment]
From the metadata of the notebook retrieve version of python use by author: version": "3.10.6"
Version of spacy not good , apparently 3.5 used

Still problem with installation of  encountering an error related to the missing 'Eigen/Dense' file while trying to install  Tomotopy library.

    src/Labeling/../TopicModel/../Utils/serializer.hpp:10:10: fatal error: 'Eigen/Dense' file not found
      #include <Eigen/Dense>
               ^~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

**Comment by eliselavy** [comment]
Test binder by : https://mybinder.org/v2/gh/jdh-observer/4ZDXFXQwhoA8/convert-R1?filepath=delors_anonymised.ipynb

**Comment by inactinique** [comment]
Sent to copy-editing
