### ISSUE TITLE
Technical review after R1: Mapping radio: Variations on segmentation and analysisof Swedish broadcasting data: Decision Revise with Major Modifications

### ISSUE THREAD

**Issue by inactinique** [C2DH/jdh-notebook#139]
pid: https://github.com/jdh-observer/6EWgjJtoiW6R
issue: https://github.com/C2DH/jdh-notebook/issues/107

email from the author (15.11.2023):

"Thank you for you swift and helpful answer. I’ve attached the document and the notebook. The two new references are currently added manually to the script, it concerns (Drucker, 2020:13) in cell 48 and (Arnheim, 1936) in cell 3. References are:

Drucker, Johanna. 2020. Visualization and Interpretation: Humanistic Approaches to Display. Cambridge, MA: The MIT Press.
Arnheim, Rudolf. 1936. Radio. London: Faber & Faber Ltd

Let me know if it works this way – otherwise I’ll find another solution."

New notebook + answer to reviewer in attachment of email (and in attachment of this issue): 

- [JDH. Reviewer reply and changes.docx](https://github.com/C2DH/jdh-notebook/files/13378436/JDH.Reviewer.reply.and.changes.docx)
- [article (2).ipynb.zip](https://github.com/C2DH/jdh-notebook/files/13378440/article.2.ipynb.zip)

**Comment by eliselavy** [comment]
New csv - needs to run nbconvert

**Comment by inactinique** [comment]
Sent back to peer review
