### ISSUE TITLE
technical review 

### ISSUE THREAD

**Issue by jdh-observer** [C2DH/jdh-notebook#14]
perform technical review for https://github.com/jdh-observer/jdh001-WBqfZzfi7nHK

**Comment by jdh-observer** [comment]
- Missing output directory
- Addition requirements.txt
- Postbuild files

**Comment by eliselavy** [comment]
Problem time execution and size of the ouput generated files
<img width="595" alt="Screenshot 2021-06-14 at 18 04 23" src="https://user-images.githubusercontent.com/35602279/121923181-f5c41e00-cd3a-11eb-946d-67ac02ad8bd9.png">

**Comment by eliselavy** [comment]
need to update hermeneutics section link as an anchor

**Comment by eliselavy** [comment]
Locally time to read the EDCS dataset ==48s
With myBinder :
Problem by executing via myBinder

<img width="528" alt="Screenshot 2021-06-17 at 13 43 18" src="https://user-images.githubusercontent.com/35602279/122390267-17f3b100-cf72-11eb-8b50-3f76555995ff.png">

**Comment by eliselavy** [comment]
https://jakevdp.github.io/PythonDataScienceHandbook/01.07-timing-and-profiling.html

**Comment by eliselavy** [comment]
While running on mybinder, users are guaranteed at least 1GB of RAM, with a maximum of 2GB.
The cell to read the EDCS dataset:
peak memory: 3113.20 MiB, increment: 2940.26 MiB. by using %%memit
3113.20 MiB = 3,264217088 GB

**Comment by eliselavy** [comment]
<img width="714" alt="Screenshot 2021-06-17 at 14 45 30" src="https://user-images.githubusercontent.com/35602279/122398976-b08e2f00-cf7a-11eb-8978-901922745dde.png">
