### ISSUE TITLE
Design review - copy editing Economic union in the debates on the creation of the euro: new evidence from the tapes of the Delors Committee meetings

### ISSUE THREAD

**Issue by eliselavy** [C2DH/jdh-notebook#143]
Repository here: https://github.com/jdh-observer/4ZDXFXQwhoA8

@biumiamy 
- Integrate copy editing in the Md file with remarks made by Andy see zip 
[4ZDXFXQwhoA8-Andy-Od-reviewv1.docx.zip](https://github.com/C2DH/jdh-notebook/files/14037125/4ZDXFXQwhoA8-Andy-Od-reviewv1.docx.zip)

- Generate media for social media  - upload in the repo

@eliselavy 
- Desanonymisation

@inactinique - @eliselavy 
- Send copyright template in order to be signed: author has choose [CC-BY](https://creativecommons.org/licenses/by/4.0/)
- NO cover on this paper, maybe ask a picture to the author?

**Comment by eliselavy** [comment]
[4ZDXFXQwhoA8-Andy-Od-reviewv1.docx.zip](https://github.com/C2DH/jdh-notebook/files/14037350/4ZDXFXQwhoA8-Andy-Od-reviewv1.docx.zip)

**Comment by inactinique** [comment]
After email exchange with authors,cover image might be for instance:
https://www.ecb.europa.eu/ecb/access_to_documents/archives/delors/documents/shared/data/ecb.dr.delors880916_TranscriptionFirstMeeting.en.pdf?5d01ca39f8b12f73e7e476eb5986518a

**Comment by eliselavy** [comment]
Generate skim-article.ipynb  to have proper size of the image, notice problem on the size of the label


![Image](https://github.com/C2DH/jdh-notebook/assets/35602279/2bc731ab-ad88-45db-b141-7002aff50140)



> This action needs to be re-run each time there is an update to the article.ipynb
Table-8 is a data-table to be tested on Windows @biumiamy

**Comment by biumiamy** [comment]
I propose for the link in the figure to change it to this:
[Excerpt from the handwritten notes](https://www.ecb.europa.eu/ecb/access_to_documents/archives/detors/documents/shared/data/ecb.dr.delors881108_HandwrittenMinutes ThirdMeeting.en.pdf? a673cf3af794467b87b0a7ecaa293877) of Gunter Baer of the third meeting of the Delors Committee, 8 November 1988

**Comment by biumiamy** [comment]
When I wanted to finish the corrections on Monday, I couldnt clone the repo

<img width="551" alt="2024-02-01 08_18_14-GitHub Desktop" src="https://github.com/C2DH/jdh-notebook/assets/47319502/8607b971-2a23-49ca-8d0d-8ca6bf82eb3f">

So instead I just downloaded only the article.md file and did the corrections there

[article.md](https://github.com/C2DH/jdh-notebook/files/14121849/article.md)

Some questions remain open:
- Andy wrote that Economic should become a keyword
<img width="853" alt="2024-02-01 08_50_42-4ZDXFXQwhoA8-Andy-Od-reviewv1 docx  -  Compatibility Mode - Word" src="https://github.com/C2DH/jdh-notebook/assets/47319502/d74cb84d-ef21-467a-9db2-df44e727b4e2">

- and he was irritated by the use of the word "snake" - do you know if it's related to some visual aspect that looks like a snake?
<img width="815" alt="2024-02-01 08_51_41-4ZDXFXQwhoA8-Andy-Od-reviewv1 docx  -  Compatibility Mode - Word" src="https://github.com/C2DH/jdh-notebook/assets/47319502/694eb4b4-2e62-4943-a6c2-4f60d4328a8d">

**Comment by eliselavy** [comment]
@inactinique about the remarks of Andy see (previous comment made by @biumiamy ) don't know if reviewer made a comment 

By looking on internet: about the snake seems to come from this concept: snake in the tunnel

At the 1972 Paris Summit, the EU attempted to impart fresh momentum to monetary
integration by creating the ‘snake in the tunnel’: **a mechanism for the managed floating
of currencies (the ‘snake’)** within narrow margins of fluctuation against the dollar (the
‘tunnel’). Thrown off course by the oil crises, the weakness of the dollar and differences
in economic policy, the ‘snake’ lost most of its members in less than two years and
was finally reduced to a ‘mark area’ comprising Germany, the Benelux countries and
Denmark.

Do you need to to contact the author? 


About Economic is already in the keywords

![Image](https://github.com/C2DH/jdh-notebook/assets/35602279/bb8b49bb-2ea1-4ec4-b466-a5cb603e62cd)

Wait for feedback before integrating your markdown @biumiamy

**Comment by eliselavy** [comment]
@biumiamy reopen no social cover

**Comment by eliselavy** [comment]
Problem by pairing the notebook with the markdown see  here: 

![Image](https://github.com/C2DH/jdh-notebook/assets/35602279/78dc28a2-7271-482b-b195-abc90550850c)

**Comment by inactinique** [comment]
> @inactinique about the remarks of Andy see (previous comment made by @biumiamy ) don't know if reviewer made a comment
> 
> By looking on internet: about the snake seems to come from this concept: snake in the tunnel
> 
> At the 1972 Paris Summit, the EU attempted to impart fresh momentum to monetary integration by creating the ‘snake in the tunnel’: **a mechanism for the managed floating of currencies (the ‘snake’)** within narrow margins of fluctuation against the dollar (the ‘tunnel’). Thrown off course by the oil crises, the weakness of the dollar and differences in economic policy, the ‘snake’ lost most of its members in less than two years and was finally reduced to a ‘mark area’ comprising Germany, the Benelux countries and Denmark.
> 
> Do you need to to contact the author?
> 
> About Economic is already in the keywords
> 
> ![Image](https://private-user-images.githubusercontent.com/35602279/301547779-bb8b49bb-2ea1-4ec4-b466-a5cb603e62cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMjU4NjMsIm5iZiI6MTcwNzIyNTU2MywicGF0aCI6Ii8zNTYwMjI3OS8zMDE1NDc3NzktYmI4YjQ5YmItMmVhMS00ZWM0LWI0NjYtYTVjYjYwM2U2MmNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDEzMTkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4NmE2NDllNmE1YzRjNjdmMWNmMDhlNTU3NGI2MjNlOTE3Nzc1ODQ5OTNiNjQ2MWUwNWRlMWEyYTk2ZDAzYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TNO8tvjirkTaTrGknflYNSNaqtx5L4yONaW1G0bOu_U)

Basically, following the Werner Committee, the member of the EEC put in place a monetary system between their  currencies (including the currencies of the then --1972-- soon to be members but not yet members --Irland, UK and Denmark). That was the European Monetary Snake (not sure of the name in English, I need to check). It almost failed immmediatly, and was reduced to a couple of currencies around the DMark in a couple of years. That's what they are talking about.

Having said that, I think for readers that are not used to EEC monetary history might not understand, like Andy, what 'snake' refers to. So I suggest to write 'Snake' with a capitalized 'S' and to put into parentheses the date (1972).

**Comment by eliselavy** [comment]
correction integrated
https://journalofdigitalhistory.org/en/notebook-viewer/JTJGcHJveHktZ2l0aHVidXNlcmNvbnRlbnQlMkZqZGgtb2JzZXJ2ZXIlMkY0WkRYRlhRd2hvQTglMkZtYWluJTJGc2tpbS1hcnRpY2xlLmlweW5i

**Comment by inactinique** [comment]
Great. We also need to remove the "references" section at the end.
<img width="954" alt="Untitled3" src="https://github.com/C2DH/jdh-notebook/assets/1017260/7b4a478a-4fb9-485f-81fa-6e83dfab9322">

**Comment by eliselavy** [comment]
done - keep open @biumiamy social media cover

**Comment by eliselavy** [comment]
Mistake by referencing the issue in the commit (mentioned #144   / was #143)

Only difference

https://github.com/jdh-observer/4ZDXFXQwhoA8/pull/4#discussion_r1486396487

**Comment by eliselavy** [comment]
@inactinique version final to send to the author: 
https://journalofdigitalhistory.org/en/notebook-viewer/JTJGcHJveHktZ2l0aHVidXNlcmNvbnRlbnQlMkZqZGgtb2JzZXJ2ZXIlMkY0WkRYRlhRd2hvQTglMkZtYWluJTJGc2tpbS1hcnRpY2xlLmlweW5i

![Screenshot 2024-02-12 at 17 22 26](https://github.com/C2DH/jdh-notebook/assets/35602279/23eed7ea-745a-4e6e-9305-7ba45bfa6906)


Licence to be requested  /  tweet also

**Comment by eliselavy** [comment]
Curvenote binder instance no more available
From myBinder
Successfully pushed 2lmrrh8f.gra7.container-registry.ovh.net/mybinder-builds/r2d-g5b5b759jdh-2dobserver-2d4zdxfxqwhoa8-4eb3aa:17eb1a4b4544c26f73d59d4f5374028c59cbea49Exception ignored in: <function Application.__del__ at 0x7ff9fe281090>
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/traitlets/config/application.py", line 1065, in __del__
  File "/usr/lib/python3.10/site-packages/traitlets/config/application.py", line 1054, in close_handlers
  File "/usr/lib/python3.10/site-packages/traitlets/traitlets.py", line 687, in __get__
  File "/usr/lib/python3.10/site-packages/traitlets/traitlets.py", line 666, in get
TypeError: 'NoneType' object is not callable

**Comment by eliselavy** [comment]
@inactinique ready to publish
https://journalofdigitalhistory.org/en/notebook-viewer/JTJGcHJveHktZ2l0aHVidXNlcmNvbnRlbnQlMkZqZGgtb2JzZXJ2ZXIlMkY0WkRYRlhRd2hvQTglMkZtYWluJTJGc2tpbS1hcnRpY2xlLmlweW5i

**Comment by eliselavy** [comment]
@inactinique ready to publish ? Let's prepare the tweets ;-)
https://journalofdigitalhistory.org/en/notebook-viewer/JTJGcHJveHktZ2l0aHVidXNlcmNvbnRlbnQlMkZqZGgtb2JzZXJ2ZXIlMkY0WkRYRlhRd2hvQTglMkZtYWluJTJGc2tpbS1hcnRpY2xlLmlweW5i

**Comment by eliselavy** [comment]
Article published
