### ISSUE TITLE
Design review - Integrate copy editing Eminent Chinese of the Shenbao (1872-1891). A digital investigation of news reporting and newspaper-making in late imperial China

### ISSUE THREAD

**Issue by eliselavy** [C2DH/jdh-notebook#144]
Repo here:

https://github.com/jdh-observer/fwpktfFtn5jm

- Copy editing to be integrated: 

[fwpktfFtn5jm-2 AOD review.docx.zip](https://github.com/C2DH/jdh-notebook/files/14191450/fwpktfFtn5jm-2.AOD.review.docx.zip)

but as mentionned Andy @inactinique : There are corrections and questions.  We need to discuss this.

**Comment by eliselavy** [comment]
@biumiamy MD generated https://github.com/jdh-observer/fwpktfFtn5jm/blob/main/article.md

**Comment by eliselavy** [comment]
Commit related to issue https://github.com/C2DH/jdh-notebook/issues/145 / mistake made

**Comment by biumiamy** [comment]
@biumiamy wait for author to do change first, then do correction

**Comment by biumiamy** [comment]
Umm, is it the correct copyediting file? there's not a single correction in the docx..

**Comment by biumiamy** [comment]
Anyway I changed from American to British English:
https://github.com/jdh-observer/fwpktfFtn5jm/pull/4

**Comment by biumiamy** [comment]
editorial point: figure 1 is really uncomfortable to look at with the grey background.. why not just white?

![2024-09-13 10_50_43-Journal of Digital History](https://github.com/user-attachments/assets/226ea1da-8ab5-4414-bacb-47ccacb2af10)

**Comment by biumiamy** [comment]
And very good example here: figure 5 / 1h and figure 6 / 2h

![2024-09-13 10_55_14-Journal of Digital History](https://github.com/user-attachments/assets/74b99f72-d7c8-4b37-a31a-5eca531bfb56)

**Comment by biumiamy** [comment]
I deleted the figure part from all captions (see PR)

**Comment by eliselavy** [comment]
need to be done also for the label of the table / problem in Toc also

![Screenshot 2024-09-16 at 14 11 44](https://github.com/user-attachments/assets/33eedc1e-35d4-4fc9-b7a4-76c4f9ac0190)

**Comment by eliselavy** [comment]
need to fixed reference
<img width="1034" alt="Screenshot 2024-09-16 at 14 41 04" src="https://github.com/user-attachments/assets/9ece555b-f77b-4bdd-b4c1-39fdc1234d9d">

**Comment by eliselavy** [comment]
> I deleted the figure part from all captions (see PR)

but it exists some reference in the text to be fixed

**Comment by eliselavy** [comment]
to remove
![Screenshot 2024-09-16 at 15 04 55](https://github.com/user-attachments/assets/5823ac75-dc1c-4fa4-9565-7849325da5cf)

**Comment by eliselavy** [comment]
> fix reference / tag / wrong cell / undefined ORCID solution for this @danieleguido ? <img alt="Screenshot 2024-09-16 at 15 20 41" width="858" src="https://private-user-images.githubusercontent.com/35602279/367769522-a41aeae7-7698-4686-963e-726be6d95672.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxODg2NTksIm5iZiI6MTcyNzE4ODM1OSwicGF0aCI6Ii8zNTYwMjI3OS8zNjc3Njk1MjItYTQxYWVhZTctNzY5OC00Njg2LTk2M2UtNzI2YmU2ZDk1NjcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDE0MzIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0ZmZiZjkyNWQ4ZGYwNzNiOTg4MDQ4MDU1ZWMxZmQ1MTlmNjUzNTQyMGJlZGFkYWM3YmMwN2E3MmUxMzQzMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PH-mgBJGjYWiltWA0HBDRylmgzhWY9XscO0QU4R-tiA">

not many things you can do without breaking the link

**Comment by eliselavy** [comment]
To check where it comes from this 
<img width="1067" alt="Screenshot 2024-09-24 at 16 57 50" src="https://github.com/user-attachments/assets/56ec2e72-7278-4667-a7b3-15468b347aeb">

**Comment by eliselavy** [comment]
> fwpktfFtn5jm



> To check where it comes from this <img alt="Screenshot 2024-09-24 at 16 57 50" width="1067" src="https://private-user-images.githubusercontent.com/35602279/370341584-56ec2e72-7278-4667-a7b3-15468b347aeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzOTEyMTYsIm5iZiI6MTcyODM5MDkxNiwicGF0aCI6Ii8zNTYwMjI3OS8zNzAzNDE1ODQtNTZlYzJlNzItNzI3OC00NjY3LWE3YjMtMTU0NjhiMzQ3YWViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDEyMzUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmNDFjMGFhZDRkZGI5Yzk1Y2M3ZTdiMzkzNjViODZlZjk3NjIzOTdmZjc4ZjVkMjBjNGE1NjkyMWZmZDFhMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gHhOXCfVrT-ZvZfjNFhtYHZ5-UK_TcSu0B88zbPLLwI">

> like that in the paper of the author, see here https://github.com/ankeqiang/Eminent/blob/main/Eminent-Revised.ipynb
![Screenshot 2024-10-08 at 14 37 16](https://github.com/user-attachments/assets/56be9547-9804-4f21-b19d-21df16674310)


@inactinique can you ask to the author to review the article, from [here](https://journalofdigitalhistory.org/en/notebook-viewer/JTJGcHJveHktZ2l0aHVidXNlcmNvbnRlbnQlMkZqZGgtb2JzZXJ2ZXIlMkZmd3BrdGZGdG41am0lMkZtYWluJTJGc2tpbS1hcnRpY2xlLmlweW5i) 
- look at this mention to table 7
- provide maybe better image for the figure-1

**Comment by eliselavy** [comment]
Need to add table 7 -csv provided by author

**Comment by eliselavy** [comment]
@biumiamy socialmedia cover
@inactinique tweets and copyright - in prod can be published

**Comment by biumiamy** [comment]
social media cover added:
https://github.com/jdh-observer/fwpktfFtn5jm/blob/main/socialmediacover.png

**Comment by inactinique** [comment]
tweets and copyright asked

**Comment by eliselavy** [comment]
PUBLISHED

**Comment by biumiamy** [comment]
social media scheduled for today
