### ISSUE TITLE
Technical revision after R1 :merge “Public opinion should be suspended until further report”: A Data-Assisted Analysis of International Newspaper Coverage of the Explosion of the USS Maine (1898)

### ISSUE THREAD

**Issue by eliselavy** [C2DH/jdh-notebook#145]
Resynchronise here : https://github.com/jdh-observer/aADj3Ljjqti2

**Comment by eliselavy** [comment]
Problem again with the preview of the plot figures @danieleguido , I reopen https://github.com/C2DH/journal-of-digital-history/issues/541

Notebook in trusted mode
Output save



![Image](https://github.com/C2DH/jdh-notebook/assets/35602279/23a5a66b-f1fb-49c6-9233-08f1a368603a)

But by looking raw: https://raw.githubusercontent.com/jdh-observer/aADj3Ljjqti2/main/articleMaine.ipynb

No 

```
" require.undef("plotly");\n",
" define('plotly', function(require, exports, module) {\n",
" /**\n",
"* plotly.js v2.18.0\n",
```
 

![Image](https://github.com/C2DH/jdh-notebook/assets/35602279/3a160245-040a-4856-b967-e1745805b6ef)

**Comment by danieleguido** [comment]
Hi @eliselavy let me have a look at it

**Comment by eliselavy** [comment]
With latency loaded in the notebook 

```
   "data": {
      "text/html": [
       "        <script type=\"text/javascript\">\n",
       "        window.PlotlyConfig = {MathJaxConfig: 'local'};\n",
       "        if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: \"STIX-Web\"}});}\n",
       "        if (typeof require !== 'undefined') {\n",
       "        require.undef(\"plotly\");\n",
       "        define('plotly', function(require, exports, module) {\n",
       "            /**\n",
       "* plotly.js v2.12.1\n",
       "* Copyright 2012-2022, Plotly, Inc.\n",
       "* All rights reserved.\n",
       "* Licensed under the MIT license\n",
       "*/\n",
```

https://raw.githubusercontent.com/jdh-observer/aADj3Ljjqti2/main/articleMaine.ipynb

Now problem: figure-8

Doesn't response: https://hndm.iib.unam.mx/consulta/resultados/visualizar/558a33207d1ed64f16908db9?resultado=14&tipo=pagina&intPagina=1&palabras=Maine#bajar

https://journalofdigitalhistory.org/en/notebook-viewer/JTJGcHJveHktZ2l0aHVidXNlcmNvbnRlbnQlMkZqZGgtb2JzZXJ2ZXIlMkZhQURqM0xqanF0aTIlMkZtYWluJTJGYXJ0aWNsZU1haW5lLmlweW5i?idx=94

**Comment by eliselavy** [comment]
Sent to peer-review
