### ISSUE TITLE
Technical revision R1 Women in Early Modern Handwritten News: Random Walks and Semantic Wanderings in the Medici Archive

### ISSUE THREAD

**Issue by eliselavy** [C2DH/jdh-notebook#146]
https://github.com/jdh-observer/jnkqqTTKW8km

**Comment by eliselavy** [comment]
Code needs to be reexecuted after insertion of R1

**Comment by eliselavy** [comment]
@inactinique version to review for the figures tagging  here: https://github.com/jdh-observer/jnkqqTTKW8km/tree/review-R1

**Comment by eliselavy** [comment]
Need to refix the import, block of code has been removed where were the import

![Uploading Screenshot 2024-02-13 at 18.08.37.png…]()

**Comment by eliselavy** [comment]
Import needs to be reinserted as the following block have been removed

![Screenshot 2024-02-13 at 18 10 04](https://github.com/C2DH/jdh-notebook/assets/35602279/bb7ec4d3-1019-4f06-9eb3-21a97cab5f57)

**Comment by eliselavy** [comment]
Codev has been removed 

df = pd.read_csv('data/input/WomenMenAbsencePresence.csv')

![Screenshot 2024-02-13 at 18 18 21](https://github.com/C2DH/jdh-notebook/assets/35602279/40eac9fc-884d-419f-8eea-86d9ae544ffb)


No more dataframe to execute this:
![Screenshot 2024-02-13 at 18 22 33](https://github.com/C2DH/jdh-notebook/assets/35602279/56cf9b9c-8ce5-4c77-b9b4-ce458382efce)

**Comment by eliselavy** [comment]
@inactinique code exexuted / cover added 
need to fixed this problem of figure tag as A, B, C,D
<img width="1384" alt="Screenshot 2024-02-14 at 15 06 15" src="https://github.com/C2DH/jdh-notebook/assets/35602279/e0ce944e-cb69-4902-af76-fe5174b88907">


On branch main , to create branch
https://journalofdigitalhistory.org/en/notebook-viewer/JTJGcHJveHktZ2l0aHVidXNlcmNvbnRlbnQlMkZqZGgtb2JzZXJ2ZXIlMkZqbmtxcVRUS1c4a20lMkZtYWluJTJGcGFwZXIuaXB5bmI=?idx=86

**Comment by inactinique** [comment]
OK. Recreated the review-R1 branch. Will do the modifications now.

**Comment by inactinique** [comment]
So all tags + legends + references in the text are done. You can rerun and then merge @eliselavy

**Comment by eliselavy** [comment]
@inactinique Resend for peer-review
