### ISSUE TITLE
Technical review after R1:  Shaping the Transnational Public Sphere in Republican China: Discourses and Practices of the Rotary Club in the Shanghai Press (1919-1949)

### ISSUE THREAD

**Issue by inactinique** [C2DH/jdh-notebook#150]
PID 69Xry3ztPAk5

https://github.com/jdh-observer/69Xry3ztPAk5

See email for new repository.

**Comment by eliselavy** [comment]
[article_69Xry3ztPAk5.pdf](https://github.com/C2DH/jdh-notebook/files/14665328/article_69Xry3ztPAk5.pdf)

**Comment by eliselavy** [comment]
Recheck to be able to execute code in script and with install.R

**Comment by eliselavy** [comment]
histtext package https://bookdown.enpchina.eu/rpackage/HistTextRManual.html

<img width="888" alt="Screenshot 2024-03-20 at 13 42 53" src="https://github.com/C2DH/jdh-notebook/assets/35602279/581491d2-7aa8-43e2-a1e4-29ae82545f01">
