### ISSUE TITLE
Technical revision R2 Women in Early Modern Handwritten News: Random Walks and Semantic Wanderings in the Medici Archive

### ISSUE THREAD

**Issue by inactinique** [C2DH/jdh-notebook#152]
From the author:
> I have now revised the paper, pushed to the repo, and I am attaching my answers and my letter to the editor.

[LetterEditor.pdf](https://github.com/C2DH/jdh-notebook/files/14506266/LetterEditor.pdf)
[Answers.pdf](https://github.com/C2DH/jdh-notebook/files/14506267/Answers.pdf)

**Comment by eliselavy** [comment]
Send to review
