### ISSUE TITLE
Technical review after R2: Secret Societies and Revolving Doors: Using Mapping the Gay Guides as a Tool for Studying Queer Geographies

### ISSUE THREAD

**Issue by inactinique** [C2DH/jdh-notebook#153]
Author updated their repository. See backend for URL.

PID: X3MGSKqAycaT

**Comment by inactinique** [comment]
Please insert in their repository the answer to reviewers (attached).
[JDH-RevisionLetter-March2024.pdf](https://github.com/C2DH/jdh-notebook/files/14760536/JDH-RevisionLetter-March2024.pdf)

**Comment by eliselavy** [comment]
Sent for review

**Comment by eliselavy** [comment]
Undefined to correct 


![Image](https://github.com/C2DH/jdh-notebook/assets/35602279/314d2e64-a897-424f-8561-cc63d638f461)

Check redundant reference:


![Image](https://github.com/C2DH/jdh-notebook/assets/35602279/cd0050da-60e9-4637-82bf-a8b5d2df388d)

**Comment by eliselavy** [comment]
Fixed.
