### ISSUE TITLE
Technical review after R1: Simulating and visualising data in environmental history: Airborne dust concentration from the Belval plant in Luxembourg (1911-1997)

### ISSUE THREAD

**Issue by inactinique** [C2DH/jdh-notebook#154]
PID: ZDFmmD3xv4S7

We can add to the scholarone thing the version with/without track changes in word format (without code) (attached).

Be carefull, in the author(s)'s repository, the letter to answer the reviewers is in two formats: one with anonymisation, one not anonymized.

[Dust pollution paper_final version_ anonymized.docx](https://github.com/C2DH/jdh-notebook/files/14760614/Dust.pollution.paper_final.version_.anonymized.docx)
[Dust pollution paper_tracked changes_ anonymized.docx](https://github.com/C2DH/jdh-notebook/files/14760615/Dust.pollution.paper_tracked.changes_.anonymized.docx)

**Comment by eliselavy** [comment]
> Review paper not anonymised
Confusing three .ipynb

**Comment by eliselavy** [comment]
Author has changed the heading level again
<img width="313" alt="Screenshot 2024-04-05 at 16 42 00" src="https://github.com/C2DH/jdh-notebook/assets/35602279/82f6725a-13c9-4191-ae4b-d9f36fa8042d">

**Comment by eliselavy** [comment]
Problem my binder:
```
Waiting for build to start...
Picked Git content provider.
Cloning into '/tmp/repo2docker549ir9md'...
Updating files: 100% (1074/1074), done.
HEAD is now at 6b66ed4 Apply automatic changes
Building conda environment for python=3.7
Using PythonBuildPack builder
```

**Comment by eliselavy** [comment]
Problem no more figure 7: image_paths = sorted(glob("./media/figure7*_72.png"))

**Comment by eliselavy** [comment]
Problem mybinder due to the size of the script folder > 2GB
Message posted on the forum for having an explicit message: `https://discourse.jupyter.org/t/lauching-github-repo-into-binder-fails-due-to-script-folder-2gb-message-could-be-more-explicit/25062`

**Comment by eliselavy** [comment]
Sent for review
