### ISSUE TITLE
Technical review after R1 Super-Vision: Tracing Back EPFL History Through its Collection of 8,000 Doctoral Theses

### ISSUE THREAD

**Issue by inactinique** [C2DH/jdh-notebook#155]
Author updated their repository.
PID: Yn8z7XNPKzy4

Answer to reviewers:

I am deeply grateful for your insightful comments and constructive critiques on my manuscript. I have meticulously addressed each point raised to enhance the clarity, depth, and overall quality of the work.

Reviewer 1:

I have detailed the rationale behind the choice of lexical similarity for mapping, explaining its relevance and effectiveness in capturing the nuances of academic supervision within the EPFL community.
The data analysis section has been expanded to provide a more comprehensive view of the methodologies applied, and the insights derived from our investigation.
Regarding multilingualism, because of time constraints, a full multilingual analysis could not be undertaken. However, I've noted in caption 4 that the peninsula at the bottom represents French theses without English abstracts, to clarify the dataset’s linguistic composition.
The emphasis on “growth” has been significantly reduced, acknowledging your critical insight. This adjustment has helped refocus the narrative on the project’s core objectives and contributions.
Reviewer 2:

I have streamlined the introduction for a clearer contextualization of the study’s goals and motivations, as per your suggestion.
The explanation surrounding the mapping of the doctoral theses has been elaborated to clarify the decision-making process and the project’s overarching aims.
Lastly, the manuscript has undergone thorough revision for language and clarity, incorporating your feedback on specific terms and errors to ensure a more polished and reader-friendly presentation.
Your feedback has been invaluable in refining this work, and I hope these revisions address your concerns satisfactorily. I am eager to hear your thoughts on the updated manuscript.

**Comment by eliselavy** [comment]
No hermeneutics

![Image](https://github.com/C2DH/jdh-notebook/assets/35602279/4c3c9a9c-8123-4d4f-843b-f44d44bcdaa6)

Review letter attached to repo: https://github.com/jdh-observer/Yn8z7XNPKzy4/blob/main/JDH-review-letter.pdf

Send for review
