### ISSUE TITLE
Technical review after R2: Mapping radio: Variations on segmentation and analysisof Swedish broadcasting data: Decision Revise with Major Modifications

### ISSUE THREAD

**Issue by inactinique** [C2DH/jdh-notebook#156]
PID: 6EWgjJtoiW6R

https://github.com/jdh-observer/6EWgjJtoiW6R

Author updated their repository

- see abstract in backend for repository URL
- be careful, title has changed: "Experiments on the threshold between signals and narratives: Two methods of audio analysis and their implications for historiography." in backend.

**Comment by eliselavy** [comment]
<img width="1188" alt="Screenshot 2024-04-03 at 15 54 01" src="https://github.com/C2DH/jdh-notebook/assets/35602279/773fec9e-bd38-45f3-9d59-3154d8df1d35">
problem table of contents

**Comment by eliselavy** [comment]
Problem mybinder: ImportError: Numba needs NumPy 1.22 or greater. Got NumPy 1.21.

**Comment by eliselavy** [comment]
Conflit -> 1059     dtype=np.complex,
   1060 ):
   1061     """Generate the frequency domain constant-Q filter basis."""
   1063     basis, lengths = filters.constant_q(
   1064         sr,
   1065         fmin=fmin,
   (...)
   1072         gamma=gamma,
   1073     )

File ~/.pyenv/versions/anaconda3-2020.02/envs/jdh-action/lib/python3.10/site-packages/numpy/__init__.py:324, in __getattr__(attr)
    319     warnings.warn(
    320         f"In the future `np.{attr}` will be defined as the "
    321         "corresponding NumPy scalar.", FutureWarning, stacklevel=2)
    323 if attr in __former_attrs__:
--> 324     raise AttributeError(__former_attrs__[attr])
    326 if attr == 'testing':
    327     import numpy.testing as testing

```
AttributeError: module 'numpy' has no attribute 'complex'.
`np.complex` was a deprecated alias for the builtin `complex`. To avoid this error in existing code, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
```

**Comment by eliselavy** [comment]
difference between csv file 
but author update file  Mar 29, 2023
and us synchronize in December 2023 : https://github.com/jdh-observer/6EWgjJtoiW6R/commit/4d873bb41282825edd1341675909886f6d4002ee

**Comment by inactinique** [comment]
Je regarde, mais je crois que c’est normal. J’essaye de voir ça demain.

From: eliselavy ***@***.***>
Date: Wednesday, 3 April 2024 at 18:58
To: C2DH/jdh-notebook ***@***.***>
Cc: Frédéric CLAVERT ***@***.***>, Author ***@***.***>
Subject: Re: [C2DH/jdh-notebook] Technical review after R2: Mapping radio: Variations on segmentation and analysisof Swedish broadcasting data: Decision Revise with Major Modifications (Issue #156)

difference between csv file
but author update file Mar 29, 2023
and us synchronize in December 2023 : ***@***.***<https://github.com/jdh-observer/6EWgjJtoiW6R/commit/4d873bb41282825edd1341675909886f6d4002ee>

**Comment by eliselavy** [comment]
> We have the good version of the csv file (https://github.com/jdh-observer/6EWgjJtoiW6R/blob/main/script/audio_featuresmean.csv) - author repo not updated 
> Execution myBinder OK
> Sent for review
