### ISSUE TITLE
Technical review + design review before publication: " "Public opinion should be suspended until further report": A Data-Assisted Analysis of International Newspaper Coverage of the Explosion of the USS <i>Maine</i> (1898)"

### ISSUE THREAD

**Issue by inactinique** [C2DH/jdh-notebook#158]
PID = aADj3Ljjqti2

https://github.com/jdh-observer/aADj3Ljjqti2

**Comment by eliselavy** [comment]
https://github.com/jdh-observer/aADj3Ljjqti2/pull/3#issuecomment-2124505480

**Comment by eliselavy** [comment]
Should be the moment to promote archive url, problem can not find it 

https://web.archive.org/web/20240000000000*/https://hndm.iib.unam.mx/consulta/publicacion/visualizar/558a33207d1ed64f16908db9/

Some Mexican Herald avaialble 
https://web.archive.org/web/20240324142553/https://hndm.iib.unam.mx/consulta/publicacion/visualizar/558075be7d1e63c9fea1a34d

but not for the year requested: 17 February 1898

**Comment by eliselavy** [comment]
Go to send to copy-editing
Need to fix problme conversion ipynb => tex= > word

doesn't support plotly output
```

    \begin{Verbatim}[commandchars=\\\{\}]
<pandas.io.formats.style.Styler at 0x7fa148f8f350>
    \end{Verbatim}
```

**Comment by eliselavy** [comment]
Send to copy-editing

**Comment by eliselavy** [comment]
> Should be the moment to promote archive url, problem can not find it
> 
> https://web.archive.org/web/20240000000000*/https://hndm.iib.unam.mx/consulta/publicacion/visualizar/558a33207d1ed64f16908db9/
> 
> Some Mexican Herald avaialble https://web.archive.org/web/20240324142553/https://hndm.iib.unam.mx/consulta/publicacion/visualizar/558075be7d1e63c9fea1a34d
> 
> but not for the year requested: 17 February 1898

available:
figure 8 available
![Image](https://github.com/C2DH/jdh-notebook/assets/35602279/156301b9-56cb-4eb4-997e-3660e9b08ef3)

**Comment by biumiamy** [comment]
"(as can be seen in table 2-8)" 
Does the author mean from table 2 to 8? 
![2024-06-12 14_39_40-Journal of Digital History](https://github.com/C2DH/jdh-notebook/assets/47319502/bd5b5af3-2b45-4c8b-a257-f9425fb8a809)

because then he tags this as an anchor.. but this table doesnt exist.
![2024-06-12 14_41_24-articleMaine md — C__Users_mirjam pfeiffer_Documents_GitHub_journal-of-digital-h](https://github.com/C2DH/jdh-notebook/assets/47319502/30095ede-1ea2-4479-bc0f-9383d24eed1a)

**Comment by biumiamy** [comment]
- added the anchor tag in the tables and figures to connect to the anchor in the text:
https://github.com/jdh-observer/aADj3Ljjqti2/compare/update-anchors?expand=1

**Comment by eliselavy** [comment]
@biumiamy merge

**Comment by inactinique** [comment]
AUthors send an email stating that the latest version was there: [https://github.com/mpriewe/repo_article_maine](https://github.com/mpriewe/repo_article_maine)

**Comment by eliselavy** [comment]
> https://github.com/jdh-observer/aADj3Ljjqti2

ok copyright added

@inactinique tweet + signed copyright to collect
@biumiamy socialmedia cover

**Comment by biumiamy** [comment]
added social media cover: https://github.com/jdh-observer/aADj3Ljjqti2/blob/main/socialmediacover.png

**Comment by biumiamy** [comment]
I just saw this: need to delete "keyword" on the first tag

![Image](https://github.com/C2DH/jdh-notebook/assets/47319502/f84dde17-8521-425b-b282-a47bff754f03)

**Comment by inactinique** [comment]
added the cover image.

**Comment by eliselavy** [comment]
> added the cover image.
lost javascript 
![Screenshot 2024-06-20 at 16 23 40](https://github.com/C2DH/jdh-notebook/assets/35602279/a8aa47bc-99fc-4d8d-ac39-bd019f95c446)
![Screenshot 2024-06-20 at 16 24 06](https://github.com/C2DH/jdh-notebook/assets/35602279/01ebe028-7d77-45d0-a584-d1c693bf0451)



fixed now

better to do a pull request and asking review , when we are on this stage , as everything has been controlled
problem javascript , notebook needs to be trusted  and consolidation with the md

report didn't help has no detection....

![Screenshot 2024-06-20 at 16 24 50](https://github.com/C2DH/jdh-notebook/assets/35602279/58d9aecd-9582-4553-bf90-a64a0f0db34d)

**Comment by eliselavy** [comment]
@inactinique part of varia bis
just tweets are missing

**Comment by eliselavy** [comment]
need to adjust cover
![Screenshot 2024-06-20 at 16 30 51](https://github.com/C2DH/jdh-notebook/assets/35602279/ebc55240-58e9-4e89-9552-f5883769dd7c)

**Comment by eliselavy** [comment]
ok skim-article used`[ here](https://journalofdigitalhistory.org/en/notebook-viewer/JTJGcHJveHktZ2l0aHVidXNlcmNvbnRlbnQlMkZqZGgtb2JzZXJ2ZXIlMkZhQURqM0xqanF0aTIlMkZtYWluJTJGYXJ0aWNsZU1haW5lLmlweW5i)`

**Comment by eliselavy** [comment]
1) After seeing how our cover image looks in the article, we have decided to change it, if possible. I have copied the new image, which is much more fitting than the current one, below as well. Since my assistant doesn’t have access to your repository, would it be possible for you to change the cover image? Or should we do that in „our“ version and you’ll synchronize them again?

2) I have also noticed that the affiliation of my co-author Adán Lerma-Mayer has not been updated to "Universidad Anáhuac“ yet. We had made that change on June 11 in our version. Could you please check that this will be displayed correctly in the final version or advise us in which file to make that change?

-----------

- affiliation updated
- cover image changed
- citation generated
<img width="857" alt="Screenshot 2024-07-03 at 15 41 32" src="https://github.com/C2DH/jdh-notebook/assets/35602279/41483ba6-6147-45b3-ad99-93c18ba88e18">

to be put in production , needs to have a description for Varia @inactinique , see here https://github.com/C2DH/journal-of-digital-history-pm/issues/36#issuecomment-2205605820

**Comment by eliselavy** [comment]
@inactinique in prod - tag new added - just need to put publish status if you want to send for validation to the author

**Comment by inactinique** [comment]
It does not have the 'publish' status, but is seeable there: https://journalofdigitalhistory.org/en/article/aADj3Ljjqti2
Even if not connected. Can I send that to authors?
Best,
Frédéric

**Comment by eliselavy** [comment]
> It does not have the 'publish' status, but is seeable there: https://journalofdigitalhistory.org/en/article/aADj3Ljjqti2 Even if not connected. Can I send that to authors? Best, Frédéric

because you have the direct url
otherwise not visible
<img width="1426" alt="Screenshot 2024-07-15 at 13 14 39" src="https://github.com/user-attachments/assets/5b0259e8-e540-4474-ae85-ddab71b8f5f6">

you can send them the url like that or set status publish in the admin or i do it if you validate

**Comment by inactinique** [comment]
Yes of course, but I can then send the direct URL to authors and we don't need to publish it yet (we can wait that the three first articles of the varia to publish them at the same time, or the to first).

**Comment by inactinique** [comment]
And the tweets, once it's published:

"Delving into the archives: Our digital humanities project analyzes the initial global newspaper reactions to the USS Maine explosion in 1898. Discover how media shaped the prelude to the Spanish-American War. #DigitalHumanities #HistoricalMedia"
"Join us in exploring how digital tools enhance our understanding of historical media biases. Our latest study on the USS Maine explosion uses quantitative analysis to trace certain discursive constructions of the event across countries. #DigitalHumanities #MediaStudies"
"How did newspapers from seven different countries report the USS Maine explosion in 1898? Our digital humanities research employs statistical and close reading methods to uncover biases in historical journalism. #DigitalHumanities #TransnationalJournalism"
"Our digital humanities research provides a new perspective on the USS Maine explosion through a data-assisted analysis of international newspaper coverage. See how different narratives influenced the lead-up to the Spanish-American War. #DigitalHumanities #History"
"Unpacking the role of media in shaping public opinion during historical events: Our study on the USS Maine explosion uses digital archives to analyze coverage in seven countries. Insights into media influence and bias. #DigitalHumanities #MediaHistory"

**Comment by eliselavy** [comment]
> And the tweets, once it's published:
> 
> "Delving into the archives: Our digital humanities project analyzes the initial global newspaper reactions to the USS Maine explosion in 1898. Discover how media shaped the prelude to the Spanish-American War. #DigitalHumanities #HistoricalMedia" "Join us in exploring how digital tools enhance our understanding of historical media biases. Our latest study on the USS Maine explosion uses quantitative analysis to trace certain discursive constructions of the event across countries. #DigitalHumanities #MediaStudies" "How did newspapers from seven different countries report the USS Maine explosion in 1898? Our digital humanities research employs statistical and close reading methods to uncover biases in historical journalism. #DigitalHumanities #TransnationalJournalism" "Our digital humanities research provides a new perspective on the USS Maine explosion through a data-assisted analysis of international newspaper coverage. See how different narratives influenced the lead-up to the Spanish-American War. #DigitalHumanities #History" "Unpacking the role of media in shaping public opinion during historical events: Our study on the USS Maine explosion uses digital archives to analyze coverage in seven countries. Insights into media influence and bias. #DigitalHumanities #MediaHistory"

perfect  - there were already attached https://github.com/jdh-observer/aADj3Ljjqti2/blob/main/tweets.md

**Comment by eliselavy** [comment]
Integration last changes

**Comment by eliselavy** [comment]
READY TO PUBLISH

**Comment by eliselavy** [comment]
PUBLISHED
@biumiamy social media to launch

**Comment by eliselavy** [comment]
> PUBLISHED @biumiamy social media to launch

made
