### ISSUE TITLE
Technical review: "History of Fandoms at Risk: Cyber Communities and Their Evolution (1996-2020)"

### ISSUE THREAD

**Issue by inactinique** [C2DH/jdh-notebook#159]
PID: [cMFbEBSriHwD](https://github.com/jdh-observer/cMFbEBSriHwD)

(see abstract in backend for author's repo)

**Comment by eliselavy** [comment]
Action requested to the author
https://github.com/jdh-observer/cMFbEBSriHwD/blob/main/report.md

**Comment by eliselavy** [comment]
@biumiamy reformat [table-1](https://journalofdigitalhistory.org/en/notebook-viewer/JTJGcHJveHktZ2l0aHVidXNlcmNvbnRlbnQlMkZqZGgtb2JzZXJ2ZXIlMkZjTUZiRUJTcmlId0QlMkZmaXgtdGFnZ2luZyUyRmFydGljbGUuaXB5bmI=?idx=28&layer=hermeneutics&lh=684&pidx=28)

**Comment by eliselavy** [comment]
@inactinique sent to be peer-review
