### ISSUE TITLE
Technical review after R1: "Chronoreferencing the Italian-Slovenian Borderlands. Citizen Science, Digital Hermeneutics and Output Criticism"

### ISSUE THREAD

**Issue by inactinique** [C2DH/jdh-notebook#160]
PID: [6ig87tC5GKjQ](https://github.com/jdh-observer/6ig87tC5GKjQ)

Comments from the author: please see email sent to frederic.clavert and forwarded to jdh.admin

**Comment by eliselavy** [comment]
![Image](https://github.com/C2DH/jdh-notebook/assets/35602279/f7628168-f32d-4462-9374-1924f9411002)

**Comment by inactinique** [comment]
This is a snippet of code that the author suggest:

<iframe id="kaltura_player" src="[https://cdnapisec.kaltura.com/p/2753661/sp/275366100/embedIframeJs/uiconf_id/45459391/partner_id/2753661?iframeembed=true&playerId=kaltura_player&entry_id=1_7uy0dr3v&flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[hotspots.plugin]=1&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_vivlkw2z](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdnapisec.kaltura.com%2Fp%2F2753661%2Fsp%2F275366100%2FembedIframeJs%2Fuiconf_id%2F45459391%2Fpartner_id%2F2753661%3Fiframeembed%3Dtrue%26playerId%3Dkaltura_player%26entry_id%3D1_7uy0dr3v%26flashvars%255BstreamerType%255D%3Dauto%26flashvars%255BlocalizationCode%255D%3Den%26flashvars%255BsideBarContainer.plugin%255D%3Dtrue%26flashvars%255BsideBarContainer.position%255D%3Dleft%26flashvars%255BsideBarContainer.clickToClose%255D%3Dtrue%26flashvars%255Bchapters.plugin%255D%3Dtrue%26flashvars%255Bchapters.layout%255D%3Dvertical%26flashvars%255Bchapters.thumbnailRotator%255D%3Dfalse%26flashvars%255BstreamSelector.plugin%255D%3Dtrue%26flashvars%255BEmbedPlayer.SpinnerTarget%255D%3DvideoHolder%26flashvars%255BdualScreen.plugin%255D%3Dtrue%26flashvars%255Bhotspots.plugin%255D%3D1%26flashvars%255BKaltura.addCrossoriginToIframe%255D%3Dtrue%26%26wid%3D1_vivlkw2z&data=05%7C02%7Cfrederic.clavert%40uni.lu%7C3aa2339d1f51428ac38c08dc6e878f90%7C445a9c950f9d49539db1bc4a45dd1220%7C0%7C0%7C638506775737220825%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=caZXxjKLb5%2B1sJk4m0z%2BTvhmf8olrZQBkXxRi0FLduA%3D&reserved=0)" width="400" height="285" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="Doc-2024-03-29-Journal of digital history"></iframe>

**Comment by eliselavy** [comment]
![Image](https://github.com/C2DH/jdh-notebook/assets/35602279/b3198d9c-eca0-4aa3-afe2-6166aa045b55)

go to see with mediacenter

**Comment by eliselavy** [comment]
solved / look at INC0129018 https://service.uni.lu/sp?id=ticket&table=incident&sys_id=b68228a9470e8a903f41becd436d4353

![Image](https://github.com/C2DH/jdh-notebook/assets/35602279/5eab932d-b8e6-49ef-9b73-da623286640f)

**Comment by eliselavy** [comment]
Can be sent to the review again @inactinique 
Email to jdh.admin@uni.lu with links

> No label for all audio fragments
