### ISSUE TITLE
TEchnical review, copy-editing, design review after Accept: Edge Cases: The Making of Network Navigator and Critical Approaches to DH Tools 

### ISSUE THREAD

**Issue by inactinique** [C2DH/jdh-notebook#161]
https://github.com/jdh-observer/nAW4E5etkMR6

**Comment by inactinique** [comment]
Modifications done: https://github.com/jrladd/edge-cases-JDH
@eliselavy

**Comment by eliselavy** [comment]
Sent to copy-editing

**Comment by eliselavy** [comment]
@biumiamy feedback of the copy-editor: This document is fine - no changed needed.
To review space, comma,... in the md file
Look at the article online https://journalofdigitalhistory.org/en/article/nAW4E5etkMR6 ( need to be connected to the backend)

**Comment by biumiamy** [comment]
I'm guessing they didn't mean "previously saved", but instead "preserve"?

![Image](https://github.com/C2DH/jdh-notebook/assets/47319502/54c6b77e-4953-48b5-8d95-51db197fbe6e)

**Comment by inactinique** [comment]
I think they mean "previously saved“. What do you think @eliselavy ?

**Comment by eliselavy** [comment]
Consolidation made

**Comment by inactinique** [comment]
John Ladd, Zoe LeBlanc


From: Mirjam Pfeiffer ***@***.***>
Date: Wednesday, 5 June 2024 at 10:37
To: C2DH/jdh-notebook ***@***.***>
Cc: Frédéric CLAVERT ***@***.***>, Author ***@***.***>
Subject: Re: [C2DH/jdh-notebook] TEchnical review, copy-editing, design review after Accept: Edge Cases: The Making of Network Navigator and Critical Approaches to DH Tools (Issue #161)

author names again? I need to add them on the social media cover :)

**Comment by biumiamy** [comment]
merci!
added to the repo: https://github.com/jdh-observer/nAW4E5etkMR6/blob/main/socialmediacover.png

**Comment by eliselavy** [comment]
@biumiamy they are on the paper ;-)
![Screenshot 2024-06-05 at 10 56 36](https://github.com/C2DH/jdh-notebook/assets/35602279/1211be47-0698-4203-8179-4e876def7d6a)

**Comment by biumiamy** [comment]
- updated with the correct author names

**Comment by eliselavy** [comment]
@inactinique article. ready - status to put in publish in prod

**Comment by biumiamy** [comment]
I found some more spacing issues between citations: https://github.com/jdh-observer/nAW4E5etkMR6/compare/corrections?expand=1

**Comment by eliselavy** [comment]
Tweets + copyright template to request +  preview for last check @inactinique

**Comment by eliselavy** [comment]
Some hermeneutics tag to review by @inactinique

**Comment by inactinique** [comment]
There are other elements to change: can I create cells from markdown, is that OK? @eliselavy

**Comment by eliselavy** [comment]
@inactinique articles merged
@biumiamy social media not more aligned due to new tagging , see difference
<img width="982" alt="Screenshot 2024-07-04 at 10 21 42" src="https://github.com/C2DH/jdh-notebook/assets/35602279/f7695672-e161-400d-9464-ae0b8d0d9dfa">

**Comment by inactinique** [comment]
Do not redo the social media cover yet, I have still things to modify

**Comment by inactinique** [comment]
ok

**Comment by eliselavy** [comment]
> Do not redo the social media cover yet, I have still things to modify

merge / tag publish-social-media

**Comment by eliselavy** [comment]
@biumiamy social media cover can be made again
@inactinique tweets and copyright

**Comment by biumiamy** [comment]
updated social media cover

**Comment by inactinique** [comment]
email sent to get the tweets. copyright on atlas

**Comment by biumiamy** [comment]
btw in the mail you send to the authors, do you also mention a limit of 280 characters? (bluesky)

**Comment by inactinique** [comment]
Yes. But I would say that Bsky is 300 ?

**Comment by biumiamy** [comment]
I thought the same, but recently when I posted it was 280

**Comment by inactinique** [comment]
That is very strange

<img width="634" alt="bsky" src="https://github.com/user-attachments/assets/884eb680-765e-4be2-b9aa-da94b9930f60">

**Comment by biumiamy** [comment]
Then it was that the tweets they provided were exactly 300 characters. But I need it shorter due to the URL..

**Comment by inactinique** [comment]
And tweets added: https://github.com/jdh-observer/nAW4E5etkMR6/blob/main/tweets.md

@biumiamy I think for the length it will be OK.

**Comment by biumiamy** [comment]
sorry for being a few days too late. It's scheduled for 11 today on both FB and bluesky (using [fedica](https://fedica.com/))

**Comment by inactinique** [comment]
This is ok. Thanks!
