### ISSUE TITLE
Technical review, design review, copy-edit after accept: imagineRio Narratives: A Map-based Writing App for Rio de Janeiro

### ISSUE THREAD

**Issue by inactinique** [C2DH/jdh-notebook#162]
https://github.com/jdh-observer/jdh002-m734RWDSLo9C

**Comment by eliselavy** [comment]
To synchronize with the repo of the author:

Thanks again for your patience, we have now finalized all revisions.

We've added two paragraphs on our approach to Historical GIS and other minor changes throughout the article.

**Comment by eliselavy** [comment]
Sent for copy-editing

**Comment by eliselavy** [comment]
Copy editing can be integrated @biumiamy 
Word: https://github.com/jdh-observer/jdh002-m734RWDSLo9C/blob/main/m734RWDSLo9C.docx
Md: https://github.com/jdh-observer/jdh002-m734RWDSLo9C/blob/main/narratives.md

**Comment by biumiamy** [comment]
corrections integrated on separate branch: https://github.com/jdh-observer/jdh002-m734RWDSLo9C/tree/corrections

**Comment by biumiamy** [comment]
design feedback:

"(Karasch 1987:60, Linhares, Lévy 1971:129)" (and many more..)
wrong formatting? should be [Chicago ](https://www.chicagomanualofstyle.org/tools_citationguide/citation-guide-2.html)style
![2024-05-24 17_08_52-Window](https://github.com/C2DH/jdh-notebook/assets/47319502/d772d258-06b5-4fb4-8da7-21681679f104)

I can do it.. or we tell the author. What is better?

**Comment by eliselavy** [comment]
> corrections integrated on separate branch: https://github.com/jdh-observer/jdh002-m734RWDSLo9C/tree/corrections

consolidation made - correction in .ipynb

@biumiamy design check if this action need to be integrated https://github.com/C2DH/template_repo_JDH/blob/main/.github/workflows/github-actions-publishing.yml

**Comment by eliselavy** [comment]
> design feedback:
> 
> "(Karasch 1987:60, Linhares, Lévy 1971:129)" (and many more..) wrong formatting? should be [Chicago ](https://www.chicagomanualofstyle.org/tools_citationguide/citation-guide-2.html)style ![2024-05-24 17_08_52-Window](https://private-user-images.githubusercontent.com/47319502/333639539-d772d258-06b5-4fb4-8da7-21681679f104.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NjQwNTMsIm5iZiI6MTcxNjU2Mzc1MywicGF0aCI6Ii80NzMxOTUwMi8zMzM2Mzk1MzktZDc3MmQyNTgtMDZiNS00ZmI0LThkYTctMjE2ODE2NzlmMTA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDE1MTU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0ZGI1N2Y5YmIzMjAyYzM0N2NlZTQ4MWQ3ODYwZGQ1Y2VhMWE1ODY4ZTlkOTVkNWViOGNmMzFmMGUzYzI0YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BaYXuVq9ZDMyOcEt9LheDvNv-66h6mmZy3f4r8cgaJ8)
> 
> I can do it.. or we tell the author. What is better?

need to do it, wrong formatting for the pages

unequal. Tens of thousands of slaves landed in Rio yearly, most enroute to plantations and mines inland, but some remaining behind. At the turn of the nineteenth century, approximately 47 percent of Rio's residents were enslaved (<cite data-cite="7748027/C6Q3NJHF"></cite>:60, <cite data-cite="7748027/E4NNMKER"></cite>:129).

**Comment by eliselavy** [comment]
We need just to have a cover later @buccalon

**Comment by eliselavy** [comment]
> We need just to have a cover image to illustrate the article [@buccalon](https://github.com/buccalon)

Not mandatory finally if some media included in the paper

@biumiamy social media

**Comment by biumiamy** [comment]
social media cover added: https://github.com/jdh-observer/jdh002-m734RWDSLo9C/blob/main/socialmediacover.png

**Comment by eliselavy** [comment]
Tweets + copyright template  to request @inactinique

**Comment by eliselavy** [comment]
Ready to publish @inactinique 
copyright save in atlas
tweets attached in the repo

**Comment by inactinique** [comment]
After discussion with authors on the published version: video to be uploaded to Vimeo instead of youtube to avoid ads. 
@biumiamy can you do that?

video is on github, [media folder of the article repo](https://github.com/jdh-observer/jdh002-m734RWDSLo9C/blob/main/media/Narrativas.mp4).

**Comment by eliselavy** [comment]
> After discussion with authors on the published version: video to be uploaded to Vimeo instead of youtube to avoid ads. @biumiamy can you do that?
> 
> video is on github, [media folder of the article repo](https://github.com/jdh-observer/jdh002-m734RWDSLo9C/blob/main/media/Narrativas.mp4).

@biumiamy concerns figure-6 - md to update

**Comment by eliselavy** [comment]
vimeo integrated https://journalofdigitalhistory.org/en/article/m734RWDSLo9C?idx=46
everything there for publication
