### ISSUE TITLE
Technical review, design review, copy-editing after accept: Shaping the transnational public sphere in Republican China: Discourses and Practices of the Rotary Club in the Shanghai press (1919-1949

### ISSUE THREAD

**Issue by inactinique** [C2DH/jdh-notebook#163]

**Comment by inactinique** [comment]
Authors has made modifications: https://github.com/carmand03/china-public-sphere/

ready for copy-edit

**Comment by eliselavy** [comment]
https://github.com/jdh-observer/69Xry3ztPAk5

**Comment by eliselavy** [comment]
Changes merged
@biumiamy can you review the media folder in order to decrease the size of the notebook
25MB. the article
https://github.com/jdh-observer/69Xry3ztPAk5/tree/main/media

**Comment by eliselavy** [comment]
Sent for copy-editing

**Comment by biumiamy** [comment]
It's so big because its pngs. I can change it to jpg to reduce the size, but need to change the names. If I need to change them anyway, I can remove the "."

**Comment by biumiamy** [comment]
some citation is lost..

![2024-09-13 11_13_40-Journal of Digital History](https://github.com/user-attachments/assets/16815673-2970-411c-82e0-4f021ff1ed37)

**Comment by biumiamy** [comment]
I think the headlines are always on the narrative layer, but then the content is one the hermeneutics layer. Is this necessary?

![2024-09-13 11_15_08-Journal of Digital History](https://github.com/user-attachments/assets/ebb93bed-9b6a-4fe5-90f0-6bf0b86f0980)

**Comment by biumiamy** [comment]
And double tags still from hermeneutics and narrative

![2024-09-13 11_19_00-article ipynb - JupyterLab](https://github.com/user-attachments/assets/dc067b56-f379-4c1c-81ae-7c4165afec11)

and some weird back and forth..

![2024-09-13 11_19_41-Journal of Digital History](https://github.com/user-attachments/assets/2690abc1-6c90-4766-ad1e-8c92a84d3723)

**Comment by biumiamy** [comment]
updated all hermeneutics-step tags to hermeneutics

**Comment by eliselavy** [comment]
> Member



> some citation is lost..
> 
> ![2024-09-13 11_13_40-Journal of Digital History](https://private-user-images.githubusercontent.com/47319502/367227724-16815673-2970-411c-82e0-4f021ff1ed37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0OTQ5OTIsIm5iZiI6MTcyNjQ5NDY5MiwicGF0aCI6Ii80NzMxOTUwMi8zNjcyMjc3MjQtMTY4MTU2NzMtMjk3MC00MTFjLTgyZTAtNGYwMjFmZjFlZDM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDEzNTEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiMzM2MGZlZTRhYWEwYTBjOTI3YzBlMzQ3YTdkNzM5NGQ3ZDBjZWNiOTg2NDQxOTIxOGM1Njc2Yjc4Y2VjOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.45lRkfDyMrTHPFz3_a4kzP6l277FN_0LNJVBt8O2ks0)

fixed

**Comment by eliselavy** [comment]
@biumiamy the function [display_png](https://www.rdocumentation.org/packages/IRdisplay/versions/0.4.2/topics/display_png) is a function from R
display_jpg doesn't exist 
![Screenshot 2024-09-16 at 16 08 49](https://github.com/user-attachments/assets/1f055463-f7a9-4b37-a524-605e9a9c8e71)
![Screenshot 2024-09-16 at 16 08 49](https://github.com/user-attachments/assets/1f055463-f7a9-4b37-a524-605e9a9c8e71)

**Comment by eliselavy** [comment]
> replaced all png with JPG and changed the figure names to without the "." PR: [jdh-observer/69Xry3ztPAk5#4](https://github.com/jdh-observer/69Xry3ztPAk5/pull/4)


@biumiamy the function [display_png](https://www.rdocumentation.org/packages/IRdisplay/versions/0.4.2/topics/display_png) is a function from R
display_jpg doesn't exist

**Comment by eliselavy** [comment]
@biumiamy can you check https://github.com/jdh-observer/69Xry3ztPAk5/tree/display_html if this solution fit?

**Comment by biumiamy** [comment]
This solution doesnt work. So I added the png again in reduced size:
https://github.com/jdh-observer/69Xry3ztPAk5/pull/5

**Comment by eliselavy** [comment]
No copy-editing to add @biumiamy 
From our copy-editor:
> This article has been checked - no changes.
But media size  have been reviewed but not the anchor can look at it @biumiamy

**Comment by inactinique** [comment]
@biumiamy @eliselavy Is there still some modifications before final check to the author?

**Comment by eliselavy** [comment]
> @biumiamy @eliselavy Is there still some modifications before final check to the author?

the anchor needs to be reviewed

**Comment by inactinique** [comment]
Can I send it to Cécile and with which URL? @eliselavy

**Comment by eliselavy** [comment]
> Can I send it to Cécile and with which URL? @eliselavy

you can sent it @inactinique with following [url](https://journalofdigitalhistory.org/en/notebook-viewer/JTJGcHJveHktZ2l0aHVidXNlcmNvbnRlbnQlMkZqZGgtb2JzZXJ2ZXIlMkY2OVhyeTN6dFBBazUlMkZtYWluJTJGYXJ0aWNsZS5pcHluYg==)

**Comment by inactinique** [comment]
sent

**Comment by inactinique** [comment]
And the few remarks to implement (@biumiamy can you do it?)

Par. 7 : residual parentheses before “Judge 1996”

Par. 10 : missing parenthesis before “Wagner (Ed.) 2007”

Par. 26 : residual parenthesis before “Mittler 2004”
+ La parenthèse après “Liu Li 刘丽 2014 )“ devrait être déplacée après “See also Christian Henriot’s piece in this issue.“ 
+ Pourrait-on introduire un lien direct vers l’article de Christian Henriot dans le même numéro ? 

Par. 32  : “the same string ©” : replacer © par (c)

Par. 34 : remplacer “Chinese” par “Shanghai” dans “common terms in this context, such as “中國”, “上海”, “China”, and “Chinese” 
+ ajouter un point après “their respective vocabularies”

Par. 127 : remplacer 奇怪的的繁榮 par 奇怪的繁榮 (enlever un 的)

Par. 132 : ajouter “and” après la virgule dans : “He notably participated in the delegation which attempted to mediate between Japan and China following the Japanese attack on Shanghai in 1932, and was highly critical of the laissez-faire attitude of Rotary International and foreign authorities towards the Japanese aggression. (1369970997).”

Par. 138 : remplacer “S. Okecki” par “Stanislaw Okecki (1908-1991)”

Par. 170 : mettre les termes suivants en italiques : Yuandong, Dongfang, Yazhou

Par. 185 : 
	⁃	ajouter une brève définition après “the most frequent bigrams (i.e., pairs of adjacent words)” et l’enlever Par. 200
	⁃	Enlever le gras pour “Term Frequency-Inverse Document Frequency (TF-IDF)” 

Par. 188 : mettre “guo” en italique

Par. 192 : mettre “furen” en italique 

Par. 194 : mettre en italique “daibiao” et “weiyuanhui”

Par. 214 : mettre en italique : “gongzi” et “nü gongzi lihui"

Par. 218 : remplacer : “civil associations” par “civic associations” 

Par. 225 : mettre au passé : remplacer “delve” par “delved” et “embody” par “embodied” 

Par. 226 : ajouter “he believed” dans “emphasizing a crucial point that he believed was either overlooked or downplayed during the lecture” 

Par. 229 : ajouter “threatened by” dans “including international peace (threatened by Japan aggression)”

Par. 240 and Par 241 : à annoter en “hermeneutics layer” 

Spelling inconsistencies : North-China Herald, North-China Daily News : ajouter un trait d’union aux occurrences suivantes: 
- Par. 10 : North-China Herald & Daily News
- Par. 26 : North-China Daily News, North-China Herald (x 2)
- Par. 28 : North-China Herald 
- Bibliography (dernière ligne) : Rotary’s Progress in China. (1935). The North-China Herald, 343

TABLES ET FIGURES : 

Figure 2 : je suggère de supprimer les images Fig2e et Fig2f qui sont illisibles 
+ Simplifier la légende en conséquence : “Distribution of documents mentioning the Rotary Club in Shenbao (top) and the ProQuest collection (bottom). The additional graphs serve to contextualize the results of the query. The second graphs (blue lines) show the percentage of the entire corpora that the query results represent.” 
+ Pourrait-on créer une galerie 2X2 de manière à aligner les images correspondantes sur deux colonnes pour faciliter la comparaison entre les deux corpus ? 

Figure 3 : “A simple three-step method for creating short text units cantered on the queried terms” : remplacer “cantered” en “centred”

Table 36 : les termes en gras n’apparaissent pas. Comme dans la Table 34, il faudrait mettre en gras les terms suivants :  
	⁃	公共 (Gonggong) Public (common)
	⁃	公衆 (Gongzhong) The public
	⁃	公民 (Gongmin) Citizen
	⁃	公用 (Gongyong) Public use
	⁃	公益 (Gongyi) Public welfare

Est-il possible de mettre en italique les termes suivants dans les légendes des figures : 
	⁃	Figure 1 : “Shenbao”, “China Weekly Review”
	⁃	Figure 2 : “Shenbao”
	⁃	Figure 3 : “Shenbao”
	⁃	Figure 8 : “Shenbao”
	⁃	Figure 9 : “Shenbao”
	⁃	Figure 10 : “Shenbao”
	⁃	Figure 13 : “Shenbao”
	⁃	Figure 14 : “Shenbao”
	⁃	Figure 15 : “Shenbao”
	⁃	Figure 16 : “Shenbao”
	⁃	Figure 17 : “Shenbao”
	⁃	Figure 18 : “Shenbao”
	⁃	Figure 19 : “Shenbao”
	⁃	Figure 23 : “Shenbao”
	⁃	Figure 24 : “Shenbao”


BIBLIOGRAPHY  : 

Retirer la référence suivante : 
Liu Li 刘丽. (2014). Zhongguo jindai baoye caifang shilun: yi shenbao wei zhongxin de kaocha 中国近代报业采访史论: 以《申报》为中心的考察 (Histoire du journalisme moderne en Chine : une étude centrée sur le Shenbao). Anhui daxue chubanshe 安徽大学出版社.

Les titres en chinois ne devraient pas être en italique : 

Deng Zhenglai 邓正来著 (Ed.). (2021). Guojia yu shehui: Zhongguo shimin shehui yanjiu 国家与社会：中国市民社会研究 (State and Society: Research on Chinese Civil Society). Beijing Book Co. Inc.

Liu Li 刘丽. (2014). Zhongguo jindai baoye caifang shilun: yi shenbao wei zhongxin de kaocha 中国近代报业采访史论: 以《申报》为中心的考察 (On the History of Newspaper Interviews in Modern China: An Investigation Centered on “Shenbao”). Anhui daxue chubanshe 安徽大学出版社.

Tang Xiaobing 唐小兵. (2012). Xiandai Zhongguo de gonggong yulun: yi Dagongbao “Xingqi lunwen” he Shenbao “Ziyoutan” wei li 现代中国的公共舆论: 以"大公报""星期论文"和"申报""自由谈"为例 

Shimin shehui yu guojia: xueli shang de fenye liang zhong jiagou 市民社会与国家 -- 学理上的分野与两种架构 (Civil Society and China: Theoretical divide and dual structure). (1993). Zhongguo Shehuikexue Jikan 中国社会季刊, 3, 5–62.

**Comment by biumiamy** [comment]
I can do it, but what about the bibliography? doesnt it need to be changed in Zotero?

**Comment by inactinique** [comment]
You can remove the one that is to be removed. I don’t think you can make the titles in Chinese not italics.

From: Mirjam Pfeiffer ***@***.***>
Date: Monday, 14 October 2024 at 13:28
To: C2DH/jdh-notebook ***@***.***>
Cc: Frédéric CLAVERT ***@***.***>, Mention ***@***.***>
Subject: Re: [C2DH/jdh-notebook] Technical review, design review, copy-editing after accept: Shaping the transnational public sphere in Republican China: Discourses and Practices of the Rotary Club in the Shanghai press (1919-1949 (Issue #163)

I can do it, but what about the bibliography? doesnt it need to be changed in Zotero?

**Comment by eliselavy** [comment]
> I can do it, but what about the bibliography? doesnt it need to be changed in Zotero?

@biumiamy to remove a reference , should be made in the metadata of the notebook.
> [!CAUTION]
> Take care that the reference is not used in the text

```
"metadata": {
  "celltoolbar": "Edit Metadata",
  "citation-manager": {
   "items": {}
  },
  "cite2c": {
   "citations": {
    "626961/25WN7ZZR": {
     "DOI": "10.46298/jdmdh.11756",
     "URL": "https://shs.hal.science/halshs-04178820",
     "author": [
      {
       "family": "Blouin",
       "given": "Baptiste"
      },
      {
       "family": "Henriot",
       "given": "Christian"
      },
      {
       "family": "Armand",
       "given": "Cécile"
      }
     ],
     "container-title": "Journal of Data Mining and Digital Humanities",
     "id": "626961/25WN7ZZR",
     "issued": {
      "year": 2023
     },
     "title": "HistText: An Application for leveraging large-scale historical textbases",
     "type": "article-journal",
     "volume": "2023"
    },
    "626961/2689WDL7": {
     "author": [
```
First process to the change in the md files
Pull request
and after change about the bibliography

**Comment by biumiamy** [comment]
I didnt touch bib yet. Its always dangerous :D

> Could we introduce a direct link to Christian Henriot's article in the same issue?
So whats the link?

**Comment by biumiamy** [comment]
Ah I didnt understand that it's an article from us. Thank you.

Thank you for taking a look at the bib part.

**Comment by biumiamy** [comment]
PR for the other stuff already:
https://github.com/jdh-observer/69Xry3ztPAk5/pull/8

**Comment by inactinique** [comment]
> > Could we create a 2X2 gallery so as to align the corresponding images in two columns to facilitate the comparison between the two corpora?
> 
> For this request I can only propose this (copied together in photoshop) What do you think? @inactinique
> 
> ![Fig2_a-d](https://private-user-images.githubusercontent.com/47319502/376298226-26dc0048-c113-42d3-9e7a-d84e531d9586.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5Nzg2MjcsIm5iZiI6MTcyODk3ODMyNywicGF0aCI6Ii80NzMxOTUwMi8zNzYyOTgyMjYtMjZkYzAwNDgtYzExMy00MmQzLTllN2EtZDg0ZTUzMWQ5NTg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDA3NDUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkMmJkYzUwZTg5OWU4Yzg0NGJmNTNmYjJhZDM5NjViNzM1NzgwOTVjN2JkZjZjZWY2OWJjYjc5ZjkwZjJiMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3O9oX1DcwCHh9L2GT7Ws81QSW98VkGYXdq-WxPb2VRE)

Looks clean.

**Comment by biumiamy** [comment]
okay updated the PR 
https://github.com/jdh-observer/69Xry3ztPAk5/pull/8

**Comment by eliselavy** [comment]
> > replaced all png with JPG and changed the figure names to without the "." PR: [jdh-observer/69Xry3ztPAk5#4](https://github.com/jdh-observer/69Xry3ztPAk5/pull/4)
> 
> @biumiamy the function [display_png](https://www.rdocumentation.org/packages/IRdisplay/versions/0.4.2/topics/display_png) is a function from R display_jpg doesn't exist

@biumiamy i believe the images were replaced in png ? as we mentionned the problem to similar articles (from the DHChina)
can you update this repo https://github.com/jdh-observer/69Xry3ztPAk5/tree/corrections/media
i will update the code

**Comment by biumiamy** [comment]
Updated it:
https://github.com/jdh-observer/69Xry3ztPAk5/compare/main...corrections

**Comment by eliselavy** [comment]
- References updated
- Skim generated
- Article in prod but not in published status

@biumiamy socialmedia cover can be added
@inactinique 
- tweet and copyright to be requested for the article in CC-BY-NC-ND , article [here](https://journalofdigitalhistory.org/en/notebook-viewer/JTJGcHJveHktZ2l0aHVidXNlcmNvbnRlbnQlMkZqZGgtb2JzZXJ2ZXIlMkY2OVhyeTN6dFBBazUlMkZtYWluJTJGc2tpbS1hcnRpY2xlLmlweW5i)
- DOI
- copyright can be also requested for the editorial

**Comment by eliselavy** [comment]
PUBLISHED

**Comment by biumiamy** [comment]
social media scheduled for today
