### ISSUE TITLE
Guideline video: writing environment for jupyterlab

### ISSUE THREAD

**Issue by eliselavy** [C2DH/jdh-notebook#164]
Step 1: Install [Docker](https://www.docker.com/products/docker-desktop/)
Step 2: Install [Github](https://desktop.github.com/)
Step 3: Clone jupyter-stack in Github
Step 4: Open console: cd path, docker-compose up
Step 5: Docker: open Jupyterlab in browser
Step 6: enter Zotero key
Step 7: use template for R or Python 

Video here: https://vimeo.com/948218439/666655d0b4?share=copy

**Comment by eliselavy** [comment]
@biumiamy https://journalofdigitalhistory.org/en/guidelines/AuthorGuideline-mac
If you can use the tag figure as the video tag doesn’t work

**Comment by eliselavy** [comment]
@biumiamy need to be removed
<img width="1040" alt="Screenshot 2024-07-16 at 11 02 11" src="https://github.com/user-attachments/assets/f9434248-7dba-4280-95b5-20648f063fa0">

**Comment by eliselavy** [comment]
> @biumiamy need to be removed <img alt="Screenshot 2024-07-16 at 11 02 11" width="1040" src="https://private-user-images.githubusercontent.com/35602279/349016680-f9434248-7dba-4280-95b5-20648f063fa0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMjE1MzgsIm5iZiI6MTcyMTEyMTIzOCwicGF0aCI6Ii8zNTYwMjI3OS8zNDkwMTY2ODAtZjk0MzQyNDgtN2RiYS00MjgwLTk1YjUtMjA2NDhmMDYzZmEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDA5MTM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhNjVhMDBlMjRiZmNiOWI2MTg4OTdiZjZjZTI2MGY1OWFkYjRjYWMzNWYzZjZiMDM2NmQyMzkwY2FiOTBhNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RVevLqL_wdruYSR-lBJPBqozTC04uIjqVxAf4nIBP1g">

I go to give you the proper version

**Comment by biumiamy** [comment]
updated the figures & the alternative writing environment
