### ISSUE TITLE
Integrate the editorial for the digital issue 

### ISSUE THREAD

**Issue by eliselavy** [C2DH/jdh-notebook#165]
Integrate the editorial for the digital issue 

[Introduction_Digital Tools Special Issue JDH.docx](https://github.com/user-attachments/files/15584069/Introduction_Digital.Tools.Special.Issue.JDH.docx)

**Comment by eliselavy** [comment]
@inactinique done
Repo here: https://github.com/jdh-observer/DQnMN3c5JU95
Article [here](https://journalofdigitalhistory.org/en/notebook-viewer/JTJGcHJveHktZ2l0aHVidXNlcmNvbnRlbnQlMkZqZGgtb2JzZXJ2ZXIlMkZEUW5NTjNjNUpVOTUlMkZtYWluJTJGYXJ0aWNsZS5pcHluYg==)

No abstract:
<img width="481" alt="Screenshot 2024-06-05 at 16 18 54" src="https://github.com/C2DH/jdh-notebook/assets/35602279/ca31e3e5-9727-4f2e-b576-e5e0fba4c026">

**Comment by eliselavy** [comment]
Added in production also https://journalofdigitalhistory.org/en/articles

**Comment by inactinique** [comment]
So I need to go through scholarone to get one, I suppose?

**Comment by inactinique** [comment]
10.1515/JDH.2024.0012

**Comment by eliselavy** [comment]
Addition autohrs for correct citation
<img width="1119" alt="Screenshot 2024-06-10 at 10 53 50" src="https://github.com/C2DH/jdh-notebook/assets/35602279/797d1e6c-db03-45d0-a2b9-aa47ebe5b448">
