### ISSUE TITLE
Copy editing / Technical / design review after accept: "Secret Societies and Revolving Doors: Using Mapping the Gay Guides to Study LBGTQ Life in the United States, 1965-1989"

### ISSUE THREAD

**Issue by inactinique** [C2DH/jdh-notebook#166]
pid: [X3MGSKqAycaT](https://github.com/jdh-observer/X3MGSKqAycaT)

author: Amanda Regan

**Comment by eliselavy** [comment]
@inactinique no copy-editing for Andy?

**Comment by eliselavy** [comment]
Send for copy-editing

**Comment by eliselavy** [comment]
@biumiamy correction can be inserted https://github.com/jdh-observer/X3MGSKqAycaT/blob/main/article.md
see docx here https://github.com/jdh-observer/X3MGSKqAycaT

**Comment by biumiamy** [comment]
integrated, here's the PR:
https://github.com/jdh-observer/X3MGSKqAycaT/compare/corrections?expand=1

**Comment by biumiamy** [comment]
there's sth strange here in the bib:
![2024-06-13 17_20_24-Journal of Digital History](https://github.com/C2DH/jdh-notebook/assets/47319502/9ce4bcc5-007a-4ed6-97f5-f70c609708d5)

**Comment by biumiamy** [comment]
updated: https://github.com/jdh-observer/X3MGSKqAycaT/compare/biblio?expand=1

**Comment by eliselavy** [comment]
@biumiamy social cover

Tweets + copyright template  to request @inactinique 
article in production - status design review https://journalofdigitalhistory.org/en/article/X3MGSKqAycaT

**Comment by inactinique** [comment]
tweets and agreement asked.

**Comment by biumiamy** [comment]
We have a strange table again..
![2024-06-18 15_16_38-Journal of Digital History](https://github.com/C2DH/jdh-notebook/assets/47319502/c5478a67-4b74-4a3e-a17a-5b71745b9438)

**Comment by biumiamy** [comment]
@danieleguido Is there a way to break the line despite it being a citation?

![2024-06-18 15_18_11-Journal of Digital History](https://github.com/C2DH/jdh-notebook/assets/47319502/ff8834b8-007f-4db3-8c15-d0c10028a856)

**Comment by biumiamy** [comment]
Btw the weird spacing is still there / back. Even though I had corrected it in the md file:

![2024-06-18 15_21_11-Journal of Digital History](https://github.com/C2DH/jdh-notebook/assets/47319502/8d1355bf-67bb-4aaa-9c97-6e069b6065ad)

**Comment by biumiamy** [comment]
added social media cover: https://github.com/jdh-observer/X3MGSKqAycaT/blob/main/socialmediacover.png

**Comment by inactinique** [comment]
> Btw the weird spacing is still there / back. Even though I had corrected it in the md file:
> 
> ![2024-06-18 15_21_11-Journal of Digital History](https://private-user-images.githubusercontent.com/47319502/340690543-8d1355bf-67bb-4aaa-9c97-6e069b6065ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MDk5MDYsIm5iZiI6MTcxODgwOTYwNiwicGF0aCI6Ii80NzMxOTUwMi8zNDA2OTA1NDMtOGQxMzU1YmYtNjdiYi00YWFhLTljOTctNmUwNjliNjA2NWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDE1MDY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxMTE2N2Y0NTcyMTQ2ODZjNGVlZTgzNGJkMWExNzIzMDE1ZTMwMzViZWRmZTY4MGZjZGNlYTliODA3OTFjMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hZ0MESqB7i4k531bY1nkKe_dt4vJfpnIjBSWn7UhQKY)

I have had a look and the problem disappeared from the article notebook but reappeared in the skim-article notebook.

@eliselavy a bug in one of the github script?

**Comment by inactinique** [comment]
> We have a strange table again.. ![2024-06-18 15_16_38-Journal of Digital History](https://private-user-images.githubusercontent.com/47319502/340689021-c5478a67-4b74-4a3e-a17a-5b71745b9438.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MDk5MDYsIm5iZiI6MTcxODgwOTYwNiwicGF0aCI6Ii80NzMxOTUwMi8zNDA2ODkwMjEtYzU0NzhhNjctNGI3NC00YTNlLWExN2EtNWI3MTc0NWI5NDM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDE1MDY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwY2RkNjBlN2ExOTk5OTJmZGJiMmJhMjhkMGY2YTY4YWRkZTIyMDgwNDM0NGFkYTIxNzkxYzczNDRmYmFkNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2pXG0mv4nLYdIeKpLH5Ir7LqhJGUYUWh7opzPXJefLI)
> 
> and this one too
> 
> ![2024-06-18 15_19_37-Journal of Digital History](https://private-user-images.githubusercontent.com/47319502/340689989-5c36874c-432e-4a7b-9f18-9263adbc3806.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MDk5MDYsIm5iZiI6MTcxODgwOTYwNiwicGF0aCI6Ii80NzMxOTUwMi8zNDA2ODk5ODktNWMzNjg3NGMtNDMyZS00YTdiLTlmMTgtOTI2M2FkYmMzODA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDE1MDY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyOTkyMGU0NGM3MDcyZjViZDM3MmFlMTZlZjFhYWY3ZjFmOWM3ZTE5NjJhOGEzY2I5ZGI0NmI5Y2U1ZmU0M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w4h6WEPAcA3Pnb6wb9leF9TBPPBmbYEld_Y0-fyFtVQ)

Yes, the first one should be that: 
<img width="921" alt="regan01" src="https://github.com/C2DH/jdh-notebook/assets/1017260/7fded8be-2cb7-41f6-b3ed-c90bcdad8be9">

The second one is OK, the strange <chr> things are there because of R.

**Comment by eliselavy** [comment]
> > Btw the weird spacing is still there / back. Even though I had corrected it in the md file:
> > ![2024-06-18 15_21_11-Journal of Digital History](https://private-user-images.githubusercontent.com/47319502/340690543-8d1355bf-67bb-4aaa-9c97-6e069b6065ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MDk5MDYsIm5iZiI6MTcxODgwOTYwNiwicGF0aCI6Ii80NzMxOTUwMi8zNDA2OTA1NDMtOGQxMzU1YmYtNjdiYi00YWFhLTljOTctNmUwNjliNjA2NWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDE1MDY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxMTE2N2Y0NTcyMTQ2ODZjNGVlZTgzNGJkMWExNzIzMDE1ZTMwMzViZWRmZTY4MGZjZGNlYTliODA3OTFjMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hZ0MESqB7i4k531bY1nkKe_dt4vJfpnIjBSWn7UhQKY)
> 
> I have had a look and the problem disappeared from the article notebook but reappeared in the skim-article notebook.
> 
> @eliselavy a bug in one of the github script?

fixed the action has not been run after this update
go to be trigger after each push to avoid this

**Comment by inactinique** [comment]
Authors sent the tweets.

**Comment by inactinique** [comment]
And copyright contract on atlas

**Comment by eliselavy** [comment]
@biumiamy every thing there to communicate on social media (hope to fix bluesky social media cover)
