### ISSUE TITLE
Copy editing / technical /design review after accept: Super-Vision: Tracing EPFL History Through 8,000 Doctoral Theses

### ISSUE THREAD

**Issue by inactinique** [C2DH/jdh-notebook#171]
PID: Yn8z7XNPKzy4
https://github.com/jdh-observer/Yn8z7XNPKzy4
DOI: 2023.0004.R1

**Comment by eliselavy** [comment]
Tweets added
https://github.com/jdh-observer/Yn8z7XNPKzy4/blob/main/tweets.md
Copyright declaration in atlas
Desanomization 
Sent to copy editing

**Comment by eliselavy** [comment]
@biumiamy copy editing can be added to md file

**Comment by biumiamy** [comment]
corrections implemented, here is the PR:
https://github.com/jdh-observer/Yn8z7XNPKzy4/pull/2

**Comment by eliselavy** [comment]
@biumiamy socialmedia cover 

added in production status design review

strange the euro symbol added after copy-editing
![Screenshot 2024-06-19 at 16 59 59](https://github.com/C2DH/jdh-notebook/assets/35602279/67a62888-8ba7-4434-82eb-054c86a1e9b2)

**Comment by biumiamy** [comment]
I know, before it was just "The School of Life Sciences (E)"..

**Comment by biumiamy** [comment]
you know what I think there's a mistake lol. 
It should be (A), (B), (C), (D), (E).
but I think it was automatically converted from Word to (c) copyright and (E) as € xD

**Comment by biumiamy** [comment]
I can change the € to (E). But in the MD file its actually not the copyright. So how can we make it that its not a copyright?

**Comment by inactinique** [comment]
If you write like that \(C\) ?

**Comment by eliselavy** [comment]
ok correction made 
 ```
  {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "Looking at the figure below, we can easily see where the faculties are positioned. Assuming a faculty numbering on two lines, respectively (A), (B), (C), (C), (D), (E), we can infer some information about the general interdisciplinary structure by looking at this small multiple. The School of Architecture, Civil and Environmental Engineering (A) and the School of Computer and Communication Sciences (B) are characterized by a well-defined lexical structure, which confines them to specific regions of the map. The School of Basic Sciences (C) and the School of Engineering (D) spread horizontally, suggesting the use of a lexicon that overlaps other disciplines. The School of Life Sciences (E) proves to have a strong identity despite its young age, and the College of Management of Technology has not enough doctoral students to delineate a clear border."
      ]
    },
```
https://raw.githubusercontent.com/jdh-observer/Yn8z7XNPKzy4/main/skim-article.ipynb

but seem a frontend problem no? @danieleguido 
raw is ok , but frontend no  , see [here](https://journalofdigitalhistory.org/en/notebook-viewer/JTJGcHJveHktZ2l0aHVidXNlcmNvbnRlbnQlMkZqZGgtb2JzZXJ2ZXIlMkZZbjh6N1hOUEt6eTQlMkZtYWluJTJGc2tpbS1hcnRpY2xlLmlweW5i?idx=31&layer=narrative&lh=715&pidx=31&pl=narrative&y=577)

**Comment by danieleguido** [comment]
This `&#40;c) `  should works, &#40;c)

**Comment by eliselavy** [comment]
Need to fixed citation
one author missing: Dario Rodighier

**Comment by eliselavy** [comment]
> Need to fixed citation one author missing: Dario Rodighier

fixed

just misisng soicalcover to be able to publish @biumiamy

**Comment by biumiamy** [comment]
@danieleguido 
Is there a way to extend the viewer to show the full graphic without having it cut at the top? and could we set a white bg perhaps?

![Image](https://github.com/C2DH/jdh-notebook/assets/47319502/91777bc7-f050-430e-a8aa-3f13afe55b47)

**Comment by biumiamy** [comment]
added social media cover: 
https://github.com/jdh-observer/Yn8z7XNPKzy4/blob/main/socialmediacover.png

**Comment by inactinique** [comment]
> is it correct that there's not a single H-layer cell?
> 
> ![Image](https://private-user-images.githubusercontent.com/47319502/344217974-cff2778c-25c1-455b-9858-cf2df71e0247.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MjY4ODcsIm5iZiI6MTcxOTgyNjU4NywicGF0aCI6Ii80NzMxOTUwMi8zNDQyMTc5NzQtY2ZmMjc3OGMtMjVjMS00NTViLTk4NTgtY2YyZGY3MWUwMjQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA5MzYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0ZWY2M2MzMmQyYjA5Zjc2NDRhN2RkYzcwYTZkOGExMGM0NmMxOWMwMWQzZGE4Zjg5ZDAwMjAxMGFiY2FlNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q0H-Sri-L-RozIW8L82VjO2Xrfeapi_hug1TJJP6TOg)

No? I'll see this with the author, as all the part "data investigation and analysis" could be hermeneutic.

**Comment by eliselavy** [comment]
Hermeneutics now present:
 socialcover needs to be regenerated @biumiamy 
<img width="460" alt="Screenshot 2024-07-03 at 10 51 13" src="https://github.com/C2DH/jdh-notebook/assets/35602279/46bda0be-2795-4c66-943e-27b151fbc565">

**Comment by eliselavy** [comment]
> there's an empty code cell at the end again
> 
> ![Image](https://private-user-images.githubusercontent.com/47319502/344217719-58a936ac-a787-43dd-84f4-a1f3314ab0c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTU5MzcsIm5iZiI6MTcxOTk5NTYzNywicGF0aCI6Ii80NzMxOTUwMi8zNDQyMTc3MTktNThhOTM2YWMtYTc4Ny00M2RkLTg0ZjQtYTFmMzMxNGFiMGMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDA4MzM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwNmZmOTgwYWE1YzViM2I1NTIzZGY3ZmI2ODM2ZWEzNjc3Nzk3OWUwM2JmZDZjMDJhY2VmN2JiOWE2OTY1ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u2xGIFvQ_Q1_9XKQbaiakIfhymoIaXsOX9m0jZ02d-I)

Strange nothing in the notebook
<img width="1118" alt="Screenshot 2024-07-03 at 10 58 13" src="https://github.com/C2DH/jdh-notebook/assets/35602279/826283f8-7b1e-4ab7-b1ea-0df5b49bd003">

**Comment by biumiamy** [comment]
social media cover updated!

**Comment by eliselavy** [comment]
> social media cover updated!

and just set to published !
only social campaign to do.

**Comment by biumiamy** [comment]
we can add two more status for our issues:
- author final check
- publish social media

**Comment by eliselavy** [comment]
Reorder of authors made:
- at the article level
- at the preload information
- at the citation level
@biumiamy social media to update

**Comment by biumiamy** [comment]
social media cover updated

**Comment by inactinique** [comment]
Author has now a bluesky account: https://bsky.app/profile/dariorodighiero.bsky.social

@biumiamy propaganda can start. Tomorrow around 11?

**Comment by biumiamy** [comment]
okay

**Comment by biumiamy** [comment]
Sorry that week I was just working on the video for the book project. It's now scheduled for Monday morning 11am.
