### ISSUE TITLE
Technical review after R1: The Text Analysis Prototype for GaLiLeO: Galileo's Library and Letters Online

### ISSUE THREAD

**Issue by inactinique** [C2DH/jdh-notebook#172]
PID: FYjDViXVXggz

https://github.com/jdh-observer/FYjDViXVXggz

[JDHRevisionsResponse.docx](https://github.com/user-attachments/files/15838560/JDHRevisionsResponse.docx)

Author asks that we synchronize their repo with the jdh-observer one. For repo URL, see backend

**Comment by eliselavy** [comment]
Authors didn't use the version of jdh-observer to resynchronize

**Comment by eliselavy** [comment]
problem table-1

not same representation in front end , see here https://journalofdigitalhistory.org/en/notebook-viewer/JTJGcHJveHktZ2l0aHVidXNlcmNvbnRlbnQlMkZqZGgtb2JzZXJ2ZXIlMkZGWWpEVmlYVlhnZ3olMkZyZXZpZXdfUjElMkZhcnRpY2xlLmlweW5i?idx=69&layer=hermeneutics&lh=684&pidx=30

problem doesn't fit with

galileo" (line 2); "mani" (hands) and "galilei" (line 3); "bacio" (kiss, line 4); "libro" (book, line 5); "terra" (earth, line 6);

problem text/plain

**Comment by eliselavy** [comment]
In R:

There are certainly more user-friendly ways to present this information, so I will highlight a few words that surprised me as a specialist: “galileo” (line 2); “mani” (hands), “galilei” (line 3); “bacio” (kiss, line 4); “libro” (book, line 5); “terra” (earth, line 6); “opera” (work, line 8); “cielo” (sky, line 9); and “libri” (books, line 12). 

<img width="763" alt="Screenshot 2024-07-22 at 11 58 21" src="https://github.com/user-attachments/assets/faa6b4c8-31cd-44d7-947a-61dc9c633577">

**Comment by eliselavy** [comment]
> In R:
> 
> There are certainly more user-friendly ways to present this information, so I will highlight a few words that surprised me as a specialist: “galileo” (line 2); “mani” (hands), “galilei” (line 3); “bacio” (kiss, line 4); “libro” (book, line 5); “terra” (earth, line 6); “opera” (work, line 8); “cielo” (sky, line 9); and “libri” (books, line 12).
> 
> <img alt="Screenshot 2024-07-22 at 11 58 21" width="763" src="https://private-user-images.githubusercontent.com/35602279/350922748-faa6b4c8-31cd-44d7-947a-61dc9c633577.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MjYwNDQsIm5iZiI6MTcyMTcyNTc0NCwicGF0aCI6Ii8zNTYwMjI3OS8zNTA5MjI3NDgtZmFhNmI0YzgtMzFjZC00NGQ3LTk0N2EtNjFkYzljNjMzNTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDA5MDkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhMDQwNjIzMDIwODIzM2U1YWU5ZjEwYzE2ZWRmYmMyM2U4MTkyNzIxYTM0YjQxZWUzYzRkNTEwY2UxOTMwY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uliSKv5_7oiyyax6XQyTQb5cwwupFJ1TsrkpJxdY1Tg">
> > Need to contact the author

author contacted

**Comment by eliselavy** [comment]
Update text with appropriate index given by author:
There are certainly more user-friendly ways to present this information, but specialists might be surprised to see the following: “galileo” (27); “mani” (hands; 36) and “galilei” (39); “bacio” (kiss, 70); “libro” (book; 86); “terra” (earth; 96); “opera” (work; 127); “cielo” (sky; 147); and “libri” (books; 184). 

Using `data-table` tag, some item not there 

<img width="1266" alt="Screenshot 2024-07-29 at 17 23 22" src="https://github.com/user-attachments/assets/470dcea6-219b-4574-a68d-eefc20572e78">

**Comment by eliselavy** [comment]
<img width="1110" alt="Screenshot 2024-07-29 at 18 17 48" src="https://github.com/user-attachments/assets/d5574c8b-1f7c-488a-a16e-b110855680a0">

**Comment by eliselavy** [comment]
In myBinder problem notebook read-only

<img width="1417" alt="Screenshot 2024-07-29 at 18 43 10" src="https://github.com/user-attachments/assets/e7ec2a05-5120-494d-921d-652b17ac305d">

**Comment by eliselavy** [comment]
> <img alt="Screenshot 2024-07-29 at 18 17 48" width="1110" src="https://private-user-images.githubusercontent.com/35602279/353148845-d5574c8b-1f7c-488a-a16e-b110855680a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNzAyMzIsIm5iZiI6MTcyMjI2OTkzMiwicGF0aCI6Ii8zNTYwMjI3OS8zNTMxNDg4NDUtZDU1NzRjOGItMWY3Yy00ODhhLWExNmUtYjExMDg1NTY4MGEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDE2MTg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxZTJjZTg0NjQwZDZhZTFlOWY0ODljNTgyM2JjZTVkZjdjNmYyNmZkZTlhN2FiOWE4NzhiOGZjODA2NzcyNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GA76IlCVN8MrrQ8XGY-FbYnv2O9cLcakhLjSq0qSXS4"> <img alt="Screenshot 2024-07-29 at 18 18 28" width="899" src="https://private-user-images.githubusercontent.com/35602279/353149069-eab67f91-b87e-4961-a391-2977878ade63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNzAyMzIsIm5iZiI6MTcyMjI2OTkzMiwicGF0aCI6Ii8zNTYwMjI3OS8zNTMxNDkwNjktZWFiNjdmOTEtYjg3ZS00OTYxLWEzOTEtMjk3Nzg3OGFkZTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDE2MTg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4MmIzNWYwODFhMzc3MjQ2ODM5YTYzZTYxMmVlYTliZTc3YmQwYTgyNWE0MTBlMjNmZTNlZmI3ZTUyZGNjZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YNp1NU0I8JKM2kcdJjnzZclgqC14DRxYDRraIdXuA7g">

fixed by displaying full dataframe

**Comment by eliselavy** [comment]
Problem by running cell, problem permissions to write to the directory where the notebooks are stored
<img width="651" alt="Screenshot 2024-07-29 at 20 34 47" src="https://github.com/user-attachments/assets/169803df-fc18-4c3c-9926-690824a96a78">

**Comment by eliselavy** [comment]
Problem by doing running all
All cells are ok, except this one, causing kernel died
![Screenshot 2024-07-30 at 09 35 25](https://github.com/user-attachments/assets/c2596557-57f5-43a7-afdf-082396361bb1)

**Comment by eliselavy** [comment]
Use of memory > 2GB the maximum allowed by myBinder

**Comment by eliselavy** [comment]
> Use of memory > 2GB the maximum allowed by myBinder

Using also `[jupyter-resource-usage](https://github.com/jupyter-server/jupyter-resource-usage)` 
Now Memory: 214.3 MB

**Comment by eliselavy** [comment]
@inactinique sent for peer-review

**Comment by eliselavy** [comment]
> Problem by doing running all All cells are ok, except this one, causing kernel died ![Screenshot 2024-07-30 at 09 35 25](https://private-user-images.githubusercontent.com/35602279/353364584-c2596557-57f5-43a7-afdf-082396361bb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMDc2MjAsIm5iZiI6MTcyMzEwNzMyMCwicGF0aCI6Ii8zNTYwMjI3OS8zNTMzNjQ1ODQtYzI1OTY1NTctNTdmNS00M2E3LWFmZGYtMDgyMzk2MzYxYmIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA4NTUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiOGYzYjhhNzQ1OGQwMzBiMDhlYmNkYWYzMjIyOGJkM2IxMTYyMTY1NTM2NmU2ZmNmOGQ2ZmI5NmQxN2QyY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZSUE7BlvEOxxysee1uQADFZ794OqDLR_nZdw6CUHCJg)

@inactinique not fully executable on mybinder due to the use of memory
