### ISSUE TITLE
Copy editing / technical /design review after accept: Women in Early Modern Handwritten News: Random Walks and Semantic Wanderings in the Medici Archive

### ISSUE THREAD

**Issue by eliselavy** [C2DH/jdh-notebook#173]
https://github.com/jdh-observer/jnkqqTTKW8km

**Comment by eliselavy** [comment]
@biumiamy revisions by Andy are available here: https://github.com/jdh-observer/jnkqqTTKW8km/blob/main/jnkqqTTKW8km.docx
to be integrated : https://github.com/jdh-observer/jnkqqTTKW8km/blob/main/paper.md

**Comment by biumiamy** [comment]
PR here: https://github.com/jdh-observer/jnkqqTTKW8km/pull/7

There are some issue in the bibliography that I cant touch with the md file

**Comment by eliselavy** [comment]
> PR here: [jdh-observer/jnkqqTTKW8km#7](https://github.com/jdh-observer/jnkqqTTKW8km/pull/7)
> 
> There are some issue in the bibliography that I cant touch with the md file

PR merge and consolidation ipynb
What are the issues in the bibliography? Article stil in dev , [here](http://10.240.4.179/en/article/jnkqqTTKW8km?s=bib)
@biumiamy social media cover
@inactinique tweets + copyright template

**Comment by inactinique** [comment]
the next varia issue

**Comment by biumiamy** [comment]
so its not on the frontend yet?

**Comment by eliselavy** [comment]
> so its not on the frontend yet?

the frontend of the dev, as for the moment, i have no description for Varia, filter on  Issue n.4 Varia bis , it's the first article http://10.240.4.179/en/articles

**Comment by biumiamy** [comment]
social media cover added: https://github.com/jdh-observer/jnkqqTTKW8km/blob/main/socialmediacover.png

**Comment by eliselavy** [comment]
@inactinique article in prod in design_review
DOI to add - tweets and copyright to request

**Comment by inactinique** [comment]
Email about social media posts and copyright sent to author.

**Comment by inactinique** [comment]
Can I send it for a last check by the author?
with this URL: https://github.com/jdh-observer/jnkqqTTKW8km ?

**Comment by biumiamy** [comment]
I see many issues
spacing.. double figures

![2024-07-15 13_59_30-Journal of Digital History](https://github.com/user-attachments/assets/c154f8e2-9bf0-4942-9326-879daf73d42c)

![2024-07-15 14_00_31-Journal of Digital History](https://github.com/user-attachments/assets/d3296844-7a25-4521-87ed-a4c54f4bdb4b)

did the script already run?
![2024-07-15 14_01_24-Journal of Digital History](https://github.com/user-attachments/assets/9c3cfd52-bee8-4baa-8341-88de3c027ee6)

**Comment by biumiamy** [comment]
this is also strange

![2024-07-15 14_03_35-Journal of Digital History](https://github.com/user-attachments/assets/7554becb-0712-4d67-9c89-b0068f82be36)

**Comment by biumiamy** [comment]
figure 9... see figure 10? maybe not the best idea..

![2024-07-15 14_04_58-Journal of Digital History](https://github.com/user-attachments/assets/686e5941-53cd-4ff3-a505-6be07f101d76)

**Comment by eliselavy** [comment]
> I see many issues
> spacing.. double figures
> 
> ![2024-07-15 13_59_30-Journal of Digital History](https://github.com/user-attachments/assets/c154f8e2-9bf0-4942-9326-879daf73d42c)
> 
> ![2024-07-15 14_00_31-Journal of Digital History](https://github.com/user-attachments/assets/d3296844-7a25-4521-87ed-a4c54f4bdb4b)
> 
> did the script already run for the images? probably not.. many others have the same issue
> ![2024-07-15 14_01_24-Journal of Digital History](https://github.com/user-attachments/assets/9c3cfd52-bee8-4baa-8341-88de3c027ee6)
> 
> 
> 

fir the spacing and double label can you correct the md files @biumiamy ?

i go to check space figure

**Comment by biumiamy** [comment]
yes I can correct in the md file, no problem

**Comment by biumiamy** [comment]
I think this headline level is wrong. Only Introduction has it. but he uses it multiple times for other headlines as well

![2024-07-15 14_07_04-Journal of Digital History](https://github.com/user-attachments/assets/d61f2478-7b92-4d59-adc4-a67cfd1f5c85)

**Comment by biumiamy** [comment]
Better style would be to merge the explanatory text and then the formula, I think..

![2024-07-15 14_08_10-Journal of Digital History](https://github.com/user-attachments/assets/8a30aed4-3fa2-4252-9bbf-5d99ebcfdcad)

**Comment by biumiamy** [comment]
All bibliography seems a bit inconsistent... and this happened

![2024-07-15 14_11_11-Journal of Digital History](https://github.com/user-attachments/assets/52338fdd-e35a-457a-8240-9cc0fdf86e7e)

**Comment by biumiamy** [comment]
I dont know why there's a double figure.. its not in the md file

![2024-07-15 14_27_27-paper md — C__Users_mirjam pfeiffer_Documents_GitHub_journal-of-digital-history-](https://github.com/user-attachments/assets/ec43cde3-fe2b-427f-aa90-2067e3529412)

**Comment by biumiamy** [comment]
I corrected what is possible in the md file:
https://github.com/jdh-observer/jnkqqTTKW8km/pull/8
can you merge @eliselavy ?

**Comment by eliselavy** [comment]
merge @biumiamy 
- correction biblio
- correction double label (due to two definitions of metadata one generated per code / one per the interface containing them ention Figure number

> investigation on the skim-article , in fact action tagged only until figure-2 

- about formula what do you mean more like below?
<img width="1001" alt="Screenshot 2024-07-15 at 18 48 02" src="https://github.com/user-attachments/assets/8afe22d1-5c29-4424-b5bd-73551829d33c">
in fact as before it was an image (in one cell) , i integrate the markdown formula in this cell

**Comment by eliselavy** [comment]
> figure 9... see figure 10? maybe not the best idea..
> 
> ![2024-07-15 14_04_58-Journal of Digital History](https://private-user-images.githubusercontent.com/47319502/348697290-686e5941-53cd-4ff3-a505-6be07f101d76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNTk0MDYsIm5iZiI6MTcyMTA1OTEwNiwicGF0aCI6Ii80NzMxOTUwMi8zNDg2OTcyOTAtNjg2ZTU5NDEtNTNjZC00ZmYzLWE1MDUtNmJlMDdmMTAxZDc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDE1NTgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjYjU4ZmFjNTdjZTAyYWQ0NWM4ZTdhMDM2ZGNmOWIyYWQ0ZGQ5ZGMyODMyOTQ1ZTExYmFhOWE5YTBiZDM2MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bhMilhlS3A0KWJXHMejnlTxUjZQbPRxM7T_YsAY7-pY)
> 
> same for figure 11 to 14 and 15 to 18

@inactinique correction or keep the lazy-style of the author ?

**Comment by biumiamy** [comment]
> - about formula what do you mean more like below?
> <img width="1001" alt="Screenshot 2024-07-15 at 18 48 02" src="https://github.com/user-attachments/assets/8afe22d1-5c29-4424-b5bd-73551829d33c">
> in fact as before it was an image (in one cell) , i integrate the markdown formula in this cell

Yes like that it's perfect :) now we don't have 1 million new cells with just one line. It will look much cleaner

**Comment by inactinique** [comment]
I think what's after the Conclusion (Implementation to Data avilability) should be in the hermeneutics layer.

**Comment by inactinique** [comment]
OK, I've done some other modifications. Can you have a look at it, @biumiamy (the part on implementation, preprocessing and data availability).

**Comment by biumiamy** [comment]
Looks good now!

**Comment by eliselavy** [comment]
@inactinique can be sent to the author for last check
@biumiamy as new hermeutics cell tagged, social media cover to be redo

**Comment by inactinique** [comment]
Sent to the author

**Comment by biumiamy** [comment]
updated social media cover

**Comment by eliselavy** [comment]
> > I see many issues
> > spacing.. double figures
> > ![2024-07-15 13_59_30-Journal of Digital History](https://private-user-images.githubusercontent.com/47319502/348696477-c154f8e2-9bf0-4942-9326-879daf73d42c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMTIxMTAsIm5iZiI6MTcyMzIxMTgxMCwicGF0aCI6Ii80NzMxOTUwMi8zNDg2OTY0NzctYzE1NGY4ZTItOWJmMC00OTQyLTkzMjYtODc5ZGFmNzNkNDJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDEzNTY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3OTBlMTE2MThmMzFkNDI4ODFiOGNiOWY5YmU0ZjhlN2EyNmRkZWU5ZThlNjEwZDM2N2NlZTg5YjFiMDU3NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nYeHk2sJ0voxSecKs_pAP9JZdQiAXV5yRjgWa9oKBVU)
> > ![2024-07-15 14_00_31-Journal of Digital History](https://private-user-images.githubusercontent.com/47319502/348696487-d3296844-7a25-4521-87ed-a4c54f4bdb4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMTIxMTAsIm5iZiI6MTcyMzIxMTgxMCwicGF0aCI6Ii80NzMxOTUwMi8zNDg2OTY0ODctZDMyOTY4NDQtN2EyNS00NTIxLTg3ZWQtYTRjNTRmNGJkYjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDEzNTY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkNGY3YTIyMzgxYTZiN2JjOGNkODVkNTFhNDEyMzU1YjFmN2I4ODI1NWFkMzY0MGY4ODI2NGYyMjM3ZjI2NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CDZwy712ZV5D4qFdzK55rmyWFtvVQ4GBzSJNdVB4M9Q)
> > did the script already run for the images? probably not.. many others have the same issue
> > ![2024-07-15 14_01_24-Journal of Digital History](https://private-user-images.githubusercontent.com/47319502/348696514-9c3cfd52-bee8-4baa-8341-88de3c027ee6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMTIxMTAsIm5iZiI6MTcyMzIxMTgxMCwicGF0aCI6Ii80NzMxOTUwMi8zNDg2OTY1MTQtOWMzY2ZkNTItYmVlOC00YmFhLTgzNDEtODhkZTNjMDI3ZWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDEzNTY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmZjFhMDU3ZjBkYTk4NjI1NWZjOTIxMDVlZjhjYjkxNzJjMWEzMGI5ODU3OTkwNjMyNTU0MzA2NGRjYWZjYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XtnXNg82wRo61sn47DjmxTXVDAdjFtVfRyNN7eq5NnY)
> 
> fir the spacing and double label can you correct the md files @biumiamy ?
> 
> i go to check space figure

fix wrong code / skim action not run properly stopped at figure-3 https://github.com/C2DH/journal-of-digital-history-ipynb-preflight-action/issues/37

<img width="1061" alt="Screenshot 2024-08-09 at 16 06 09" src="https://github.com/user-attachments/assets/1c87d7b5-94d6-40c7-8de6-b8ae11e52a8c">

less space than before

**Comment by eliselavy** [comment]
Need to resynchronize with the repo of the author:
and check problem here:

> '§' is inserted in two sections when I am rendering my notebook through the JDH website, could you please check what is going on?
> Evidence: the probability § of B given A
> We can formalize the relationship between the prior (X) and the evidence (H and T) as the probability § of observing presence h number of times

**Comment by eliselavy** [comment]
![Screenshot 2024-09-06 at 17 30 42](https://github.com/user-attachments/assets/96265488-3cb9-4f83-bfeb-d9a0ae4e41de)

**Comment by eliselavy** [comment]
![Screenshot 2024-09-06 at 17 31 33](https://github.com/user-attachments/assets/4e73959b-54e4-4298-8241-0ea9014a278b)

**Comment by eliselavy** [comment]
Merge changes / fixed bad caracter by escaping parentheses

**Comment by eliselavy** [comment]
Problem in the pdf the LaTeX mathematical formula are not properly rendered
<img width="938" alt="Screenshot 2024-09-06 at 18 44 24" src="https://github.com/user-attachments/assets/b7aacb84-89f9-41df-a071-02b256566d4f">

**Comment by eliselavy** [comment]
ready to be published on monday

**Comment by eliselavy** [comment]
PUBLISHED
@biumiamy social media to launch
