### ISSUE TITLE
Technical review for In search of an interpretative environment for digital traces: the building of Arvest

### ISSUE THREAD

**Issue by jdh-observer** [C2DH/jdh-notebook#176]
Technical review for In search of an interpretative environment for digital traces: the building of Arvest

pid : 8X2RX68Qavxr

https://github.com/jdh-observer/8X2RX68Qavxr

**Comment by eliselavy** [comment]
@danieleguido problem more than 12 columns , scroll in jupyter notebook not in front
https://journalofdigitalhistory.org/en/notebook-viewer/JTJGcHJveHktZ2l0aHVidXNlcmNvbnRlbnQlMkZqZGgtb2JzZXJ2ZXIlMkY4WDJSWDY4UWF2eHIlMkZtYWluJTJGYXJ0aWNsZS5pcHluYg==?idx=30

advice?
<img width="1399" alt="Screenshot 2024-08-08 at 18 15 09" src="https://github.com/user-attachments/assets/e4e380b4-0a51-4def-929a-9d0d7bdc67aa">

**Comment by eliselavy** [comment]
Missing label figures / tables

**Comment by eliselavy** [comment]
```
---> 12 display(Image("media/figure1.png", width=1000), metadata=metadata)
NameError: name 'Image' is not defined
```
https://github.com/jdh-observer/8X2RX68Qavxr/actions/runs/10321387424/job/28574168666

**Comment by eliselavy** [comment]
@biumiamy advices in order to reformat the columns

**Comment by eliselavy** [comment]
@biumiamy now the table will be a dataframe generated from a csv file 
see comments here before merge https://github.com/jdh-observer/8X2RX68Qavxr/pull/2

**Comment by biumiamy** [comment]
I think the best way finally is to set it up as a dataframe from scratch. Then it looks the best:

![2024-09-10 16_41_13-Window](https://github.com/user-attachments/assets/41901cf4-a86b-484d-a310-19c85f8c1253)

**Comment by biumiamy** [comment]
Okay I formatted a bit again. I think now it can be sent to the author @eliselavy

**Comment by eliselavy** [comment]
Authors contacted for missing labels and validation of the reformat table

**Comment by eliselavy** [comment]
Label to add:
Figure 1: A MemoRekall Capsule that tracks the creative process of Adrien M & Claire B's production of Hakanaï. Capsule created by Clarisse Bardiot, 2016.
Table 1: Comparative study of 51 video annotation softwares.
Table 2: Inventory of the 34 documents that compose the corpus of documents tracking the creative process of COESO's Pilot 2 study.

**Comment by eliselavy** [comment]
@inactinique sent to peer review
