### ISSUE TITLE
DH China global check

### ISSUE THREAD

**Issue by biumiamy** [C2DH/jdh-notebook#179]
Checking all articles

Here are the latest linked issues:

- #180 
- #163 
- #144 
- #129
- #135 
- #137

**Comment by biumiamy** [comment]
[ReOrienting Digital History: New frontiers in Chinese Studies](http://10.240.4.179/en/article/NpQvUTkRCF5T)

- something wrong with the cover, it's not fully generating the lower part (but the [image in the folder ](https://github.com/jdh-observer/NpQvUTkRCF5T/blob/main/media/liuri_wordcloud.png)shows it correctly)

**Comment by biumiamy** [comment]
[Machine-aided detection of sources in Jinpingmei](http://10.240.4.179/en/article/5QKJH5KQn9r3)

- keywords: "C"hinese fiction (capital C), "M"ing dynasty (capital M)

![2024-09-05 11_48_28-Journal of Digital History](https://github.com/user-attachments/assets/2a011ce2-0988-4bab-84e7-185b296d677d)

Spacing issue between citations..

![2024-09-05 11_56_55-Journal of Digital History](https://github.com/user-attachments/assets/7e0a671e-7b5f-4d20-b511-be6454575806)

And too much text in one cell.

![2024-09-05 11_58_14-C__Users_mirjam pfeiffer_Downloads_screenshots](https://github.com/user-attachments/assets/c0ba8271-6390-48fe-88e7-c6a0ecbb4ca7)

I will change it..

**Comment by biumiamy** [comment]
How did we handle this before in other articles?

![2024-09-05 13_27_48-Window](https://github.com/user-attachments/assets/4b8de29f-36ee-409d-a669-25ccd2f7602a)

**Comment by biumiamy** [comment]
And it continues.. for each section starting from 1 again:

![2024-09-05 14_32_21-Window](https://github.com/user-attachments/assets/26fd5a5a-48c2-42a3-a065-ff89cb856f42)

**Comment by inactinique** [comment]
How many of them are they ?

Usually we send them back to the author, with this simple instruction: either it’s important, and it should be in the body of the text, or it is not and it should be removed.


From: Mirjam Pfeiffer ***@***.***>
Date: Thursday, 5 September 2024 at 14:33
To: C2DH/jdh-notebook ***@***.***>
Cc: Frédéric CLAVERT ***@***.***>, Mention ***@***.***>
Subject: Re: [C2DH/jdh-notebook] DH China global check (Issue #179)

And it continues.. for each section starting from 1 again:

2024-09-05.14_32_21-Window.png (view on web)<https://github.com/user-attachments/assets/26fd5a5a-48c2-42a3-a065-ff89cb856f42>

**Comment by biumiamy** [comment]
if we send back anyway, the can also correct to paragraph per cell

**Comment by inactinique** [comment]
Indeed !

From: Mirjam Pfeiffer ***@***.***>
Date: Thursday, 5 September 2024 at 15:19
To: C2DH/jdh-notebook ***@***.***>
Cc: Frédéric CLAVERT ***@***.***>, Mention ***@***.***>
Subject: Re: [C2DH/jdh-notebook] DH China global check (Issue #179)

if we send it back anyway, they can also correct to paragraph per cell

**Comment by biumiamy** [comment]
update:
ReOrienting Digital History- New frontiers in Chinese Studies
- need to check skimmed or unskimmed version has problem? 
- problem in skimmed version

Machine-aided detection of sources in Jinpingmei: 
- update end of October by the author
-  send msg to author about changing the footnotes

**Comment by biumiamy** [comment]
Will you contact the author @inactinique ? about the footnotes issue

**Comment by inactinique** [comment]
Did not, yet, will do.


From: Mirjam Pfeiffer ***@***.***>
Date: Tuesday, 24 September 2024 at 11:03
To: C2DH/jdh-notebook ***@***.***>
Cc: Frédéric CLAVERT ***@***.***>, Mention ***@***.***>
Subject: Re: [C2DH/jdh-notebook] DH China global check (Issue #179)

Will you / did you contact the author @inactinique<https://github.com/inactinique> ? about the footnotes issue

**Comment by inactinique** [comment]
> Did not, yet, will do. From: Mirjam Pfeiffer ***@***.***> Date: Tuesday, 24 September 2024 at 11:03 To: C2DH/jdh-notebook ***@***.***> Cc: Frédéric CLAVERT ***@***.***>, Mention ***@***.***> Subject: Re: [C2DH/jdh-notebook] DH China global check (Issue #179) Will you / did you contact the author @inactinique<https://github.com/inactinique> ? about the footnotes issue 

email sent

**Comment by inactinique** [comment]
> Will you / did you contact the author @inactinique ? about the footnotes issue

done. Waiting for the answer.

**Comment by biumiamy** [comment]
closing this ticket and looking at the issues already opened per article instead
