### ISSUE TITLE
Review editorial DH China : ReOrienting Digital History: New frontiers in Chinese Studies

### ISSUE THREAD

**Issue by eliselavy** [C2DH/jdh-notebook#180]
- Problem of cover to be fixed @eliselavy 
- Review @inactinique 

https://github.com/jdh-observer/NpQvUTkRCF5T

**Comment by eliselavy** [comment]
Need to check why no skim-article not generated
https://github.com/jdh-observer/NpQvUTkRCF5T/actions/runs/10742613375/job/29795576147
 Working tree clean. Nothing to commit.

**Comment by eliselavy** [comment]
Problem of the cover fixed: http://10.240.4.179/en/article/NpQvUTkRCF5T?idx=3

**Comment by inactinique** [comment]
Some modifications to do in the text:
- Paragraph 5: Replace "The five papers that constitute this special issue illustrate the multifarious ways digital methods can be applied in the field of Chinese studies." by "The five papers that will progressively be published and constitute this special issue illustrate the multifarious ways digital methods can be applied in the field of Chinese studies."

**Comment by inactinique** [comment]
Modification done. Pull request + merge done
skim failed.

@eliselavy can you have a look at the failed job and then send to copy-edit?

**Comment by inactinique** [comment]
skim successful, finally.

@eliselavy you can send to copy-edit

**Comment by eliselavy** [comment]
Sent to copy-edit

**Comment by eliselavy** [comment]
@biumiamy from the copy editor
> There is only one minor correction on page 3. 
docx attached

**Comment by eliselavy** [comment]
@biumiamy copy-editing to add 
@inactinique DOI / copyright to request

**Comment by biumiamy** [comment]
copyediting integrated:
https://github.com/jdh-observer/NpQvUTkRCF5T/pull/3

**Comment by eliselavy** [comment]
> copyediting integrated: [jdh-observer/NpQvUTkRCF5T#3](https://github.com/jdh-observer/NpQvUTkRCF5T/pull/3)

Editorial in prod - not status published
@biumiamy social media cover can be added

**Comment by inactinique** [comment]
Licence + tweets asked.

**Comment by biumiamy** [comment]
social media cover added:
https://github.com/jdh-observer/NpQvUTkRCF5T/blob/main/socialmediacover.png
