### ISSUE TITLE
Design-review - Copy-editing - Technical -review - Merge after peer-review “The Secret History of the Mongols. A Digital History Approach”

### ISSUE THREAD

**Issue by eliselavy** [C2DH/jdh-notebook#181]
https://github.com/jdh-observer/Gqh2Bf5W4TdK

**Comment by eliselavy** [comment]
@inactinique Sent to peer-review

**Comment by eliselavy** [comment]
> @inactinique Sent to peer-review

need to send to copy-editing

**Comment by eliselavy** [comment]
Sent to copy-editing

**Comment by biumiamy** [comment]
apart from having to skim, for the design review: everything okay

**Comment by eliselavy** [comment]
@biumiamy  in production: https://journalofdigitalhistory.org/en/article/Gqh2Bf5W4TdK
@inactinique can be sent to the author for final check https://journalofdigitalhistory.org/en/notebook-viewer/JTJGcHJveHktZ2l0aHVidXNlcmNvbnRlbnQlMkZqZGgtb2JzZXJ2ZXIlMkZHcWgyQmY1VzRUZEslMkZtYWluJTJGc2tpbS1hcnRpY2xlLmlweW5i

**Comment by inactinique** [comment]
Answer from the author:

- Paragraph [5]: "SHM reliability is contentious" should be "SHM's reliability is contentious".
- Paragraph [20]: "Rachewiltz's translation" should be "De Rachewiltz's translation".
- Figure 2 caption: "Geolocation visualised on Sattelite view" should be "Geolocation visualised on Satellite view".
- Paragraph [31]: "OpenStreetMap is a conventional GIS application that showcases the city layout in flat Map format" should be "OpenStreetMap is a conventional GIS application that showcases the city layout in flat map format".
- Paragraph [55]: Please change the single quotations to double quotations for 'Γ č, š, γ Č ǰ, Š'.
 
@biumiamy possible to make the corrections?

**Comment by inactinique** [comment]
Licence chosen: Creative Commons Attribution-NonCommercial-NoDerivatives license as currently displayed on
https://creativecommons.org/licenses/by-nc-nd/4.0/

**Comment by biumiamy** [comment]
Corrections implemented in the md file:
https://github.com/jdh-observer/Gqh2Bf5W4TdK/pull/4

**Comment by eliselavy** [comment]
Synchronisation done / licence updated. /. ready to publish

**Comment by biumiamy** [comment]
added social media cover

**Comment by biumiamy** [comment]
the tweet is way too long..

![2024-10-11 10_13_57-Gqh2Bf5W4TdK_tweets md at main · jdh-observer_Gqh2Bf5W4TdK](https://github.com/user-attachments/assets/1c1c3b88-c102-4926-9464-7753e165feef)

**Comment by inactinique** [comment]
You can split it after the sentence ending with "enhances visualization and analysis." and, if needed, after the sentence ending with "philological standards.".

**Comment by biumiamy** [comment]
just saw this: it should be Satellite (instead of Sattelite)

![2024-10-14 16_03_11-Window](https://github.com/user-attachments/assets/ceabf1e6-3057-4bc3-8e05-fb7ee30cbc10)

**Comment by biumiamy** [comment]
But its strange, here it's correct?

![2024-10-15 09_05_26-Window](https://github.com/user-attachments/assets/ebe2e263-5702-4884-bd3e-52178dfe8263)

**Comment by eliselavy** [comment]
> But its strange, here it's correct?
> 
> ![2024-10-15 09_05_26-Window](https://private-user-images.githubusercontent.com/47319502/376495223-ebe2e263-5702-4884-bd3e-52178dfe8263.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5ODUxMjksIm5iZiI6MTcyODk4NDgyOSwicGF0aCI6Ii80NzMxOTUwMi8zNzY0OTUyMjMtZWJlMmUyNjMtNTcwMi00ODg0LWJkM2UtNTIxNzhkZmU4MjYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDA5MzM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1Yzk5NmNiYzRmNjkzYmYyZmQ3MGEzNjNhOTU4N2RiZDVlNmQ0ZmNiM2E1ZTg2MWQ5ZDNmYzExMDUxNDNkOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-JoZVf80wIcOlUP3h6khnFjah7R2MI4D6583mYjHZm8)

@biumiamy fixed
Problem of label defined also at the level of the metadata not reflected in the md file...
```
"metadata": {
            "jdh": {
              "module": "object",
              "object": {
                "source": [
                  "figure 2: Geolocation visualised on Sattelite view"
                ],
                "type": "image"
              }
            }
          },
          "output_type": "display_data"
        }
```

**Comment by eliselavy** [comment]
Social media launched
