### ISSUE TITLE
Technical review after R1 Chinese Political and Cultural Elites: Twentieth Century Transformations

### ISSUE THREAD

**Issue by eliselavy** [C2DH/jdh-notebook#182]
https://github.com/jdh-observer/JMU8e6tFQscz

**Comment by eliselavy** [comment]
@biumiamy same problem here , some figures are 46MB, can you look at in the media folder 

Branch revision
https://github.com/jdh-observer/JMU8e6tFQscz/tree/revision

**Comment by biumiamy** [comment]
Editorial point: figure 6 is not very well readable

![2024-09-13 10_24_51-Journal of Digital History](https://github.com/user-attachments/assets/99a47291-cf90-4d25-ad6f-8f04e6669317)

**Comment by biumiamy** [comment]
And for design review later: italic sections that are quotes -> add > for blockquote style

![2024-09-13 10_42_42-Journal of Digital History](https://github.com/user-attachments/assets/1c3a03df-25b6-41d9-8700-e5b5b8ba2202)

**Comment by eliselavy** [comment]
> Editorial point: figure 6 is not very well readable. Finally a lightbox would be useful..
> 
> ![2024-09-13 10_24_51-Journal of Digital History](https://private-user-images.githubusercontent.com/47319502/367210489-99a47291-cf90-4d25-ad6f-8f04e6669317.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTc3NTAsIm5iZiI6MTcyNjIxNzQ1MCwicGF0aCI6Ii80NzMxOTUwMi8zNjcyMTA0ODktOTlhNDcyOTEtY2Y5MC00ZDI1LWFkNmYtOGYwNGU2NjY5MzE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDA4NTA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkMTEyZmVlZTdkMGM1MjlmZDlkYmRiYzdkN2ZkNTYyOGViY2NlN2VkMjc3YzMyYzM4NjEyZjAyZTU2ZmQwOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r-a2ZPedt1IjvpmqnCeK5-iQ0JGKdEjOwhgF2iXKSWw)

@biumiamy do you try the skim?

**Comment by biumiamy** [comment]
Ah but this is unrelated to the skim.. It's about how the figure was designed from scratch. It's crazy long vertically. If it was horizontal, it would be better perhaps

**Comment by eliselavy** [comment]
> @biumiamy same problem here , some figures are 46MB, can you look at in the media folder
> 
> Branch revision https://github.com/jdh-observer/JMU8e6tFQscz/tree/revision

@biumiamy  i see your figures branch but not started from revisions

**Comment by biumiamy** [comment]
done: https://github.com/jdh-observer/6ig87tC5GKjQ/pull/4

**Comment by biumiamy** [comment]
Okay, I added it to the revision branch:
https://github.com/jdh-observer/JMU8e6tFQscz/commit/83c044383600d9b37c4d412a53ae192b47f5adc2

**Comment by eliselavy** [comment]
> Okay, I added it to the revision branch: [jdh-observer/JMU8e6tFQscz@83c0443](https://github.com/jdh-observer/JMU8e6tFQscz/commit/83c044383600d9b37c4d412a53ae192b47f5adc2)

do you not rename it without . in it as made for previous article, see here:
https://github.com/C2DH/jdh-notebook/issues/163#issuecomment-2353046810

same remark also , if we no more use png, in R find only this solution for the Jupyter notebook , need to be validated https://github.com/C2DH/jdh-notebook/issues/163#issuecomment-2367426926

otherwise need to keep png

**Comment by biumiamy** [comment]
ah. no problem I can do png. but the total size will be bigger for the notebook then

**Comment by eliselavy** [comment]
> ah. no problem I can do png. but the total size will be bigger for the notebook then

@biumiamy  f the solution mentionned above is ok, we can fit with jpeg
tell me

**Comment by biumiamy** [comment]
I checked the other solution, it doesnt work. So need to keep png

**Comment by biumiamy** [comment]
updated to png: https://github.com/jdh-observer/JMU8e6tFQscz/compare/master...revision

**Comment by eliselavy** [comment]
> updated to png: [jdh-observer/JMU8e6tFQscz@master...revision](https://github.com/jdh-observer/JMU8e6tFQscz/compare/master...revision)

@biumiamy code updated / run notebook / reconvert table in html now notebook has a good size 6.78 MB
can you check the anchor, can be updated in the md file

**Comment by biumiamy** [comment]
added anchors and corrected American to British English:
https://github.com/jdh-observer/JMU8e6tFQscz/pull/2

**Comment by eliselavy** [comment]
![Screenshot 2024-09-25 at 11 59 10](https://github.com/user-attachments/assets/ded6f6ef-1d98-4001-bd5f-2aaf9b25a4cc)

**Comment by eliselavy** [comment]
> https://github.com/jdh-observer/JMU8e6tFQscz

seems linked to 
![Screenshot 2024-09-25 at 12 00 17](https://github.com/user-attachments/assets/7c2744e9-ba5d-4511-89ee-b33d02cdd356)

**Comment by eliselavy** [comment]
> > ![Screenshot 2024-09-25 at 11 59 10](https://private-user-images.githubusercontent.com/35602279/370663526-ded6f6ef-1d98-4001-bd5f-2aaf9b25a4cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNTg2NzgsIm5iZiI6MTcyNzI1ODM3OCwicGF0aCI6Ii8zNTYwMjI3OS8zNzA2NjM1MjYtZGVkNmY2ZWYtMWQ5OC00MDAxLWJkNWYtMmFhZjliMjVhNGNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDA5NTkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5N2Y0MjNhOTRkNGQ2NjdhOTk3NTYwMDc3Y2I2ZTBiYTg0OGE1NTQ3NmFiODAxZWM5ODAyYTU3MGY1YzRlNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cBNCgv-JSBXtRekYjKtnwGD-E9xHDoUQPsVxuI8v9S8)
> 
> @biumiamy i merged also but this text should not be, can you correct and transform also [table-10](http://10.240.4.179/en/article/JMU8e6tFQscz?idx=132&layer=hermeneutics&lh=684&pidx=61) in html in Markdown (uses AI) ![Screenshot 2024-09-25 at 12 00 17](https://private-user-images.githubusercontent.com/35602279/370707037-22c5a6d8-e0f2-46dd-afbb-1bcafdea8e4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNTc1NDAsIm5iZiI6MTcyNzM1NzI0MCwicGF0aCI6Ii8zNTYwMjI3OS8zNzA3MDcwMzctMjJjNWE2ZDgtZTBmMi00NmRkLWFmYmItMWJjYWZkZWE4ZTRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDEzMjcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMGFlNjEyYmRhOGQwZGQxZWM3ZjQ4ZmU1NDk5YmM0MDJhMWM2NGY5YjRmYzAwMDhiODQ0ZjIzOTkwMWNlZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Sv5KM8HbNBFSLk_xoEBawiZXzQ8m1b7KCxjyssq3oxU)

done

**Comment by eliselavy** [comment]
@inactinique to be sent to PEER-REVIEW
