### ISSUE TITLE
Design review: advice for reformatting table 

### ISSUE THREAD

**Issue by eliselavy** [C2DH/jdh-notebook#183]
Can you look at and give advice  @biumiamy how to reformat

 [table-1](https://journalofdigitalhistory.org/en/notebook-viewer/JTJGcHJveHktZ2l0aHVidXNlcmNvbnRlbnQlMkZqZGgtb2JzZXJ2ZXIlMkZjTUZiRUJTcmlId0QlMkZmaXgtdGFnZ2luZyUyRmFydGljbGUuaXB5bmI=?idx=28&layer=hermeneutics&lh=684&pidx=28) and table-2 , there is a scrollbar but...

_Originally posted by @eliselavy in https://github.com/C2DH/jdh-notebook/issues/159#issuecomment-2379243236_

**Comment by biumiamy** [comment]
Here's a slimmer table-1

![2024-10-02 09_25_08-Journal of Digital History](https://github.com/user-attachments/assets/4d5904d1-6683-4da1-9392-f26ab6a8ae51)

**Comment by eliselavy** [comment]
> #159 (comment)

perfect can you look at also table-2, commit in a branch?

**Comment by biumiamy** [comment]
Yes, on it

**Comment by eliselavy** [comment]
Ok table-1 proposition integrated to main branch  https://github.com/jdh-observer/cMFbEBSriHwD/blob/main/article.ipynb, previous dataframe needs to be removed - and label to be added

**Comment by biumiamy** [comment]
table 2 done as well, PR here:
https://github.com/jdh-observer/cMFbEBSriHwD/pull/3

**Comment by biumiamy** [comment]
- added the data-table tag

**Comment by biumiamy** [comment]
I checked the tags again.. does it work now? Its really a problem that it sometimes doesn't save tags in Github.. when I change them in Docker (even with saving and closing the notebook)

**Comment by eliselavy** [comment]
> I checked the tags again.. does it work now? Its really a problem that it sometimes doesn't save tags in Github.. when I change them in Docker-run Jupyter Lab (even with saving and closing the notebook)

yes it works - indeed strange i will try to replicate this by testing as it can be a problem

just label are missing , they were include in the metadata before...
table-1
```
"jdh": {
     "module": "object",
     "object": {
      "source": [
       "English-Speaking Fandoms"
      ]
     }
```
table-2

```
"jdh": {
     "module": "object",
     "object": {
      "source": [
       "Russian-Speaking Fandoms"
      ]
     }
```
@biumiamy i will include them

**Comment by biumiamy** [comment]
Yes, I've been struggling with that.. thank you
