### ISSUE TITLE
Technical review before peer review: Debates on a Burden: Exploring the Connotations of the Wehrmacht in Post-War German Politics

### ISSUE THREAD

**Issue by jdh-observer** [C2DH/jdh-notebook#184]
Author's repo: https://github.com/maxte0/jdh_submission
PID: [BHmHNQKJaSWT](https://github.com/jdh-observer/BHmHNQKJaSWT)

**Comment by eliselavy** [comment]
Error my binder:
<img width="1119" alt="Screenshot 2024-11-07 at 15 14 13" src="https://github.com/user-attachments/assets/9f6576d6-7b59-403e-9e0d-d087ebed8e4c">
Error nbconvert:
https://github.com/jdh-observer/BHmHNQKJaSWT/actions/runs/11724160914/job/32657427336

**Comment by eliselavy** [comment]
@inactinique email sent to the author about issue to load the pkl file

**Comment by inactinique** [comment]
Thanks!

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by eliselavy** [comment]
Need to resynchronize with author / pkl changes in csv

**Comment by eliselavy** [comment]
- now possible to load csv
- test onmybinder ok
- can test reproducibility until this part:

![Screenshot 2024-11-25 at 11 39 49](https://github.com/user-attachments/assets/0d33d6cd-f11c-4ac3-ad31-877a0929685e)

**Comment by eliselavy** [comment]
Dataset GermaParl (v2.0.0) encompasses all proceedings up to the 19th legislative period, concluding in 2021

https://polmine.github.io/GermaParl2/
Dataset in Zenodo: https://doi.org/10.5281/zenodo.10416536.

**Comment by eliselavy** [comment]
@inactinique to sent to peer review
