### ISSUE TITLE
Merge last revision  Interactive panels as explorative tools of visual sources: continuing Warburg’s epistemological principles

### ISSUE THREAD

**Issue by eliselavy** [C2DH/jdh-notebook#186]
https://github.com/jdh-observer/48RGuzM4qfVA

**Comment by eliselavy** [comment]
@inactinique do you need to send back to review or not?

**Comment by inactinique** [comment]
> @inactinique do you need to send back to review or not?

yes

**Comment by eliselavy** [comment]
- Missing label
- Undefined reference
- and monuments (<cite data-cite=“undefined”>Antei, 1995</cite>; <cite data-cite=“7299034/RTPHGI8V”>De la Maza et al., 2016</cite>).
![Screenshot 2024-10-30 at 14 35 26](https://github.com/user-attachments/assets/dc9d22da-6ddd-4b1e-8fc5-0ccbedccb918)

**Comment by eliselavy** [comment]
Insert Iframe Observable , need to define the good height @biumiamy see here review branch
[https://journalofdigitalhistory.org/en/notebook-viewer/JTJGcHJveHktZ2l0aHVidXNlcmNvbnRlbnQ[…]56&layer=narrative&lh=1140&pidx=56&pl=hermeneutics&y=85](https://journalofdigitalhistory.org/en/notebook-viewer/JTJGcHJveHktZ2l0aHVidXNlcmNvbnRlbnQlMkZqZGgtb2JzZXJ2ZXIlMkY0OFJHdXpNNHFmVkElMkZyZXZpZXclMkZhcnRpY2xlLmlweW5i?idx=56&layer=narrative&lh=1140&pidx=56&pl=hermeneutics&y=85)

**Comment by eliselavy** [comment]
@biumiamy in main if you can fix citation and width

**Comment by eliselavy** [comment]
> I did the citation: [jdh-observer/48RGuzM4qfVA#5](https://github.com/jdh-observer/48RGuzM4qfVA/pull/5)
> 
> I think the width 800 is okay. thats the best for our journal anyway. Ofc.. finally the usability of their project is the real issue. But thats their responsibility.. ;)

consolidation made can you check if can be sent to peer-review @biumiamy

**Comment by biumiamy** [comment]
I found two more, I sent the md file.

and there is one [undefined](http://10.240.4.179/en/notebook-viewer/JTJGcHJveHktZ2l0aHVidXNlcmNvbnRlbnQlMkZqZGgtb2JzZXJ2ZXIlMkY0OFJHdXpNNHFmVkElMkZtYWluJTJGYXJ0aWNsZS5pcHluYg==?idx=68&layer=narrative&lh=1321&pidx=68&pl=narrative&y=462)

![2024-11-07 10_43_29-Journal of Digital History](https://github.com/user-attachments/assets/a0bab051-e1a6-4e46-87ee-82edc6b72b88)

and some strange formatting. 

![2024-11-07 10_44_08-Journal of Digital History](https://github.com/user-attachments/assets/c2c3ef4d-d83b-475a-846c-cdf4a4bca2b0)

but in the notebook there's no issue..

![2024-11-07 10_46_07-article md — C__Users_mirjam pfeiffer_Documents_GitHub_journal-of-digital-histor](https://github.com/user-attachments/assets/c9c5ace5-c62f-4959-9046-377bd19426ad)

**Comment by eliselavy** [comment]
> I found two more, I sent the md file.
> 
> and there is one [undefined](http://10.240.4.179/en/notebook-viewer/JTJGcHJveHktZ2l0aHVidXNlcmNvbnRlbnQlMkZqZGgtb2JzZXJ2ZXIlMkY0OFJHdXpNNHFmVkElMkZtYWluJTJGYXJ0aWNsZS5pcHluYg==?idx=68&layer=narrative&lh=1321&pidx=68&pl=narrative&y=462)
> 
> ![2024-11-07 10_43_29-Journal of Digital History](https://private-user-images.githubusercontent.com/47319502/383903923-a0bab051-e1a6-4e46-87ee-82edc6b72b88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NzMzNzcsIm5iZiI6MTczMDk3MzA3NywicGF0aCI6Ii80NzMxOTUwMi8zODM5MDM5MjMtYTBiYWIwNTEtZTFhNi00ZTQ2LTg3ZWUtODJlZGM2YjcyYjg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDA5NTExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwMzgyNDRlYzljMzViOTU1OTU4MTY1OGZlYTFmODE3YjBlZDgzY2FkMmI5ZDMxNTEzNzFhZjI5NTUwZmFkZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ejditgj6AoOUyL87vAQGqfq1vON4iGcueTUxWQhk-Nk)
> 
> and some strange formatting.
> 
> ![2024-11-07 10_44_08-Journal of Digital History](https://private-user-images.githubusercontent.com/47319502/383903989-c2c3ef4d-d83b-475a-846c-cdf4a4bca2b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NzMzNzcsIm5iZiI6MTczMDk3MzA3NywicGF0aCI6Ii80NzMxOTUwMi8zODM5MDM5ODktYzJjM2VmNGQtZDgzYi00NzVhLTg0NmMtY2RmNGE0YmNhMmIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDA5NTExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1ZDQxN2NlZGU3OTUxZDM5Yjk5MGRiMDI4ODI0ODdlOWQ4NGFiZmJkM2U3NTI5ZjA5NjRjMTg5YWVhMjg0OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.s4lyf_Zmu7p6NIKiLqZMItohx8-y-L0fciHysTZWZbY)
> 
> but in the notebook there's no issue..
> 
> ![2024-11-07 10_46_07-article md — C__Users_mirjam pfeiffer_Documents_GitHub_journal-of-digital-histor](https://private-user-images.githubusercontent.com/47319502/383904042-c9c5ace5-c62f-4959-9046-377bd19426ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NzMzNzcsIm5iZiI6MTczMDk3MzA3NywicGF0aCI6Ii80NzMxOTUwMi8zODM5MDQwNDItYzljNWFjZTUtYzYyZi00OTU5LTkwNDYtMzc3YmQxOTQyNmFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDA5NTExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyZTJhNTU0NjVlNDc5NDkyNzcyNzc1YzdjMDM4MTgxNDI3NTY0NDBkNjhjNzE0NmRlMTNiNjMzY2YzN2YwNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RgByoaRJh1QsKADRUqChsU7WCurvrjpHU9k9C45uHwg)

@biumiamy 
for the undefined: bug of cite2c if you add the same reference a second time, need to be replace with the good key
for the strange formatting link to the hyperlink of the title can not be cut

**Comment by eliselavy** [comment]
Author didn't resynchronize to jdh-observer  - redo work
@inactinique Sent to peer-review
