### ISSUE TITLE
overview of the plugin nb_extension_tagstyler

### ISSUE THREAD

**Issue by eliselavy** [C2DH/jdh-notebook#22]
pip install nb_extension_tagstyler

to implement : https://journalofdigitalhistory.org/en/guidelines#C-73

**Comment by eliselavy** [comment]
OH MY GOD still this issue by @biumiamy you test it ,now ? 
https://github.com/innovationOUtside/nb_extension_tagstyler mentioned in https://github.com/C2DH/journal-of-digital-history/issues/327#issuecomment-1240495044

**Comment by biumiamy** [comment]
We didn't follow up on it for a year, because of other priorities :)

**Comment by eliselavy** [comment]
Example added https://github.com/C2DH/jdh-notebook/blob/master/examples/tag_style.ipynb
