### ISSUE TITLE
Design review for two articles having pass the peer-review

### ISSUE THREAD

**Issue by eliselavy** [C2DH/jdh-notebook#32]
@biumiamy as similar works you made for this article https://github.com/C2DH/journal-of-digital-history/issues/102 can you made the design review for the following article: 

- http://10.240.4.179/en/article/JJszM3GwAYDs 
- http://10.240.4.179/en/article/L2gBr3BzwH8Z

For this one https://github.com/C2DH/journal-of-digital-history/issues/102 need to see if comments are still relevant with changes in the interface, by the way this article is not in this lastest version yet.

**Comment by eliselavy** [comment]
For this one http://10.240.4.179/en/article/JJszM3GwAYDs

**Comment by biumiamy** [comment]
include browser check

**Comment by biumiamy** [comment]
Safari - http://10.240.4.179/en/guidelines
paragraph numbering problem

![2021-10-12 11_03_04-Journal of Digital History — Mozilla Firefox](https://user-images.githubusercontent.com/47319502/136928257-a3b070ef-20d5-4de0-90fc-36f8d63b96af.png)

**Comment by biumiamy** [comment]
Links should open in new tabs?

- when opening any link, it opens in the **same** tab
- when clicking on the back button, the article needs to reload again...

**Comment by eliselavy** [comment]
articles have been published no more sense
