### ISSUE TITLE
Integrate the first editorial issue in a notebook after revision

### ISSUE THREAD

**Issue by eliselavy** [C2DH/jdh-notebook#33]
Integrate the first editorial issue

find a draft of the first editorial here: https://docs.google.com/document/d/1dSRZI1oyeWnGS1DaCt2lBmGGB4cYEMcZ77Wjw-Tm8WM/edit?usp=sharing

**Comment by eliselavy** [comment]
Need to be done before the 7 october as it's requested for the communication de gruyter https://github.com/C2DH/journal-of-digital-history/issues/190

@orielisar take in charge the update part of the scrollytelling

**Comment by eliselavy** [comment]
@biumiamy you can upload the editorial notebook here:
- https://github.com/jdh-observer/jdh001-jXupS3QAeNgb

**Comment by biumiamy** [comment]
https://github.com/jdh-observer/jdh001-jXupS3QAeNgb/blob/main/First_Issue_Editoral.ipynb

**Comment by biumiamy** [comment]
@inactinique will add the images and references

**Comment by biumiamy** [comment]
design proposal for the editorial @danieleguido 
https://www.figma.com/file/uqirjGAhT3VzfaO4Ts9GAl/Editorial-for-the-First-Issue?node-id=0%3A1
