### ISSUE TITLE
Reformat citation in two articles

### ISSUE THREAD

**Issue by eliselavy** [C2DH/jdh-notebook#43]
You put a reference into ()
example: (<cite ghfdohgfd/fjdifdsjo></cite>)
If several references are following each other, then they will as a group be put in (), separated into the () by a coma

Example:
(<cite fhjdskfhd.fjhdfd></cite>, <cite fhiughreubg/hfdjhgfdj></cite>)

If numbers of pages: (<cite ghfdohgfd/fjdifdsjo></cite>, p. 56)

Exception: if the sentence is engaging directly with the book. '<cite fhdjskfdhsk/rjeirhj></cite> argues that...' 

And if pages quoted in this case: '<cite fhdjskfdhsk/rjeirhj></cite> (P. 78) argues that...'

**Comment by biumiamy** [comment]
updated https://github.com/C2DH/jdh-notebook/blob/master/examples/Author_Guideline/AuthorGuideline.ipynb
