### ISSUE TITLE
Word spelling / improvment

### ISSUE THREAD

**Issue by jdh-observer** [C2DH/jdh-notebook#44]
- [x] **On pyramids, prisms, and scalable reading**

Abstract: skeched > sketched · practive > practice
7: modeling > modelling · datasets, but > datasets but · V’s > Vs
9: „tools“ > “tools”
14: github > GitHub
15: scholarschip > scholarship
18: endeavor > endeavour
21: dataverse > Dataverse · jupyter notebooks > Jupyter notebooks
22: jupyter notebooks > Jupyter notebooks
23: dataverse > Dataverse · dataverse > Dataverse
24: jupyter notebooks > Jupyter notebooks · pdf > PDF
26: time-span > time span · centered > centred
34: meager > meagre

- [x] **The Nameless Crowds: Using Quantitative Data and Digital Tools to Study the Ancient Vocabulary of the Crowd in Tacitus**

78: occurences > occurrences · occurences > occurrences · occurences > occurrences
figure 9a: reccurrence > recurrence
figure 9b: reccurrence > recurrence
126: eg : > eg: · eg : > eg: · eg : > eg:
130: studied.Figure 10 > studied. Figure 10 · reccurrence > recurrence
figure 10: reccurrence > recurrence
177: earlier, but > earlier but
183: whole, and > whole and
186: above mentioned > above-mentioned
193: this cases > these cases
Bibliography: 2) : osservazioni > 2): osservazioni
3:30

- [x] Digital history of representations: analysing identity and nationalism in the Capuchin Annual periodical (1930-1977)

4: British Empire and > British Empire, and
50: outlook.The > outlook. The
figure 4: realting > relating

- [x] **Topic-specific corpus building: A step towards a representative newspaper corpus on the topic of return migration using text mining methods**

Abstract: analyzed > analysed
3: scarce and > scarce, and · analyze > analyse
6: for and > for, and
12: appropriatly > appropriately
19: labeled > labelled
20: labeled > labelled
23: treshold > threshold
24: unlabeled > unlabelled · modeling > modelling · modeling > modelling
41: Classifiy > Classify
44: modeling > modelling · modeling > modelling
45: modeling > modelling
49: modeling > modelling
54: newsapaper > newspaper
60: labeled > labelled
71: labeled > labelled
73: unlabeled > unlabelled

**Comment by eliselavy** [comment]
correction integrated here https://github.com/jdh-observer/jdh001-4yxHGiqXYRbX/commit/e0c3bc1f658cdd2706c321913acc4620ce7d3830
