### ISSUE TITLE
Merge revision for article https://github.com/jdh-observer/jdh001-SLCj9T3MsrEk

### ISSUE THREAD

**Issue by eliselavy** [C2DH/jdh-notebook#51]
Merge revision for article https://github.com/jdh-observer/jdh001-SLCj9T3MsrEk

zip file

**Comment by inactinique** [comment]
> @inactinique merge / anchor / tagging / citation between () to check http://10.240.4.179/en/article/SLCj9T3MsrEk

@eliselavy I am not sure to see what you mean here. Can you be more explicit?
