### ISSUE TITLE
Merge revision for article http://10.240.4.179/en/article/8pGzPyTDKBjR

### ISSUE THREAD

**Issue by eliselavy** [C2DH/jdh-notebook#56]
Merge revision for article http://10.240.4.179/en/article/8pGzPyTDKBjR

**Comment by eliselavy** [comment]
- tag / metadatas previously added no more present =>. need to add again
- problem with BokehJS 2.3.0

**Comment by eliselavy** [comment]
<img width="912" alt="Screenshot 2021-11-18 at 12 02 01" src="https://user-images.githubusercontent.com/35602279/142403502-124151df-cf7e-4098-bc38-435a5b437484.png">

**Comment by eliselavy** [comment]
https://github.com/C2DH/journal-of-digital-history/issues/296

**Comment by inactinique** [comment]
@eliselavy So, are the issues solved?

**Comment by eliselavy** [comment]
@inactinique the Bokeh support is still on development https://github.com/C2DH/journal-of-digital-history/issues/296

**Comment by eliselavy** [comment]
reference fixed - bokeh on dev
