### ISSUE TITLE
Prepare publication for https://github.com/jdh-observer/jdh002-8pGzPyTDKBjR

### ISSUE THREAD

**Issue by eliselavy** [C2DH/jdh-notebook#65]
- copyright
- keywords
- remove bokeh image 
- generate citation

- social media

 I will use the CC-BY license. My keywords are: "Collective Violence," "Extralegal Violence," "GIS," "Rioting," "Vigilantism," "Lynching," and "United States of America."

**Comment by eliselavy** [comment]
@orielisar upload socialmedia image in dedicated repository https://github.com/jdh-observer/jdh002-8pGzPyTDKBjR (normally will be for 7 march )

**Comment by eliselavy** [comment]
@biumiamy socialmedia image to be uploaded in : https://github.com/jdh-observer/jdh002-8pGzPyTDKBjR
Designer will upload the image in the dedicated repository
Image will be name : socialmediacover

**Comment by biumiamy** [comment]
@eliselavy social media asset was uploaded to the [folder](https://github.com/jdh-observer/jdh002-8pGzPyTDKBjR)
