### ISSUE TITLE
Integrate last revisions for media in the Kinora's article

### ISSUE THREAD

**Issue by eliselavy** [C2DH/jdh-notebook#68]
Integrate revisions : 

https://github.com/jdh-observer/jdh001-33pRxE2dtUHP

Revision Andy:
send by email 

Revision  Media
[Replicating the Kinora - revisions figures 22-03-22.docx](https://github.com/C2DH/jdh-notebook/files/8349126/Replicating.the.Kinora.-.revisions.figures.22-03-22.docx)

**Comment by eliselavy** [comment]
Move the video from DEMA folder https://vimeo.com/manage/folders/2177592 to JDH folder https://vimeo.com/manage/folders/2590873 

https://vimeo.com/543497595/836466f3d6
https://vimeo.com/501153807/c1e7bf4504

and update the notebook

**Comment by eliselavy** [comment]
Furthermore, as I announced in my last email, I have been working on the Zenodo link, which you can find here: https://zenodo.org/record/6417747
Please add this link to the beginning of the article, similar to how it’s done in this JDH-article (so after abstract the rights statement, then the link to Zenodo-depository, then the acknowledgements, then the figure): https://journalofdigitalhistory.org/en/article/WBqfZzfi7nHK
 
The GitHub links that are currently in paragraphs 136 can be replaced by the direct permanent links to the stl and stp files part of the Zenodo-depository:
- STL: https://zenodo.org/record/6417747/files/Kinora%20Replica%203D%20Model.stl?download=1
- STP: https://zenodo.org/record/6417747/files/Kinora%20Replica%203D%20Model.stp?download=1

**Comment by biumiamy** [comment]
[done](https://github.com/jdh-observer/jdh001-33pRxE2dtUHP/pull/3)
