### ISSUE TITLE
Coming article with audio files + Clarin Elan files (analysis of audio files)

### ISSUE THREAD

**Issue by inactinique** [C2DH/jdh-notebook#73]
One of the recently submitted abstract is an article that will use audio files and Clarin Elan files (analysis of audio files).

- [Clarin Elan](https://archive.mpi.nl/tla/elan)

**Comment by eliselavy** [comment]
### Question of the size of the data

1Giga of audio materials
Advice :
Work on fragment and not the full audio files
Maybe full audio files in data verse
Use Ipython.display.Audio to play Audio
[ipython audio](https://musicinformationretrieval.com/ipython_audio.html)

### Oral video
Transcript
3 different formats: - monolog
				- 2 monologs
				- 3 monologs
How to render Interactivity of the digital coffee?

Export the csv , and try to produce visualisation Number of interaction according to the fragment / word cloud…


### About analysis made with MAXQDA
Export the visualisation made with the software
