### ISSUE TITLE
Technical review on article Contextualizing and unlocking political web defacements for research

### ISSUE THREAD

**Issue by eliselavy** [C2DH/jdh-notebook#79]
Github repository here: https://github.com/jdh-observer/hXsgcT9BZ5jP

**Comment by eliselavy** [comment]
mybinder:

ERROR: Could not find a version that satisfies the requirement glob==0.7 (from versions: none)
ERROR: No matching distribution found for glob==0.7

**Comment by eliselavy** [comment]
- python module included in requirements.txt: glob / datetime / IPython.display

- Missing model for spacy en_core_web_lg

```
File ~/.pyenv/versions/anaconda3-2020.02/envs/hXsgcT9BZ5jP/lib/python3.10/site-packages/spacy/util.py:439, in load_model(name, vocab, disable, enable, exclude, config)
    437 if name in OLD_MODEL_SHORTCUTS:
    438     raise IOError(Errors.E941.format(name=name, full=OLD_MODEL_SHORTCUTS[name]))  # type: ignore[index]
--> 439 raise IOError(Errors.E050.format(name=name))

OSError: [E050] Can't find model 'en_core_web_lg'. It doesn't seem to be a Python package or a valid path to a data directory.
```

**Comment by eliselavy** [comment]
---
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[24], line 11
      9 import gensim
     10 from gensim.utils import simple_preprocess
---> 11 import pyLDAvis.gensim_models
     12 stop_words = stopwords.words('english') #select English stopwords here
     13 #import nlp libraries for further text processing

ModuleNotFoundError: No module named 'pyLDAvis'
ModuleNotFoundError: No module named 'pyLDAvis'

**Comment by eliselavy** [comment]
Problem citation undefined and heading level not reflected in table of contents
<img width="1301" alt="Screenshot 2022-12-02 at 13 10 29" src="https://user-images.githubusercontent.com/35602279/205290437-0ceef429-c9c2-4c23-94df-1f2e40699051.png">
Reference for website not managed:

**Comment by eliselavy** [comment]
Wrong reference type:

**Comment by eliselavy** [comment]
TO DO: contact the author

**Comment by jdh-observer** [comment]
technical review made /  email sent to the author 06-12-2022
