### ISSUE TITLE
Technical review "Public opinion should be suspended until further report": A Data-Assisted Analysis of International Newspaper Coverage of the Explosion of the USS Maine (1898)

### ISSUE THREAD

**Issue by jdh-observer** [C2DH/jdh-notebook#84]
Technical review "Public opinion should be suspended until further report": A Data-Assisted Analysis of International Newspaper Coverage of the Explosion of the USS Maine (1898)

https://github.com/jdh-observer/aADj3Ljjqti2

**Comment by eliselavy** [comment]
- anonymisation
- addition script files
- update raw url
- light requirements.txt

**Comment by eliselavy** [comment]
Missing files:
"media/Get context.png"

**Comment by eliselavy** [comment]
addition nbformat==5.7.1
run nbconvert pb with output: 
<img width="216" alt="Screenshot 2023-01-03 at 17 19 37" src="https://user-images.githubusercontent.com/35602279/210397853-958f0472-2fbc-47ec-961c-375a7691090a.png">
