### ISSUE TITLE
Check if guidelines are coherent after removals of all references to hermeneutics-step or narrative-step

### ISSUE THREAD

**Issue by inactinique** [C2DH/jdh-notebook#87]
Please have a look here:
https://github.com/C2DH/jdh-notebook/blob/steps_removed/examples/Author_Guideline/AuthorGuideline.ipynb
and check if coherently removed all *-steps related things.
If so, I'll ask to merge this branch to the master branch.

@biumiamy @danieleguido @eliselavy

**Comment by eliselavy** [comment]
Still there here:
http://10.240.4.179/en/guidelines/AuthorGuideline-styling?idx=37
<img width="1100" alt="Screenshot 2023-06-22 at 16 42 29" src="https://github.com/C2DH/jdh-notebook/assets/35602279/112cd51f-29dc-47b8-8371-460bbf2fede1">

**Comment by inactinique** [comment]
As Mirjam did a major update of the guidelines, is it pertinent to still have this issue open?

**Comment by eliselavy** [comment]
indeed deploy in[ v4.2.1](https://github.com/C2DH/journal-of-digital-history/releases/tag/v4.2.0)
