### ISSUE TITLE
Technical review How do we avoid the loss of our digital memory: Challenges for the archiving (and analysis) of social media content

### ISSUE THREAD

**Issue by jdh-observer** [C2DH/jdh-notebook#95]
https://github.com/jdh-observer/m5GhKrrErgfE

https://github.com/hermesj/DigitalMemoryArticleAnonymous

We unfortunately had significant difficulties with the cite2c plugin. Although all literature should now be correctly linked, unfortunately all (incorrect) versions ever cited are now listed in the bibliography, although they no longer appear in the text. Is there a way to remove them?
 

Some of our graphics still need to be resized because there is too much white space underneath them. Since some of the essays published so far use different parameters, we would like to ask which one we should use, and then we would adjust it.
 

We included a table with 401 rows in the text. In the text, however, only 10 rows are shown. Is there any way to make the table interactive or to display the 401 rows in any other format?

**Comment by eliselavy** [comment]
Many ressources included in the repository not called https://github.com/jdh-observer/m5GhKrrErgfE/blob/main/output_2023-03-16%2009:19:33.817790.txt

**Comment by eliselavy** [comment]
GitGuardian has detected the following Okta Token exposed within your GitHub account.
--
Details- Secret type: Okta Token- Repository: jdh-observer/m5GhKrrErgfE- Pushed date: September 19th 2023, 10:49:39 UTC

GitGuardian has detected the following Okta Token exposed within your GitHub account.
Details

- Secret type: [Okta Token](https://github.com/jdh-observer/m5GhKrrErgfE/commit/37280059882525678d5e44effb6e69556af10bda#diff-f8e3dee84a0a4428d96d921bfe39c8942edde1f969eec8cadc6c11616b932041)


- Repository: jdh-observer/m5GhKrrErgfE

- Pushed date: September 19th 2023, 10:49:39 UTC

**Comment by eliselavy** [comment]
Check my binder ok 
Send for peer-review

**Comment by eliselavy** [comment]
3 unvalid urls: 
- https://developer.twitter.com/en/products/twitter-api/academic-research returned a 404 status code.
- https://library.stanford.edu/blogs/stanford-libraries-blog/2021/09/archiving-instagram-posts returned a 404 status code.
- https://nfdi4culture.de/de/aufgaben/services.html#service-10 returned a 404 status code.
