### ISSUE TITLE
Technical review Women in Early Modern Handwritten News: Random Walks and Semantic Wanderings in the Medici Archive

### ISSUE THREAD

**Issue by jdh-observer** [C2DH/jdh-notebook#97]
What shall I do with code that is CPU heavy? [I cannot cut the number of simulation cycles since that can alter results].

**Comment by jdh-observer** [comment]
%%time magic command in front of each cell to get a hint of the amount of CPU and wall clock time spent


https://mybinder.readthedocs.io/en/latest/about/user-guidelines.html

**Comment by eliselavy** [comment]
https://github.com/jdh-observer/jnkqqTTKW8km

**Comment by eliselavy** [comment]
Label of figures need to be added

**Comment by eliselavy** [comment]
<img width="883" alt="Screenshot 2023-04-18 at 17 31 38" src="https://user-images.githubusercontent.com/35602279/232827775-67d5b13a-e832-45c8-8afe-ae5361abbfc4.png">

**Comment by eliselavy** [comment]
For the moment formula need to be in a separate cell: https://github.com/C2DH/journal-of-digital-history/issues/540

**Comment by eliselavy** [comment]
Mybinder:
Problem installation package

```
 × Encountered error while trying to install package.
      ╰─> numpy
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for output from the failure.
      [end of output]

    numpy/core/src/multiarray/scalartypes.c.src: In function ‘unicodetype_repr’:
            numpy/core/src/multiarray/scalartypes.c.src:482:5: warning: ‘PyUnicode_AsUnicode’ is deprecated [-Wdeprecated-declarations]
                 ip = dptr = Py@Name@_AS_@NAME@(self);
                 ^~
            In file included from /srv/conda/envs/notebook/include/python3.10/unicodeobject.h:1046:0,
                             from /srv/conda/envs/notebook/include/python3.10/Python.h:83,

```

try with a runtime.txt

**Comment by eliselavy** [comment]
Mismatch in the figure citation , between one tag per user and one made by automatic tag
![Screenshot 2023-04-19 at 16 55 59](https://user-images.githubusercontent.com/35602279/233115756-6a7e4802-6914-4786-90bd-8e7ae9f9d784.png)

**Comment by eliselavy** [comment]
To fix: https://github.com/C2DH/journal-of-digital-history/issues/554

**Comment by eliselavy** [comment]
[peer_review_jnkqqTTKW8km.pdf](https://github.com/C2DH/jdh-notebook/files/11817146/peer_review_jnkqqTTKW8km.pdf)

**Comment by eliselavy** [comment]
Recheck binder - run correctly - take times
