### ISSUE TITLE
Technical review Designing Our Digital Past: Anchoring Digital-History Tool Development in the Historical Method Through Design-Based History Research

### ISSUE THREAD

**Issue by eliselavy** [C2DH/jdh-notebook#98]
Authors remarks:

There are a few hermeneutic and data cells in there now, an iFrame of a Net.Create dataset using the code you sent, and some citations from my Zotero library. I haven’t fed in any images yet because I’ve been focused on the structure and more complex technical pieces, but that’s an easy task and I’m not worried about it.

**Comment by eliselavy** [comment]
- Problem tagging table/figure
- No labelling
- Ressources missing
- HTML tag 
- Use of data tag - switch to data layer? 
<img width="951" alt="Screenshot 2023-03-16 at 10 32 40" src="https://user-images.githubusercontent.com/35602279/225575160-03fea017-7d59-4399-9370-2657650ba131.png">

**Comment by jdh-observer** [comment]
Final version submitted the 11/05

**Comment by eliselavy** [comment]
- No caption  table / figure
- Iframe html not displayed in frontend
![Screenshot 2023-05-25 at 16 54 25](https://github.com/C2DH/jdh-notebook/assets/35602279/4bc674c8-32ff-4f78-a710-d65f772b59b7)
- remove html tag
![Screenshot 2023-05-25 at 16 52 20](https://github.com/C2DH/jdh-notebook/assets/35602279/965271d4-9a17-4b78-9482-d0b6f016e50a)
- Problem in reference
![Screenshot 2023-05-25 at 16 57 24](https://github.com/C2DH/jdh-notebook/assets/35602279/04d5a904-0e9c-474b-bffa-6fa0b356b849)

**Comment by eliselavy** [comment]
Problem ordered list in table : https://github.com/C2DH/journal-of-digital-history/issues/554

**Comment by eliselavy** [comment]
[peer_review_BGU3PDv9p7pC.pdf](https://github.com/C2DH/jdh-notebook/files/11817705/peer_review_BGU3PDv9p7pC.pdf)
