### ISSUE TITLE
Integrate copy -editing for the article of Taking the Measure of Social Democracy: Exploring the Ideology of the Socialist International through Topic Modeling

### ISSUE THREAD

**Issue by eliselavy** [C2DH/jdh-notebook#99]
https://github.com/jdh-observer/jdh001-MyifnvNPDgUx/blob/main/taking-the-measure-of-social-democracy.ipynb

[Costa_LanguageReview AOD 24-01-2023.docx](https://github.com/C2DH/jdh-notebook/files/10696179/Costa_LanguageReview.AOD.24-01-2023.docx)

**Comment by inactinique** [comment]
Done.

**Comment by inactinique** [comment]
@eliselavy can you check?

**Comment by eliselavy** [comment]
@biumiamy design review not my task - social media needs to be generated

**Comment by biumiamy** [comment]
could either of you tell me the author names? I need to add them to the social media asset..

**Comment by biumiamy** [comment]
Can I get access rights? I can't upload anything to the repo..

**Comment by biumiamy** [comment]
So is Andy reviewing right now and should I implement the changes then? or is it already finished :)

**Comment by biumiamy** [comment]
What happened here with the <chr>? Is it correct like this?
![2023-02-28 10_42_11-Window](https://user-images.githubusercontent.com/47319502/221815234-10533d10-3c8d-4833-b5e4-a18324255c87.png)

**Comment by jdh-observer** [comment]
> So is Andy reviewing right now and should I implement the changes then? or is it already finished :)

I've done it yesterday.

**Comment by jdh-observer** [comment]
> What happened here with the (at the top of the table)? Is it correct like this?
> 
> ![2023-02-28 10_42_11-Window](https://user-images.githubusercontent.com/47319502/221815234-10533d10-3c8d-4833-b5e4-a18324255c87.png)

I'm not sure I do understand what you mean? Can you precise?

**Comment by biumiamy** [comment]
the <chr> should not be there I think?

**Comment by inactinique** [comment]
> the "chr" should not be there I think?

OK, sorry did not get that. I'll change that right away. I also gave you access right (and logged out / logged in to get back my proper identity :) )

**Comment by biumiamy** [comment]
yes, now it worked :) I added the socialmediacover

**Comment by biumiamy** [comment]
the "A data.frame: 18 × 2" is also a bit weird above the table. Is it correct as well?

**Comment by biumiamy** [comment]
it seems to be here again in the table above figure 10

![2023-02-28 11_01_59-Window](https://user-images.githubusercontent.com/47319502/221820432-4e7c4f02-ec74-4dca-bc39-845323679ef0.png)

**Comment by inactinique** [comment]
It's in all tables (data.frame + <chr> and sometimes <!-/>

**Comment by inactinique** [comment]
But it's generated by the R code based on data files, I suppose. I need to check the files and to see what we can do about it.

**Comment by biumiamy** [comment]
okay I see

**Comment by biumiamy** [comment]
except for the table issue, the rest looks fine. I only found only one tiny thing, there's a space missing here:

![2023-02-28 10_39_24-Window](https://user-images.githubusercontent.com/47319502/221824605-0d00dd54-d4da-4ac4-a0bd-a8e22ef1ab99.png)

**Comment by eliselavy** [comment]
@inactinique  Ok Licence CC-BY was already  inserted in the notebook  - legal document saved in atlas

**Comment by eliselavy** [comment]
@biumiamy Integrate last remarks made by the author - after this made inform me in order to regenerate:
- citation 
- fingerprint
- download

I have changed my affiliation since submission, so we have to update that. My current affiliation is "Scuola Normale Superiore, Pisa", the institutional mail address is ettore.costa@sns.it 

There are two bigger problems. One is whether to change references to my past work. Whenever the article says "Costa argued" should we change it to "I argued"? We had to anonimyze the article for peer-review, but we could change it for publication. The interested paragraphs are 6, 12, 15, 101, 104.

The second problems is a couple of mistakes in the references, which I had corrected in my last version, but probably there was a misunderstanding. These are the following:
Van Kemseke publication date is wrong. It should 2006
There are two separate references to my 2022 article: 
 
Costa, E. (2022). Socialist World from Balancing East and West to Militant Anti-Communism: Reading the Beginning of the Cold War in the Journal of the Socialist International (1947–1949). Journal of Cold War History, 24(1).
 
 
 
Costa, E. (2022). From East-West Balancing to Militant Anti-Communism: The Socialist International and the Beginning of the Cold War, 1947–1949. Journal of Cold War Studies, 24(2), 95–131. https://doi.org/10.1162/jcws_a_01044
 
Only the second one is correct

Smaller mistakes in the text: 
 
abstract: "what role of European social democracy" to "what role European social democracy"
Paragraph 30: "Topic modeling works under the assumption that the order of the words within the document text is irrelevant" cancel "text"
Paragraph 57 should be also Narrative, not just hermenutics

**Comment by biumiamy** [comment]
•	<s>Van Kemseke publication date is wrong. It should be 2006 (instead of 2017)</s>

**Comment by biumiamy** [comment]
![2023-03-06 16_12_14-taking-the-measure-of-social-democracy - Jupyter Notebook](https://user-images.githubusercontent.com/47319502/223151276-7d3e3ae7-1616-452f-afe4-38a8dcbaac87.png)

**Comment by eliselavy** [comment]
@biumiamy not possible the double tag : pending issue https://github.com/C2DH/journal-of-digital-history/issues/323

**Comment by biumiamy** [comment]
Okay, its done, except for the email address. where does that go? @eliselavy @inactinique

**Comment by eliselavy** [comment]
@eliselavy i go to update the email to the database, or check if there is a mention in the article

**Comment by biumiamy** [comment]
https://github.com/jdh-observer/jdh001-MyifnvNPDgUx/pull/1

**Comment by biumiamy** [comment]
@inactinique all corrections are done

**Comment by inactinique** [comment]
Great! Will do the propaganda tomorrow.
